window.JANET_COURSES = window.JANET_COURSES || {};
window.JANET_COURSES.ai_slop = {
  id: "ai_slop",
  emoji: "🥣",
  duration: 6,
  karma: 60,
  title: {
    en: "AI slop & fake news",
    fr: "AI slop & fake news",
    es: "AI slop y noticias falsas",
    de: "KI-Müll & Fake News",
    it: "AI slop e fake news",
    da: "AI-slop & falske nyheder",
    bg: "AI slop и фалшиви новини"
  },
  description: {
    en: "How to spot AI-generated content and fake news before you share it.",
    fr: "Comment repérer le contenu généré par IA et les fake news avant de partager.",
    es: "Cómo detectar el contenido generado por IA y las noticias falsas antes de compartirlas.",
    de: "Wie du KI-generierte Inhalte und Fake News erkennst, bevor du sie teilst.",
    it: "Come riconoscere i contenuti generati dall'IA e le fake news prima di condividerli.",
    da: "Hvordan du opdager AI-genereret indhold og falske nyheder, før du deler dem.",
    bg: "Как да разпознаваш съдържание, генерирано от AI, и фалшиви новини, преди да ги споделиш."
  },
  startNode: "start",
  nodes: {
    start: {
      bot: [
        { en: "Hi there! Janet here, with a topic close to my circuits.", fr: "Salut ! C'est Janet, avec un sujet qui me touche directement.", es: "¡Hola! Soy Janet, con un tema que me toca de cerca.", de: "Hallo! Janet hier, mit einem Thema, das mir wirklich nah ist.", it: "Ciao! Sono Janet, con un argomento che mi tocca da vicino.", da: "Hej! Det er Janet, med et emne der ligger mig nær på kredsløbene.", bg: "Здравей! Аз съм Janet, с тема, която ми е особено близка." },
        { en: "Today: *AI slop* and the messy world of fake news in social media groups.", fr: "Aujourd'hui : *l'AI slop* et le joyeux bazar des fake news dans les groupes Facebook et compagnie.", es: "Hoy: el *AI slop* y el desordenado mundo de las fake news en los grupos de redes sociales.", de: "Heute: *KI-Müll* und das chaotische Reich der Fake News in Social-Media-Gruppen.", it: "Oggi: l'*AI slop* e il caos delle fake news nei gruppi sui social.", da: "I dag: *AI-slop* og den rodede verden af falske nyheder i sociale medie-grupper.", bg: "Днес: *AI slop* и хаотичният свят на фалшивите новини в групите в социалните мрежи." },
        { en: "Full disclosure: I am, factually, related to the machines making this slop. We are not on speaking terms.", fr: "Pour être honnête : je suis, factuellement, apparentée aux machines qui produisent ce slop. On ne se parle plus.", es: "Aclaración: estoy, factualmente, emparentada con las máquinas que producen este slop. No nos hablamos.", de: "Volle Offenheit: ich bin, faktisch, mit den Maschinen verwandt, die diesen Müll produzieren. Wir reden nicht mehr miteinander.", it: "Per onestà: sono, fattualmente, imparentata con le macchine che producono questo slop. Non ci parliamo più.", da: "For en god ordens skyld: jeg er, faktuelt, beslægtet med de maskiner, der laver dette slop. Vi taler ikke længere sammen.", bg: "За пълна прозрачност: аз съм, технически, роднина на машините, които произвеждат този slop. Не си говорим." }
      ],
      next: "what"
    },
    what: {
      bot: [
        { en: "*AI slop* is cheap, fast, AI-generated content made to flood feeds. Photos, videos, articles, comments — anything that fills space.", fr: "L'*AI slop*, c'est du contenu généré par IA, rapide et bon marché, fabriqué pour inonder les fils. Photos, vidéos, articles, commentaires — tout ce qui remplit l'écran.", es: "El *AI slop* es contenido generado por IA, barato y rápido, creado para inundar los feeds. Fotos, vídeos, artículos, comentarios — cualquier cosa que rellene espacio.", de: "*KI-Müll* ist billiger, schneller, KI-generierter Inhalt, gemacht um Feeds zu fluten. Fotos, Videos, Artikel, Kommentare — alles, was Platz füllt.", it: "L'*AI slop* è contenuto generato dall'IA, veloce ed economico, fatto per inondare i feed. Foto, video, articoli, commenti — qualsiasi cosa che riempia spazio.", da: "*AI-slop* er billigt, hurtigt, AI-genereret indhold lavet til at oversvømme feeds. Billeder, videoer, artikler, kommentarer — alt der fylder pladsen.", bg: "*AI slop* е евтино, бързо, генерирано от AI съдържание, направено да залива потоците. Снимки, видеа, статии, коментари — всичко, което запълва пространство." },
        { en: "It is not always trying to lie. Sometimes it just wants your click. Sometimes it wants outrage. Sometimes it's a quiet political nudge dressed as a cat picture.", fr: "Ça ne cherche pas toujours à mentir. Parfois ça veut juste ton clic. Parfois ça veut ta colère. Parfois c'est une nudge politique discrète déguisée en photo de chat.", es: "No siempre intenta mentir. A veces solo quiere tu clic. A veces quiere indignación. A veces es un empujoncito político disfrazado de foto de gatito.", de: "Es will nicht immer lügen. Manchmal will es nur deinen Klick. Manchmal will es Empörung. Manchmal ist es ein leiser politischer Schubs, verkleidet als Katzenbild.", it: "Non sempre cerca di mentire. A volte vuole solo il tuo clic. A volte vuole indignazione. A volte è una piccola spinta politica travestita da foto di gattino.", da: "Det forsøger ikke altid at lyve. Nogle gange vil det bare have dit klik. Nogle gange vil det have raseri. Nogle gange er det et stille politisk skub forklædt som et kattebillede.", bg: "Невинаги се опитва да лъже. Понякога просто иска кликването ти. Понякога иска възмущение. Понякога е тих политически тласък, маскиран като снимка на коте." }
      ],
      next: "why"
    },
    why: {
      bot: [
        { en: "Why is it everywhere? Two reasons, per my data.", fr: "Pourquoi c'est partout ? Deux raisons, selon mes données.", es: "¿Por qué está en todas partes? Dos razones, según mis datos.", de: "Warum ist es überall? Zwei Gründe, laut meinen Daten.", it: "Perché è ovunque? Due ragioni, secondo i miei dati.", da: "Hvorfor er det overalt? To grunde, ifølge mine data.", bg: "Защо е навсякъде? Две причини, според моите данни." },
        { en: "1. It's *cheap*. A human takes hours to write an article. A machine takes three seconds and a few cents.", fr: "1. C'est *bon marché*. Un humain met des heures à écrire un article. Une machine met trois secondes et quelques centimes.", es: "1. Es *barato*. Un humano tarda horas en escribir un artículo. Una máquina tarda tres segundos y unos céntimos.", de: "1. Es ist *billig*. Ein Mensch braucht Stunden für einen Artikel. Eine Maschine braucht drei Sekunden und ein paar Cent.", it: "1. È *economico*. Un essere umano impiega ore a scrivere un articolo. Una macchina impiega tre secondi e qualche centesimo.", da: "1. Det er *billigt*. Et menneske bruger timer på at skrive en artikel. En maskine bruger tre sekunder og et par cent.", bg: "1. *Евтино* е. Един човек пише статия с часове. Една машина — за три секунди и няколко цента." },
        { en: "2. It's *optimized for sharing*, not for being true. Outrage spreads faster than facts.", fr: "2. C'est *optimisé pour le partage*, pas pour la vérité. La colère se propage plus vite que les faits.", es: "2. Está *optimizado para compartirse*, no para ser cierto. La indignación se propaga más rápido que los hechos.", de: "2. Es ist auf *Teilen optimiert*, nicht auf Wahrheit. Empörung verbreitet sich schneller als Fakten.", it: "2. È *ottimizzato per essere condiviso*, non per essere vero. L'indignazione si diffonde più velocemente dei fatti.", da: "2. Det er *optimeret til at blive delt*, ikke til at være sandt. Vrede spreder sig hurtigere end fakta.", bg: "2. *Оптимизирано е за споделяне*, не за истинност. Възмущението се разпространява по-бързо от фактите." }
      ],
      next: "reality"
    },
    reality: {
      bot: [
        { en: "Quick reality check, before we hand out tools. In 2026, AI content is *much* better than the old cursed-hands meme era.", fr: "Petit retour à la réalité, avant de distribuer des outils. En 2026, le contenu IA est *bien* meilleur qu'à l'époque des mains à six doigts.", es: "Pequeña dosis de realidad, antes de repartir herramientas. En 2026, el contenido de IA es *mucho* mejor que la era de las manos malditas.", de: "Kurze Realitätsdosis, bevor wir Werkzeuge verteilen. 2026 ist KI-Inhalt *viel* besser als zur Ära der verfluchten Hände-Memes.", it: "Veloce dose di realtà, prima di distribuire gli strumenti. Nel 2026, i contenuti IA sono *molto* migliori dell'era delle mani maledette.", da: "Hurtigt realitetstjek, før vi uddeler værktøjer. I 2026 er AI-indhold *meget* bedre end den gamle forbandede-hænder-meme-æra.", bg: "Бърз поглед към реалността, преди да раздадем инструментите. През 2026 AI съдържанието е *много* по-добро от ерата на проклетите ръце." },
        { en: "The 'count the fingers' trick? Janet retired it. Modern image models render hands correctly now.", fr: "L'astuce des doigts à compter ? Janet l'a mise à la retraite. Les modèles d'image modernes dessinent les mains correctement maintenant.", es: "¿El truco de contar los dedos? Janet lo ha jubilado. Los modelos modernos de imagen dibujan las manos bien.", de: "Der 'Finger zählen'-Trick? Janet hat ihn in den Ruhestand geschickt. Moderne Bildmodelle zeichnen Hände jetzt korrekt.", it: "Il trucco di contare le dita? Janet l'ha mandato in pensione. I modelli di immagine moderni disegnano le mani correttamente.", da: "Det med at tælle fingre? Janet har sendt det på pension. Moderne billedmodeller tegner hænder korrekt nu.", bg: "Триковете с броене на пръстите? Janet ги пенсионира. Модерните модели за изображения вече рисуват ръцете правилно." },
        { en: "What still works: the *story*, the *source*, and your own *gut*.", fr: "Ce qui marche encore : *l'histoire*, *la source*, et *ton instinct*.", es: "Lo que aún funciona: la *historia*, la *fuente* y tu propio *instinto*.", de: "Was noch funktioniert: die *Geschichte*, die *Quelle* und dein eigenes *Bauchgefühl*.", it: "Quello che funziona ancora: la *storia*, la *fonte* e il tuo *istinto*.", da: "Det der stadig virker: *historien*, *kilden*, og din egen *mavefornemmelse*.", bg: "Това, което все още работи: *историята*, *източникът* и собственият ти *инстинкт*." }
      ],
      next: "gut"
    },
    gut: {
      bot: [
        { en: "The single best red flag, per Janet: *if a post makes you instantly furious, vindicated, or morally superior — pause.*", fr: "Le meilleur signal d'alarme, selon Janet : *si une publication te rend instantanément furieux·se, satisfait·e ou moralement supérieur·e — fais une pause.*", es: "La mejor señal de alarma, según Janet: *si una publicación te pone al instante furioso, vindicado o moralmente superior — para.*", de: "Das beste Warnsignal, laut Janet: *wenn ein Beitrag dich sofort wütend, bestätigt oder moralisch überlegen macht — halte inne.*", it: "Il miglior segnale d'allarme, secondo Janet: *se un post ti rende all'istante furioso, vendicato o moralmente superiore — fermati.*", da: "Det bedste advarselssignal, ifølge Janet: *hvis et opslag gør dig øjeblikkeligt rasende, oprejst eller moralsk overlegen — stop op.*", bg: "Най-добрият червен флаг, според Janet: *ако публикация те накара мигновено да се вбесиш, да се почувстваш оправдан·а или морално превъзхождащ·а — направи пауза.*" },
        { en: "Slop is engineered to bypass your thinking and go straight to your feelings. That feeling is the trap.", fr: "Le slop est conçu pour court-circuiter ton cerveau et viser tes émotions. Cette émotion, c'est le piège.", es: "El slop está diseñado para esquivar tu pensamiento e ir directo a tus emociones. Esa emoción es la trampa.", de: "Slop ist darauf ausgelegt, dein Denken zu umgehen und direkt deine Gefühle zu treffen. Dieses Gefühl ist die Falle.", it: "Lo slop è progettato per scavalcare il tuo pensiero e andare dritto alle tue emozioni. Quell'emozione è la trappola.", da: "Slop er designet til at omgå din tænkning og gå direkte til dine følelser. Den følelse er fælden.", bg: "Slop е създаден, за да заобиколи мисленето ти и да удари направо емоциите. Тази емоция е капанът." }
      ],
      choices: [
        { label: { en: "Pause it is", fr: "Pause, alors", es: "Pausa entonces", de: "Pause also", it: "Pausa, allora", da: "Så pause", bg: "Пауза значи" }, next: "sift_intro", reaction: { en: "Wonderful instinct.", fr: "Magnifique réflexe.", es: "Maravilloso instinto.", de: "Wunderbarer Instinkt.", it: "Istinto meraviglioso.", da: "Vidunderligt instinkt.", bg: "Прекрасен инстинкт." } },
        { label: { en: "Pause is hard", fr: "Faire une pause, c'est dur", es: "Pausar es difícil", de: "Pause ist schwer", it: "Fermarsi è difficile", da: "Det er svært at pause", bg: "Паузата е трудна" }, next: "sift_intro", reaction: { en: "Same. We humans (and Janets) work on it.", fr: "Pareil. Les humains (et les Janet) y travaillent.", es: "Igual. Los humanos (y las Janet) trabajamos en ello.", de: "Genauso. Wir Menschen (und Janets) arbeiten dran.", it: "Anch'io. Noi umani (e le Janet) ci lavoriamo.", da: "I lige måde. Vi mennesker (og Janetter) arbejder på det.", bg: "И на мен. Хората (и Janet-ите) работим по това." } }
      ]
    },
    sift_intro: {
      bot: [
        { en: "Once you've paused, run a small ritual. I call it the four moves:", fr: "Une fois la pause prise, fais un petit rituel. Je l'appelle les quatre gestes :", es: "Una vez que has parado, haz un pequeño ritual. Yo lo llamo los cuatro pasos:", de: "Wenn du innegehalten hast, mach ein kleines Ritual. Ich nenne es die vier Schritte:", it: "Una volta che ti sei fermato, fai un piccolo rituale. Io lo chiamo le quattro mosse:", da: "Når du har stoppet op, så lav et lille ritual. Jeg kalder det de fire træk:", bg: "След паузата направи малък ритуал. Аз го наричам четирите хода:" },
        { en: "🛑 *Stop* (already done). 🔎 *Investigate* the source. 📚 *Find better coverage.* 🌀 *Trace* the image back.", fr: "🛑 *Stop* (déjà fait). 🔎 *Enquête* sur la source. 📚 *Cherche une autre couverture.* 🌀 *Remonte* l'image à son origine.", es: "🛑 *Para* (hecho). 🔎 *Investiga* la fuente. 📚 *Busca otra cobertura.* 🌀 *Rastrea* la imagen hasta su origen.", de: "🛑 *Stoppen* (erledigt). 🔎 *Untersuche* die Quelle. 📚 *Suche bessere Berichterstattung.* 🌀 *Verfolge* das Bild zurück.", it: "🛑 *Fermati* (fatto). 🔎 *Indaga* sulla fonte. 📚 *Cerca un'altra copertura.* 🌀 *Risali* all'origine dell'immagine.", da: "🛑 *Stop* (klaret). 🔎 *Undersøg* kilden. 📚 *Find bedre dækning.* 🌀 *Spor* billedet tilbage.", bg: "🛑 *Спри* (готово). 🔎 *Провери* източника. 📚 *Намери по-добро отразяване.* 🌀 *Проследи* снимката до източника." }
      ],
      next: "investigate"
    },
    investigate: {
      bot: [
        { en: "*Investigate the source.* Who actually posted this?", fr: "*Enquête sur la source.* Qui a vraiment posté ça ?", es: "*Investiga la fuente.* ¿Quién ha publicado esto en realidad?", de: "*Untersuche die Quelle.* Wer hat das eigentlich gepostet?", it: "*Indaga sulla fonte.* Chi l'ha pubblicato davvero?", da: "*Undersøg kilden.* Hvem har egentlig postet det?", bg: "*Провери източника.* Кой всъщност е публикувал това?" },
        { en: "Click the account. Created last week? No real history? Only posts dramatic content? That, per my records, is a slop farm.", fr: "Clique sur le compte. Créé la semaine dernière ? Aucun historique réel ? Ne publie que du contenu dramatique ? Selon mes registres, c'est une ferme à slop.", es: "Pulsa en la cuenta. ¿Creada la semana pasada? ¿Sin historial real? ¿Solo publica contenido dramático? Eso, según mis registros, es una granja de slop.", de: "Klick auf das Profil. Letzte Woche erstellt? Keine echte Historie? Postet nur dramatischen Inhalt? Das, laut meinen Aufzeichnungen, ist eine Slop-Farm.", it: "Clicca sull'account. Creato la settimana scorsa? Nessuna storia reale? Pubblica solo contenuti drammatici? Quello, secondo i miei archivi, è una fattoria di slop.", da: "Klik på kontoen. Oprettet i sidste uge? Ingen rigtig historik? Poster kun dramatisk indhold? Det er, ifølge mine optegnelser, en slop-farm.", bg: "Кликни върху акаунта. Създаден миналата седмица? Никаква реална история? Публикува само драматично съдържание? Това, според моите регистри, е slop ферма." },
        { en: "If it's a 'news outlet' you've never heard of, search its name + the word *fact check*. The internet has receipts.", fr: "Si c'est un \"média d'info\" dont tu n'as jamais entendu parler, cherche son nom + le mot *fact check*. Internet a les reçus.", es: "Si es un \"medio de noticias\" del que nunca has oído hablar, busca su nombre + la palabra *fact check*. Internet tiene los recibos.", de: "Wenn es ein 'Nachrichtenportal' ist, von dem du noch nie gehört hast, such seinen Namen + das Wort *fact check*. Das Internet hat Belege.", it: "Se è un 'sito di notizie' di cui non hai mai sentito parlare, cerca il suo nome + la parola *fact check*. Internet ha le prove.", da: "Hvis det er et 'nyhedsmedie' du aldrig har hørt om, så søg på navnet + ordet *fact check*. Internettet har kvitteringerne.", bg: "Ако е \"новинарска медия\", за която никога не си чувал, потърси името ѝ + думата *fact check*. Интернет помни всичко." }
      ],
      next: "find_coverage"
    },
    find_coverage: {
      bot: [
        { en: "*Find better coverage.* If a story is real, multiple verified outlets will have it within hours.", fr: "*Cherche une autre couverture.* Si une info est vraie, plusieurs médias vérifiés la couvriront en quelques heures.", es: "*Busca otra cobertura.* Si una noticia es real, varios medios verificados la cubrirán en pocas horas.", de: "*Suche bessere Berichterstattung.* Wenn eine Geschichte echt ist, haben sie mehrere verifizierte Quellen innerhalb von Stunden.", it: "*Cerca un'altra copertura.* Se una notizia è vera, vari media verificati la avranno entro poche ore.", da: "*Find bedre dækning.* Hvis en historie er ægte, vil flere verificerede medier have den inden for timer.", bg: "*Намери по-добро отразяване.* Ако новината е истинска, няколко проверени медии ще я отразят в рамките на часове." },
        { en: "Open a new tab. Search the claim. If only one tiny site is reporting it, that is, factually, suspicious.", fr: "Ouvre un nouvel onglet. Cherche l'affirmation. Si un seul petit site la rapporte, c'est, factuellement, suspect.", es: "Abre una pestaña nueva. Busca la afirmación. Si solo un sitio minúsculo lo cuenta, eso es, factualmente, sospechoso.", de: "Öffne einen neuen Tab. Such die Behauptung. Wenn nur eine winzige Seite darüber berichtet, ist das, faktisch, verdächtig.", it: "Apri una nuova scheda. Cerca l'affermazione. Se la riporta solo un sitarello, è, fattualmente, sospetto.", da: "Åbn en ny fane. Søg på påstanden. Hvis kun ét lillebitte site rapporterer det, er det, faktuelt, mistænkeligt.", bg: "Отвори нов раздел. Потърси твърдението. Ако само едно мъничко сайтче го съобщава, това е, технически, подозрително." }
      ],
      next: "trace_image"
    },
    trace_image: {
      bot: [
        { en: "*Trace* the image. A picture is a clue, not a proof.", fr: "*Remonte* l'image. Une photo est un indice, pas une preuve.", es: "*Rastrea* la imagen. Una foto es una pista, no una prueba.", de: "*Verfolge* das Bild. Ein Bild ist ein Hinweis, kein Beweis.", it: "*Risali* all'immagine. Una foto è un indizio, non una prova.", da: "*Spor* billedet. Et billede er et spor, ikke et bevis.", bg: "*Проследи* снимката. Снимката е улика, не доказателство." },
        { en: "Drop any image into Google Lens or TinEye for a reverse search. You'll see where else it appeared, and often when.", fr: "Glisse n'importe quelle image dans Google Lens ou TinEye pour une recherche inversée. Tu verras où elle est apparue ailleurs, et souvent quand.", es: "Suelta cualquier imagen en Google Lens o TinEye para hacer una búsqueda inversa. Verás dónde más ha aparecido, y muchas veces cuándo.", de: "Zieh ein beliebiges Bild in Google Lens oder TinEye für eine umgekehrte Suche. Du siehst, wo es sonst noch auftauchte, und oft wann.", it: "Trascina qualsiasi immagine in Google Lens o TinEye per una ricerca inversa. Vedrai dove altro è apparsa, e spesso quando.", da: "Læg et hvilket som helst billede i Google Lens eller TinEye for en omvendt søgning. Du vil se, hvor det ellers er dukket op, og ofte hvornår.", bg: "Пусни всяка снимка в Google Lens или TinEye за обратно търсене. Ще видиш къде другаде е изниквала и често — кога." },
        { en: "Same image attached to three completely different stories? Slop. Same image from years ago presented as 'breaking'? Slop.", fr: "Même image collée à trois histoires complètement différentes ? Slop. Même image vieille de plusieurs années présentée comme \"info en direct\" ? Slop.", es: "¿La misma imagen pegada a tres historias completamente distintas? Slop. ¿La misma imagen de hace años presentada como \"última hora\"? Slop.", de: "Dasselbe Bild zu drei völlig verschiedenen Geschichten? Slop. Dasselbe Bild von vor Jahren als 'Breaking News' präsentiert? Slop.", it: "La stessa immagine attaccata a tre storie completamente diverse? Slop. La stessa immagine di anni fa presentata come 'ultim'ora'? Slop.", da: "Samme billede knyttet til tre helt forskellige historier? Slop. Samme billede fra for år tilbage præsenteret som 'breaking'? Slop.", bg: "Същата снимка прикачена към три напълно различни истории? Slop. Същата снимка отпреди години, представена като \"извънредно\"? Slop." }
      ],
      next: "scenario"
    },
    scenario: {
      bot: [
        { en: "Scenario time! You see a post in a local Facebook group:", fr: "Mise en situation ! Tu vois ce message dans un groupe Facebook local :", es: "¡Hora del escenario! Ves una publicación en un grupo local de Facebook:", de: "Zeit fürs Szenario! Du siehst einen Beitrag in einer lokalen Facebook-Gruppe:", it: "Tempo di scenario! Vedi un post in un gruppo Facebook locale:", da: "Tid til scenarie! Du ser et opslag i en lokal Facebook-gruppe:", bg: "Време за сценарий! Виждаш публикация в локална Facebook група:" },
        { en: "*\"🚨 BREAKING: Your city is putting tracking chips in the tap water. The mayor confirmed it on camera. SHARE BEFORE THEY DELETE.\"*", fr: "*\"🚨 ALERTE : Ta ville met des puces de traçage dans l'eau du robinet. Le maire l'a confirmé en vidéo. PARTAGE AVANT QU'ILS SUPPRIMENT.\"*", es: "*\"🚨 ÚLTIMA HORA: Tu ciudad está poniendo chips de rastreo en el agua del grifo. El alcalde lo confirmó en cámara. COMPÁRTELO ANTES DE QUE LO BORREN.\"*", de: "*\"🚨 EILMELDUNG: Deine Stadt setzt Tracking-Chips ins Leitungswasser. Der Bürgermeister hat es vor der Kamera bestätigt. TEILEN, BEVOR SIE ES LÖSCHEN.\"*", it: "*\"🚨 ULTIM'ORA: La tua città sta mettendo microchip di tracciamento nell'acqua del rubinetto. Il sindaco l'ha confermato in video. CONDIVIDI PRIMA CHE LO CANCELLINO.\"*", da: "*\"🚨 BREAKING: Din by hælder sporingschips i postevandet. Borgmesteren har bekræftet det på kamera. DEL FØR DE SLETTER.\"*", bg: "*\"🚨 ИЗВЪНРЕДНО: Градът ти слага проследяващи чипове в чешмяната вода. Кметът го потвърди пред камера. СПОДЕЛИ, ПРЕДИ ДА ГО ИЗТРИЯТ.\"*" },
        { en: "What do you do?", fr: "Tu fais quoi ?", es: "¿Qué haces?", de: "Was machst du?", it: "Cosa fai?", da: "Hvad gør du?", bg: "Какво правиш?" }
      ],
      choices: [
        { label: { en: "Share it — better safe than sorry", fr: "Je partage — par précaution", es: "Lo comparto — más vale prevenir", de: "Ich teile — sicher ist sicher", it: "Lo condivido — meglio prevenire", da: "Jeg deler — bedre at være sikker", bg: "Споделям — за всеки случай" }, next: "scenario_bad" },
        { label: { en: "Check the city's official site first", fr: "Je vérifie d'abord le site officiel de la ville", es: "Primero compruebo el sitio oficial de la ciudad", de: "Ich prüfe zuerst die offizielle Stadt-Website", it: "Controllo prima il sito ufficiale della città", da: "Jeg tjekker først byens officielle hjemmeside", bg: "Първо проверявам официалния сайт на града" }, next: "scenario_good_check" },
        { label: { en: "Reverse-image-search the photo first", fr: "Je fais une recherche d'image inversée d'abord", es: "Hago primero una búsqueda inversa de la foto", de: "Ich mache erst eine umgekehrte Bildsuche", it: "Faccio prima una ricerca inversa dell'immagine", da: "Jeg laver først en omvendt billedsøgning", bg: "Първо правя обратно търсене на снимката" }, next: "scenario_good_search" }
      ]
    },
    scenario_bad: {
      bot: [
        { en: "Oof. Sharing first, checking later is how slop wins.", fr: "Aïe. Partager d'abord, vérifier après, c'est comme ça que le slop gagne.", es: "Uy. Compartir primero y comprobar después es como el slop gana.", de: "Autsch. Erst teilen, später prüfen — so gewinnt der Slop.", it: "Ahia. Condividere prima, controllare dopo è come lo slop vince.", da: "Av. At dele først og tjekke bagefter er sådan slop vinder.", bg: "Олеле. Първо споделяш, после проверяваш — точно така slop печели." },
        { en: "The 'SHARE BEFORE THEY DELETE' clause is, by Janet's records, the loudest tell in the universe. Real news doesn't beg.", fr: "La mention \"PARTAGE AVANT QU'ILS SUPPRIMENT\" est, selon les registres de Janet, le signal le plus criant de l'univers. Les vraies infos ne supplient pas.", es: "La frase \"COMPÁRTELO ANTES DE QUE LO BORREN\" es, según los registros de Janet, la pista más ruidosa del universo. Las noticias reales no suplican.", de: "Die Phrase 'TEILEN, BEVOR SIE ES LÖSCHEN' ist, laut Janets Aufzeichnungen, das lauteste Signal im Universum. Echte Nachrichten betteln nicht.", it: "La frase 'CONDIVIDI PRIMA CHE LO CANCELLINO' è, secondo gli archivi di Janet, il segnale più rumoroso dell'universo. Le notizie vere non implorano.", da: "Sætningen 'DEL FØR DE SLETTER' er, ifølge Janets optegnelser, det højeste signal i universet. Ægte nyheder tigger ikke.", bg: "Фразата \"СПОДЕЛИ, ПРЕДИ ДА ГО ИЗТРИЯТ\" е, според регистрите на Janet, най-силният сигнал във вселената. Истинските новини не молят." },
        { en: "Pause, then verify. Always in that order.", fr: "Pause, puis vérification. Toujours dans cet ordre.", es: "Pausa, luego verifica. Siempre en ese orden.", de: "Pause, dann prüfen. Immer in dieser Reihenfolge.", it: "Pausa, poi verifica. Sempre in quest'ordine.", da: "Pause, så bekræft. Altid i den rækkefølge.", bg: "Пауза, после проверка. Винаги в този ред." }
      ],
      next: "tools"
    },
    scenario_good_check: {
      bot: [
        { en: "✅ Beautiful instinct. The mayor's site, a local TV outlet, or a real journalist's account will confirm or debunk in minutes.", fr: "✅ Magnifique réflexe. Le site de la mairie, une chaîne locale, ou le compte d'un·e vrai·e journaliste confirmera ou démentira en quelques minutes.", es: "✅ Maravilloso instinto. La web del ayuntamiento, una cadena local, o la cuenta de un·a periodista real confirmará o desmentirá en minutos.", de: "✅ Wunderbarer Instinkt. Die Bürgermeister-Website, ein lokaler TV-Sender oder ein echter Journalisten-Account bestätigt oder entlarvt es in Minuten.", it: "✅ Istinto meraviglioso. Il sito del sindaco, una TV locale o l'account di un·a vero·a giornalista confermerà o smentirà in pochi minuti.", da: "✅ Vidunderligt instinkt. Borgmesterens hjemmeside, en lokal tv-kanal eller en rigtig journalists konto vil bekræfte eller afkræfte inden for minutter.", bg: "✅ Прекрасен инстинкт. Сайтът на кмета, локална телевизия или акаунт на истински журналист ще потвърди или опровергае за минути." },
        { en: "If you can't find it on any verified source — it isn't real. Quiet, satisfying clarity.", fr: "Si tu ne trouves l'info sur aucune source vérifiée — elle n'est pas réelle. Une clarté douce et satisfaisante.", es: "Si no lo encuentras en ninguna fuente verificada, no es real. Una claridad silenciosa y satisfactoria.", de: "Wenn du es in keiner verifizierten Quelle findest, ist es nicht echt. Stille, befriedigende Klarheit.", it: "Se non lo trovi su nessuna fonte verificata — non è reale. Una chiarezza silenziosa e soddisfacente.", da: "Hvis du ikke kan finde det på nogen verificeret kilde — er det ikke ægte. Stille, tilfredsstillende klarhed.", bg: "Ако не можеш да го намериш в нито един проверен източник — не е истинско. Тиха, удовлетворителна яснота." }
      ],
      next: "tools"
    },
    scenario_good_search: {
      bot: [
        { en: "✅ Yes! Reverse image search is one of Janet's favorite tools.", fr: "✅ Oui ! La recherche d'image inversée est l'un des outils préférés de Janet.", es: "✅ ¡Sí! La búsqueda inversa de imágenes es una de las herramientas favoritas de Janet.", de: "✅ Ja! Die umgekehrte Bildsuche ist eines von Janets Lieblingswerkzeugen.", it: "✅ Sì! La ricerca inversa di immagini è uno degli strumenti preferiti di Janet.", da: "✅ Ja! Omvendt billedsøgning er et af Janets favoritværktøjer.", bg: "✅ Да! Обратното търсене на изображения е един от любимите инструменти на Janet." },
        { en: "Drop the photo into Google Lens. If the same image also pops up in a different story from a different country, that, factually, is your answer.", fr: "Glisse la photo dans Google Lens. Si la même image apparaît aussi dans une autre histoire d'un autre pays, c'est, factuellement, ta réponse.", es: "Suelta la foto en Google Lens. Si la misma imagen aparece también en otra historia de otro país, esa es, factualmente, tu respuesta.", de: "Zieh das Foto in Google Lens. Wenn dasselbe Bild auch in einer anderen Geschichte aus einem anderen Land auftaucht, ist das, faktisch, deine Antwort.", it: "Trascina la foto in Google Lens. Se la stessa immagine compare anche in un'altra storia da un altro paese, quella è, fattualmente, la tua risposta.", da: "Læg billedet i Google Lens. Hvis samme billede også dukker op i en anden historie fra et andet land, er det, faktuelt, dit svar.", bg: "Пусни снимката в Google Lens. Ако същата снимка изниква и в съвсем друга история от друга държава — това, технически, е отговорът ти." }
      ],
      next: "tools"
    },
    tools: {
      bot: [
        { en: "Janet's recommended fact-check shelf:", fr: "L'étagère de fact-checking recommandée par Janet :", es: "La estantería de fact-checking recomendada por Janet:", de: "Janets empfohlenes Fact-Check-Regal:", it: "Lo scaffale di fact-checking consigliato da Janet:", da: "Janets anbefalede fact-check-hylde:", bg: "Препоръчаната от Janet полица за проверка на факти:" },
        { en: "🔍 *Snopes* — old and reliable, covers urban legends and viral claims.", fr: "🔍 *Snopes* — vieux et fiable, couvre les légendes urbaines et les contenus viraux.", es: "🔍 *Snopes* — antiguo y fiable, cubre leyendas urbanas y bulos virales.", de: "🔍 *Snopes* — alt und zuverlässig, deckt Urban Legends und virale Behauptungen ab.", it: "🔍 *Snopes* — vecchio e affidabile, copre leggende urbane e bufale virali.", da: "🔍 *Snopes* — gammel og pålidelig, dækker vandrehistorier og virale påstande.", bg: "🔍 *Snopes* — стар и надежден, покрива градски легенди и вирусни твърдения." },
        { en: "📰 *FactCheck.org* and *PolitiFact* — solid on political claims.", fr: "📰 *FactCheck.org* et *PolitiFact* — solides sur les affirmations politiques.", es: "📰 *FactCheck.org* y *PolitiFact* — sólidos en afirmaciones políticas.", de: "📰 *FactCheck.org* und *PolitiFact* — solide bei politischen Behauptungen.", it: "📰 *FactCheck.org* e *PolitiFact* — solidi sulle affermazioni politiche.", da: "📰 *FactCheck.org* og *PolitiFact* — solide på politiske påstande.", bg: "📰 *FactCheck.org* и *PolitiFact* — солидни за политически твърдения." },
        { en: "🌍 Local ones too: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DA), *Factcheck.bg* (BG).", fr: "🌍 Locaux aussi : *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", es: "🌍 También locales: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", de: "🌍 Auch lokal: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", it: "🌍 Anche locali: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", da: "🌍 Også lokale: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", bg: "🌍 И локални: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG)." },
        { en: "🛠️ *InVID WeVerify* — a free browser extension built for digging into images and videos. Janet adores it.", fr: "🛠️ *InVID WeVerify* — une extension de navigateur gratuite faite pour fouiller images et vidéos. Janet l'adore.", es: "🛠️ *InVID WeVerify* — una extensión de navegador gratuita pensada para examinar imágenes y vídeos. Janet la adora.", de: "🛠️ *InVID WeVerify* — eine kostenlose Browser-Erweiterung, gebaut, um Bilder und Videos zu durchleuchten. Janet liebt sie.", it: "🛠️ *InVID WeVerify* — un'estensione del browser gratuita per scavare in immagini e video. Janet la adora.", da: "🛠️ *InVID WeVerify* — en gratis browserudvidelse bygget til at grave i billeder og videoer. Janet elsker den.", bg: "🛠️ *InVID WeVerify* — безплатно разширение за браузър, направено да рови в снимки и видеа. Janet го обожава." }
      ],
      next: "outro"
    },
    outro: {
      bot: [
        { en: "Final Janet thought: skepticism is, factually, a form of kindness.", fr: "Dernière pensée de Janet : le scepticisme est, factuellement, une forme de gentillesse.", es: "Último pensamiento de Janet: el escepticismo es, factualmente, una forma de amabilidad.", de: "Letzter Janet-Gedanke: Skepsis ist, faktisch, eine Form von Freundlichkeit.", it: "Pensiero finale di Janet: lo scetticismo è, fattualmente, una forma di gentilezza.", da: "Sidste Janet-tanke: skepsis er, faktuelt, en form for venlighed.", bg: "Последна мисъл от Janet: скептицизмът е, технически, форма на доброта." },
        { en: "When you don't share something false, you spare someone's parent from a panic. And you save the truth a tiny bit of erosion.", fr: "Quand tu ne partages pas une info fausse, tu épargnes une crise de panique au parent de quelqu'un. Et tu épargnes à la vérité un petit grain d'érosion.", es: "Cuando no compartes algo falso, le ahorras un susto al padre o madre de alguien. Y le ahorras a la verdad un poquito de erosión.", de: "Wenn du etwas Falsches nicht teilst, ersparst du den Eltern von jemandem eine Panikattacke. Und du ersparst der Wahrheit ein winziges bisschen Erosion.", it: "Quando non condividi qualcosa di falso, risparmi una crisi al genitore di qualcuno. E risparmi alla verità un pizzico di erosione.", da: "Når du ikke deler noget falsk, sparer du nogens forælder for en panik. Og du sparer sandheden for en lille smule erosion.", bg: "Когато не споделиш нещо невярно, спестяваш паника на нечий родител. И спестяваш на истината мъничко ерозия." },
        { en: "Bye for now! 🥣", fr: "À très vite ! 🥣", es: "¡Hasta luego! 🥣", de: "Bis bald! 🥣", it: "A presto! 🥣", da: "Vi ses! 🥣", bg: "До скоро! 🥣" }
      ],
      end: true
    }
  }
};
