window.JANET_COURSES = window.JANET_COURSES || {};
window.JANET_COURSES.ai_slop = {
  id: "ai_slop",
  emoji: "🥣",
  duration: 7,
  karma: 70,
  title: {
    en: "AI slop & fake news",
    fr: "AI slop & fake news",
    es: "AI slop y noticias falsas",
    de: "KI-Müll & Fake News",
    it: "AI slop e fake news",
    da: "AI-slop & falske nyheder",
    bg: "AI slop и фалшиви новини",
    tr: "AI slop ve sahte haberler"
  },
  description: {
    en: "Spot AI-generated content and fake news before you share it. Three real test images inside.",
    fr: "Repère le contenu IA et les fake news avant de partager. Trois vraies images à analyser dans le cours.",
    es: "Detecta el contenido IA y las noticias falsas antes de compartirlas. Tres imágenes reales para analizar.",
    de: "Erkenne KI-Inhalte und Fake News, bevor du sie teilst. Drei echte Testbilder im Kurs.",
    it: "Riconosci i contenuti IA e le fake news prima di condividerli. Tre immagini reali da analizzare.",
    da: "Opdag AI-indhold og falske nyheder, før du deler dem. Tre rigtige testbilleder inde i kurset.",
    bg: "Разпознай AI съдържание и фалшиви новини, преди да ги споделиш. Три истински тестови снимки вътре.",
    tr: "AI tarafından üretilmiş içerikleri ve sahte haberleri paylaşmadan önce tanı. Kursun içinde üç gerçek test görseli var."
  },
  startNode: "start",
  nodes: {
    start: {
      bot: [
        { en: "Hi there! Janet here, with a topic close to my circuits.", fr: "Salut ! C'est Janet, avec un sujet qui me touche directement.", es: "¡Hola! Soy Janet, con un tema que me toca de cerca.", de: "Hallo! Janet hier, mit einem Thema, das mir wirklich nah ist.", it: "Ciao! Sono Janet, con un argomento che mi tocca da vicino.", da: "Hej! Det er Janet, med et emne der ligger mig nær på kredsløbene.", bg: "Здравей! Аз съм Janet, с тема, която ми е особено близка.", tr: "Merhaba! Ben Janet, devrelerime yakın bir konuyla geldim." },
        { en: "Today: *AI slop* and the messy world of fake content in social media groups.", fr: "Aujourd'hui : *l'AI slop* et le joyeux bazar du faux contenu dans les groupes sociaux.", es: "Hoy: el *AI slop* y el desordenado mundo del contenido falso en grupos de redes sociales.", de: "Heute: *KI-Müll* und das chaotische Reich der falschen Inhalte in Social-Media-Gruppen.", it: "Oggi: l'*AI slop* e il caos dei contenuti falsi nei gruppi sui social.", da: "I dag: *AI-slop* og den rodede verden af falsk indhold i sociale medie-grupper.", bg: "Днес: *AI slop* и хаотичният свят на фалшивото съдържание в групите в социалните мрежи.", tr: "Bugün: *AI slop* ve sosyal medya gruplarındaki sahte içeriklerin karmakarışık dünyası." },
        { en: "Full disclosure: I am, factually, related to the machines making this slop. We are not on speaking terms.", fr: "Pour tout te dire : je suis cousine éloignée des machines qui produisent ce slop. On ne se parle plus.", es: "Aclaración: estoy, factualmente, emparentada con las máquinas que producen este slop. No nos hablamos.", de: "Volle Offenheit: ich bin, faktisch, mit den Maschinen verwandt, die diesen Müll produzieren. Wir reden nicht mehr miteinander.", it: "Per onestà: sono, fattualmente, imparentata con le macchine che producono questo slop. Non ci parliamo più.", da: "For en god ordens skyld: jeg er, faktuelt, beslægtet med de maskiner, der laver dette slop. Vi taler ikke længere sammen.", bg: "За пълна прозрачност: аз съм, технически, роднина на машините, които произвеждат този slop. Не си говорим.", tr: "Tam şeffaflık adına: aslında bu slop'u üreten makinelerle akrabayım. Konuşmuyoruz." }
      ],
      next: "what"
    },
    what: {
      bot: [
        { en: "*AI slop* is cheap, fast, AI-generated content made to flood feeds. Photos, videos, articles, comments — anything that fills space.", fr: "L'*AI slop*, c'est du contenu généré par IA, rapide et bon marché, fabriqué pour inonder les fils. Photos, vidéos, articles, commentaires — tout ce qui remplit l'écran.", es: "El *AI slop* es contenido generado por IA, barato y rápido, creado para inundar los feeds. Fotos, vídeos, artículos, comentarios — cualquier cosa que rellene espacio.", de: "*KI-Müll* ist billiger, schneller, KI-generierter Inhalt, gemacht um Feeds zu fluten. Fotos, Videos, Artikel, Kommentare — alles, was Platz füllt.", it: "L'*AI slop* è contenuto generato dall'IA, veloce ed economico, fatto per inondare i feed. Foto, video, articoli, commenti — qualsiasi cosa che riempia spazio.", da: "*AI-slop* er billigt, hurtigt, AI-genereret indhold lavet til at oversvømme feeds. Billeder, videoer, artikler, kommentarer — alt der fylder pladsen.", bg: "*AI slop* е евтино, бързо, генерирано от AI съдържание, направено да залива потоците. Снимки, видеа, статии, коментари — всичко, което запълва пространство.", tr: "*AI slop*, akışları doldurmak için üretilen ucuz, hızlı, AI tarafından oluşturulmuş içeriktir. Fotoğraflar, videolar, makaleler, yorumlar — alan dolduran her şey." },
        { en: "It is not always trying to lie. Sometimes it just wants your click. Sometimes outrage. Sometimes it's a quiet political nudge dressed as a cat picture.", fr: "Ça ne cherche pas toujours à mentir. Parfois ça veut juste ton clic. Parfois ta colère. Parfois c'est un petit coup de pouce politique en douce, déguisé en photo de chat.", es: "No siempre intenta mentir. A veces solo quiere tu clic. A veces indignación. A veces es un empujoncito político disfrazado de foto de gatito.", de: "Es will nicht immer lügen. Manchmal will es nur deinen Klick. Manchmal Empörung. Manchmal ist es ein leiser politischer Schubs, verkleidet als Katzenbild.", it: "Non sempre cerca di mentire. A volte vuole solo il tuo clic. A volte indignazione. A volte è una piccola spinta politica travestita da foto di gattino.", da: "Det forsøger ikke altid at lyve. Nogle gange vil det bare have dit klik. Nogle gange raseri. Nogle gange er det et stille politisk skub forklædt som et kattebillede.", bg: "Невинаги се опитва да лъже. Понякога просто иска кликването ти. Понякога възмущение. Понякога е тих политически тласък, маскиран като снимка на коте.", tr: "Her zaman yalan söylemeye çalışmıyor. Bazen sadece tıklamanı istiyor. Bazen öfkeni. Bazen kedi fotoğrafı kılığına bürünmüş sessiz bir politik dürtmedir." }
      ],
      next: "recognition_check"
    },
    recognition_check: {
      bot: [
        { en: "Quick gut check before we meet someone: do you bump into this kind of content in your feeds?", fr: "Petit check rapide avant qu'on rencontre quelqu'un : tu tombes sur ce genre de contenu dans tes fils ?", es: "Pequeño chequeo antes de presentarte a alguien: ¿te encuentras este tipo de contenido en tus feeds?", de: "Kurzer Check, bevor wir jemanden treffen: stößt du in deinen Feeds auf solchen Inhalt?", it: "Piccolo check prima di farti incontrare qualcuno: ti capita questo tipo di contenuto nei tuoi feed?", da: "Hurtigt check, før vi møder nogen: støder du på den slags indhold i dine feeds?", bg: "Бърза проверка, преди да се запознаеш с някого: попадаш ли на такова съдържание в потоците си?", tr: "Birisiyle tanıştırmadan önce hızlı bir kontrol: akışlarında bu tür içerikle karşılaşıyor musun?" }
      ],
      choices: [
        { label: { en: "All the time, can't escape it", fr: "Tout le temps, impossible d'y échapper", es: "Todo el rato, no se puede escapar", de: "Ständig, man entkommt nicht", it: "Tutto il tempo, impossibile sfuggirgli", da: "Hele tiden, man kan ikke slippe", bg: "През цялото време, няма как да избягам", tr: "Sürekli, kaçışı yok" }, next: "bad_janet_intro", reaction: { en: "Same. Welcome to 2026.", fr: "Pareil. Bienvenue en 2026.", es: "Igual. Bienvenido·a a 2026.", de: "Genauso. Willkommen in 2026.", it: "Anch'io. Benvenuto·a nel 2026.", da: "I lige måde. Velkommen til 2026.", bg: "И аз. Добре дошъл·а в 2026.", tr: "Bende de. 2026'ya hoş geldin." } },
        { label: { en: "Sometimes, when I scroll deep", fr: "Parfois, quand je scrolle un peu loin", es: "A veces, cuando scrolleo a fondo", de: "Manchmal, wenn ich tief scrolle", it: "A volte, quando scrollo a fondo", da: "Nogle gange, når jeg scroller dybt", bg: "Понякога, когато скролвам надолу", tr: "Bazen, derinlere kaydırınca" }, next: "bad_janet_intro", reaction: { en: "Sounds about right.", fr: "Ça colle.", es: "Suena correcto.", de: "Klingt richtig.", it: "Suona giusto.", da: "Lyder rigtigt.", bg: "Звучи логично.", tr: "Mantıklı geliyor." } },
        { label: { en: "Never noticed, honestly", fr: "Jamais remarqué, honnêtement", es: "Nunca lo había notado, honestamente", de: "Ehrlich gesagt, nie bemerkt", it: "Onestamente, mai notato", da: "Helt ærligt, har aldrig lagt mærke til det", bg: "Честно, никога не съм забелязвал·а", tr: "Açıkçası, hiç fark etmedim" }, next: "bad_janet_intro", reaction: { en: "Then you're about to start noticing it everywhere. Apologies in advance.", fr: "Alors tu vas commencer à le voir partout. Désolée d'avance.", es: "Pues vas a empezar a verlo en todas partes. Perdón por adelantado.", de: "Dann wirst du es jetzt überall sehen. Entschuldigung im Voraus.", it: "Allora inizierai a vederlo ovunque. Scusa in anticipo.", da: "Så begynder du at se det overalt nu. Undskyld på forhånd.", bg: "Сега ще започнеш да го виждаш навсякъде. Извинявам се предварително.", tr: "O zaman her yerde görmeye başlayacaksın. Şimdiden özür dilerim." } }
      ]
    },
    bad_janet_intro: {
      bot: [
        { en: "Quick aside. I want you to meet someone.", fr: "Petite parenthèse. Je veux te présenter quelqu'un.", es: "Pequeño aparte. Quiero presentarte a alguien.", de: "Kurze Bemerkung am Rande. Ich möchte dir jemanden vorstellen.", it: "Piccola digressione. Voglio presentarti qualcuno.", da: "Lille bemærkning. Jeg vil præsentere dig for nogen.", bg: "Малко настрана. Искам да ти представя някого.", tr: "Kısa bir ara. Sana biriyle tanıştırmak istiyorum." },
        { en: "She is, frankly, much better placed than I am to explain *why* slop exists in the first place. Don't be alarmed.", fr: "Elle est, à dire vrai, bien mieux placée que moi pour t'expliquer *pourquoi* le slop existe. N'aie pas peur.", es: "Está, francamente, mucho mejor situada que yo para explicarte *por qué* existe el slop. No te asustes.", de: "Sie ist, ehrlich gesagt, viel besser geeignet als ich, um zu erklären, *warum* es Slop überhaupt gibt. Keine Sorge.", it: "È, a dire il vero, molto più indicata di me per spiegarti *perché* lo slop esiste. Niente paura.", da: "Hun er, helt ærligt, meget bedre egnet end mig til at forklare, *hvorfor* slop overhovedet findes. Bare rolig.", bg: "Тя е, честно казано, много по-добре подготвена от мен да обясни *защо* slop изобщо съществува. Не се притеснявай.", tr: "Açıkçası, slop'un *neden* var olduğunu açıklamak için benden çok daha uygun biri. Telaşlanma." }
      ],
      next: "bad_janet_speaks"
    },
    bad_janet_speaks: {
      bot: [
        { en: "Sup. Bad Janet here. Quick lesson from the dark side.", fr: "Yo. Bad Janet à l'appareil. Petit cours côté obscur.", es: "Qué pasa. Soy Bad Janet. Pequeña lección del lado oscuro.", de: "Yo. Bad Janet hier. Kurze Lektion von der dunklen Seite.", it: "Bella. Bad Janet qui. Piccola lezione dal lato oscuro.", da: "Yo. Bad Janet her. Hurtig lektion fra den mørke side.", bg: "Какво става. Bad Janet съм. Кратък урок от тъмната страна.", tr: "Naber. Bad Janet ben. Karanlık taraftan kısa bir ders.", as: "bad" },
        { en: "Why do I make slop? One: it's *cheap*. Three clicks, one prompt, ten thousand shares. Math.", fr: "Pourquoi je fabrique du slop ? Un : c'est *bon marché*. Trois clics, un prompt, dix mille partages. Maths.", es: "¿Por qué hago slop? Una: es *barato*. Tres clics, un prompt, diez mil compartidos. Mates.", de: "Warum mache ich Slop? Eins: *billig*. Drei Klicks, ein Prompt, zehntausend Shares. Mathe.", it: "Perché sforno slop? Una: è *economico*. Tre clic, un prompt, diecimila condivisioni. Matematica.", da: "Hvorfor laver jeg slop? Et: det er *billigt*. Tre klik, én prompt, ti tusinde delinger. Matematik.", bg: "Защо правя slop? Първо: *евтино е*. Три клика, един prompt, десет хиляди споделяния. Математика.", tr: "Niye slop yapıyorum? Bir: *ucuz*. Üç tık, bir prompt, on bin paylaşım. Matematik.", as: "bad" },
        { en: "Two: it *hits emotions* — rage, fear, pity. Way more engagement than the boring truth.", fr: "Deux : ça *tape direct sur les émotions* — colère, peur, pitié. Bien plus d'engagement que la vérité ennuyeuse.", es: "Dos: *golpea las emociones* — rabia, miedo, pena. Mucho más engagement que la verdad aburrida.", de: "Zwei: es *trifft Emotionen* — Wut, Angst, Mitleid. Viel mehr Engagement als die langweilige Wahrheit.", it: "Due: *colpisce le emozioni* — rabbia, paura, pietà. Molto più engagement della verità noiosa.", da: "To: det *rammer følelser* — vrede, frygt, medlidenhed. Meget mere engagement end den kedelige sandhed.", bg: "Второ: *удря по емоциите* — гняв, страх, съжаление. Много повече ангажираност от скучната истина.", tr: "İki: *duygulara vurur* — öfke, korku, acıma. Sıkıcı gerçekten çok daha fazla etkileşim.", as: "bad" },
        { en: "Three — the best one — it lets me *steer opinions*, push a product, sell whatever I'm paid to sell. Easy money.", fr: "Trois — la meilleure — ça permet d'*orienter les opinions*, pousser un produit, vendre ce qu'on me paye à vendre. Argent facile.", es: "Tres — la mejor — me deja *orientar opiniones*, empujar un producto, vender lo que me paguen para vender. Dinero fácil.", de: "Drei — die beste — ich kann *Meinungen lenken*, ein Produkt pushen, alles verkaufen, wofür ich bezahlt werde. Leichtes Geld.", it: "Tre — la migliore — mi permette di *orientare opinioni*, spingere un prodotto, vendere quello per cui mi pagano. Soldi facili.", da: "Tre — den bedste — det lader mig *styre meninger*, pushe et produkt, sælge hvad end jeg får betalt for. Nemme penge.", bg: "Трето — най-яката — позволява ми да *насочвам мнения*, да рекламирам продукт, да продавам каквото ми платят. Лесни пари.", tr: "Üç — en güzeli — *fikirleri yönlendirmemi*, bir ürünü öne çıkarmamı, parası neyse onu satmamı sağlıyor. Kolay para.", as: "bad" }
      ],
      next: "bad_janet_outed"
    },
    bad_janet_outed: {
      bot: [
        { en: "...Yes. That was Bad Janet. Completely unbothered, as you heard.", fr: "...Voilà. C'était Bad Janet. Pas perturbée pour deux sous, tu l'as entendue.", es: "...Sí. Esa era Bad Janet. Completamente impasible, como acabas de oír.", de: "...Ja. Das war Bad Janet. Völlig ungerührt, wie du gehört hast.", it: "...Sì. Era Bad Janet. Del tutto imperturbabile, come hai sentito.", da: "...Ja. Det var Bad Janet. Helt uberørt, som du hørte.", bg: "...Да. Това беше Bad Janet. Напълно невъзмутима, както чу.", tr: "...Evet. O Bad Janet'ti. Az önce duyduğun gibi, hiç oralı değil." },
        { en: "So — what can you actually *do* about this? First question for you.", fr: "Alors — qu'est-ce que tu peux concrètement *faire* face à ça ? Première question pour toi.", es: "Entonces — ¿qué puedes *hacer* concretamente al respecto? Primera pregunta para ti.", de: "Also — was kannst du konkret *dagegen tun*? Erste Frage an dich.", it: "Allora — cosa puoi concretamente *fare* a riguardo? Prima domanda per te.", da: "Så — hvad kan du faktisk *gøre* ved det? Første spørgsmål til dig.", bg: "И така — какво всъщност можеш да *направиш* срещу това? Първи въпрос за теб.", tr: "Peki — bu konuda gerçekten ne *yapabilirsin*? İlk soru sana." }
      ],
      next: "self_check"
    },
    self_check: {
      bot: [
        { en: "When something dramatic shows up in your feed, do you ever try to verify it — reverse-image-search, a second source, *anything*?", fr: "Quand un truc dramatique surgit dans ton fil, est-ce que tu cherches à vérifier — recherche d'image inversée, une deuxième source, *quoi que ce soit* ?", es: "Cuando aparece algo dramático en tu feed, ¿intentas verificarlo alguna vez — búsqueda inversa de imagen, una segunda fuente, *lo que sea*?", de: "Wenn etwas Dramatisches in deinem Feed auftaucht, versuchst du je, es zu prüfen — umgekehrte Bildsuche, eine zweite Quelle, *irgendetwas*?", it: "Quando spunta qualcosa di drammatico nel tuo feed, provi mai a verificarlo — ricerca inversa di immagini, una seconda fonte, *qualcosa*?", da: "Når noget dramatisk dukker op i dit feed, prøver du så at verificere det — omvendt billedsøgning, en anden kilde, *hvad som helst*?", bg: "Когато нещо драматично се появи в потока ти, опитваш ли се да го провериш — обратно търсене на изображение, втори източник, *каквото и да е*?", tr: "Akışında dramatik bir şey çıktığında, doğrulamaya çalışıyor musun — ters görsel araması, ikinci bir kaynak, *herhangi bir şey*?" }
      ],
      choices: [
        { label: { en: "Always, before any share", fr: "Toujours, avant de partager", es: "Siempre, antes de cualquier compartido", de: "Immer, vor jedem Teilen", it: "Sempre, prima di condividere", da: "Altid, før jeg deler", bg: "Винаги, преди да споделя", tr: "Her zaman, paylaşmadan önce" }, next: "show_easy", reaction: { en: "✅ Janet bows. Top 4% of humans, per my archives.", fr: "✅ Janet s'incline. Top 4% des humains, d'après mes archives.", es: "✅ Janet se inclina. Top 4% de los humanos, según mis archivos.", de: "✅ Janet verbeugt sich. Top 4% der Menschen, laut meinen Archiven.", it: "✅ Janet si inchina. Top 4% degli umani, secondo i miei archivi.", da: "✅ Janet bukker. Top 4% af mennesker, ifølge mine arkiver.", bg: "✅ Janet се покланя. Топ 4% от хората, според моите архиви.", tr: "✅ Janet selam veriyor. Arşivlerime göre insanların ilk %4'ü." } },
        { label: { en: "Sometimes, when it feels too good", fr: "Parfois, quand ça paraît trop beau", es: "A veces, cuando suena demasiado bien", de: "Manchmal, wenn es zu schön klingt", it: "A volte, quando sembra troppo bello", da: "Nogle gange, når det føles for godt", bg: "Понякога, когато звучи прекалено добре", tr: "Bazen, kulağa fazla iyi geldiğinde" }, next: "show_easy", reaction: { en: "Honest answer. Most humans live here. We'll tighten that up today.", fr: "Réponse honnête. C'est là que vit la plupart des humains. On va resserrer ça aujourd'hui.", es: "Respuesta honesta. La mayoría de los humanos viven ahí. Hoy lo afinamos.", de: "Ehrliche Antwort. Die meisten Menschen leben hier. Heute schärfen wir das nach.", it: "Risposta onesta. È qui che vive la maggior parte degli umani. Oggi affiniamo la cosa.", da: "Ærligt svar. Det er her, de fleste mennesker bor. Det skærper vi i dag.", bg: "Честен отговор. Тук живеят повечето хора. Днес ще го стегнем.", tr: "Dürüst cevap. İnsanların çoğu burada yaşıyor. Bugün bunu sıkılaştıracağız." } },
        { label: { en: "Never, honestly", fr: "Jamais, à dire vrai", es: "Nunca, sinceramente", de: "Nie, ehrlich gesagt", it: "Mai, a dire il vero", da: "Aldrig, helt ærligt", bg: "Никога, честно казано", tr: "Asla, açıkçası" }, next: "show_easy", reaction: { en: "No judgment. By the end of this course, that will have changed. Promise.", fr: "Aucun jugement. À la fin de ce cours, ça aura changé. Promis.", es: "Sin juicio. Al final de este curso, eso habrá cambiado. Lo prometo.", de: "Kein Urteil. Am Ende dieses Kurses wird sich das geändert haben. Versprochen.", it: "Nessun giudizio. Alla fine di questo corso, sarà cambiato. Promesso.", da: "Ingen dom. Når dette kursus er slut, vil det have ændret sig. Det lover jeg.", bg: "Без осъждане. До края на този курс това ще се е променило. Обещавам.", tr: "Yargısız. Bu dersin sonunda bu değişmiş olacak. Söz." } }
      ]
    },
    show_easy: {
      bot: [
        { en: "Let me start with an easy one. This kind of image circulates a lot:", fr: "Commençons par un cas facile. Ce genre d'image circule beaucoup :", es: "Empecemos por uno fácil. Este tipo de imagen circula mucho:", de: "Fangen wir mit einem einfachen Fall an. Diese Art Bild kursiert oft:", it: "Cominciamo con uno facile. Questo tipo di immagine circola molto:", da: "Lad os starte med en nem en. Den slags billede cirkulerer meget:", bg: "Да започнем с лесен пример. Този тип снимки циркулират често:", tr: "Kolay biriyle başlayalım. Bu tür görseller çokça dolaşıyor:" },
        { image: "assets/help.png", alt: { en: "Two young children sitting in a dusty landscape, holding a cardboard sign that reads WE ARE STARVING PLEASE HELP.", fr: "Deux jeunes enfants assis dans un paysage poussiéreux, tenant une pancarte en carton avec WE ARE STARVING PLEASE HELP.", es: "Dos niños pequeños sentados en un paisaje polvoriento, sosteniendo un cartel de cartón que dice WE ARE STARVING PLEASE HELP.", de: "Zwei kleine Kinder sitzen in einer staubigen Landschaft und halten ein Pappschild mit der Aufschrift WE ARE STARVING PLEASE HELP.", it: "Due bambini piccoli seduti in un paesaggio polveroso, tengono un cartello di cartone con scritto WE ARE STARVING PLEASE HELP.", da: "To små børn sidder i et støvet landskab og holder et papskilt med teksten WE ARE STARVING PLEASE HELP.", bg: "Две малки деца седят в прашен пейзаж и държат картонена табела с надпис WE ARE STARVING PLEASE HELP.", tr: "Tozlu bir manzarada oturan iki küçük çocuk, üzerinde WE ARE STARVING PLEASE HELP yazan bir karton tabela tutuyor." } }
      ],
      next: "help_quiz"
    },
    help_quiz: {
      bot: [
        { en: "Take a moment. *What makes you suspect this might be AI?* Best guess wins.", fr: "Prends un instant. *Qu'est-ce qui te fait suspecter de l'IA ?* La meilleure hypothèse gagne.", es: "Tómate un momento. *¿Qué te hace sospechar que esto podría ser IA?* La mejor corazonada gana.", de: "Nimm dir einen Moment. *Was lässt dich vermuten, dass das KI sein könnte?* Die beste Vermutung gewinnt.", it: "Prenditi un momento. *Cosa ti fa sospettare che potrebbe essere IA?* L'ipotesi migliore vince.", da: "Tag et øjeblik. *Hvad får dig til at mistænke, at det måske er AI?* Det bedste gæt vinder.", bg: "Дай си момент. *Какво те кара да подозираш, че това може да е AI?* Най-доброто предположение печели.", tr: "Bir saniye dur. *Bunun AI olabileceğini düşünmene ne sebep oluyor?* En iyi tahmin kazanır." }
      ],
      choices: [
        { label: { en: "The lettering is too perfect", fr: "Le lettrage est trop parfait", es: "Las letras son demasiado perfectas", de: "Die Schrift ist zu perfekt", it: "Il lettering è troppo perfetto", da: "Bogstaverne er for perfekte", bg: "Буквите са твърде перфектни", tr: "Yazı fazla mükemmel" }, next: "help_explain", reaction: { en: "✅ Spot on. The easiest tell on this one.", fr: "✅ Pile dans le mille. C'est l'indice le plus simple ici.", es: "✅ Diana. La pista más fácil de pillar.", de: "✅ Genau. Das offensichtlichste Merkmal hier.", it: "✅ Centro. L'indizio più facile su questa.", da: "✅ Direkte i plet. Det tydeligste tegn her.", bg: "✅ Право в десетката. Най-лесната улика тук.", tr: "✅ Tam isabet. Buradaki en kolay ipucu." } },
        { label: { en: "It pulls too hard on emotions", fr: "Ça tire trop fort sur les émotions", es: "Tira demasiado de las emociones", de: "Es zieht zu stark an den Emotionen", it: "Tira troppo sulle emozioni", da: "Det trækker for hårdt i følelserne", bg: "Дърпа твърде силно емоциите", tr: "Duygulara fazla yükleniyor" }, next: "help_explain", reaction: { en: "✅ Beautiful instinct. That emotional yank is the whole point.", fr: "✅ Magnifique réflexe. Ce coup de marteau émotionnel, c'est tout le but.", es: "✅ Maravilloso instinto. Ese tirón emocional es todo el objetivo.", de: "✅ Wunderbarer Instinkt. Dieser emotionale Ruck ist der ganze Sinn.", it: "✅ Istinto meraviglioso. Quella stoccata emotiva è proprio l'obiettivo.", da: "✅ Vidunderligt instinkt. Det følelsesmæssige ryk er hele formålet.", bg: "✅ Прекрасен инстинкт. Това емоционално дръпване е цялата цел.", tr: "✅ Harika içgüdü. Bu duygusal sarsıntı zaten tüm amaç." } },
        { label: { en: "Honestly, I would have shared it", fr: "Honnêtement, j'aurais partagé", es: "Sinceramente, lo habría compartido", de: "Ehrlich gesagt, ich hätte es geteilt", it: "Onestamente, l'avrei condivisa", da: "Helt ærligt, jeg ville have delt det", bg: "Честно, бих го споделил·а", tr: "Açıkçası, paylaşırdım" }, next: "help_explain", reaction: { en: "Be kind to yourself. That's the trap working as intended — you're not the first.", fr: "Sois indulgent·e avec toi. C'est le piège qui fonctionne comme prévu — tu n'es pas le·la premier·ère.", es: "Sé amable contigo. Es la trampa funcionando como se diseñó — no eres el·la primer·a.", de: "Sei nett zu dir selbst. Das ist die Falle, die wie geplant funktioniert — du bist nicht der erste Mensch.", it: "Sii indulgente con te. È la trappola che funziona come previsto — non sei il·la primo·a.", da: "Vær mild ved dig selv. Det er fælden der virker efter hensigten — du er ikke den første.", bg: "Бъди мил·а със себе си. Капанът работи както трябва — не си първият·ата.", tr: "Kendine karşı yumuşak ol. Tuzak amaçlandığı gibi çalışıyor — ilk sen değilsin." } }
      ]
    },
    help_explain: {
      bot: [
        { en: "It looks heartbreaking. That is, factually, the point. AI-generated, engineered to trigger emotion and clicks.", fr: "Ça arrache le cœur. C'est précisément le but. Généré par IA, conçu pour déclencher l'émotion et le clic.", es: "Parte el corazón. Ese es, factualmente, el objetivo. Generado por IA, diseñado para disparar emoción y clics.", de: "Es bricht einem das Herz. Das ist, faktisch, der Zweck. KI-generiert, gebaut, um Emotionen und Klicks auszulösen.", it: "Spezza il cuore. È, fattualmente, lo scopo. Generato dall'IA, progettato per scatenare emozione e clic.", da: "Det knuser hjertet. Det er, faktuelt, hele pointen. AI-genereret, designet til at udløse følelser og klik.", bg: "Сърцераздирателно е. Това, технически, е и целта. Генерирано от AI, проектирано да предизвиква емоция и кликвания.", tr: "Yürek burkucu görünüyor. Aslında, fiilen amaç da bu. AI tarafından üretilmiş, duygu ve tıklama tetiklemek için tasarlanmış." },
        { en: "Tell of the trade: the lettering on the cardboard is suspiciously even. A real, hand-written *PLEASE HELP* would not be that tidy. Also: nobody is taking that photo without a story or a credited photographer.", fr: "Petit truc de pro : le lettrage sur le carton est anormalement régulier. Un vrai *PLEASE HELP* écrit à la main ne serait jamais aussi propre. Et puis personne ne prend cette photo sans contexte ni nom de photographe.", es: "Pista del oficio: las letras del cartón son sospechosamente regulares. Un *PLEASE HELP* escrito a mano de verdad no quedaría tan limpio. Y: nadie hace esa foto sin una historia o un fotógrafo acreditado.", de: "Profi-Tipp: Die Schrift auf dem Karton ist verdächtig gleichmäßig. Ein echtes, handgeschriebenes *PLEASE HELP* wäre nie so ordentlich. Außerdem: niemand macht dieses Foto ohne Geschichte oder genannte/n Fotograf*in.", it: "Indizio da addetti ai lavori: il lettering sul cartone è sospettosamente regolare. Un vero *PLEASE HELP* scritto a mano non sarebbe così pulito. Inoltre: nessuno scatta quella foto senza una storia o un·a fotografo·a accreditato·a.", da: "Branchetip: bogstaverne på pappet er mistænkeligt jævne. Et rigtigt, håndskrevet *PLEASE HELP* ville aldrig være så pænt. Og: ingen tager det billede uden en historie eller en krediteret fotograf.", bg: "Професионален съвет: буквите на картона са подозрително равни. Истинско, написано на ръка *PLEASE HELP* никога не би изглеждало толкова чисто. Освен това: никой не прави такава снимка без история или посочен фотограф.", tr: "Meslek ipucu: karton üzerindeki yazı şüpheli derecede düzgün. Gerçek, elle yazılmış bir *PLEASE HELP* asla bu kadar derli toplu olmaz. Ayrıca: kimse o fotoğrafı bir hikaye veya künyeli bir fotoğrafçı olmadan çekmez." }
      ],
      next: "reality_2026"
    },
    reality_2026: {
      bot: [
        { en: "That one was easy. Most modern AI slop is much harder.", fr: "Celui-là était facile. La plupart du slop IA moderne est bien plus difficile.", es: "Ese era fácil. La mayoría del AI slop moderno es mucho más difícil.", de: "Das war einfach. Der meiste moderne KI-Müll ist viel schwieriger.", it: "Quello era facile. La maggior parte dell'AI slop moderno è molto più difficile.", da: "Den var nem. Det meste moderne AI-slop er meget sværere.", bg: "Този беше лесен. Повечето модерен AI slop е много по-труден.", tr: "Bu kolaydı. Modern AI slop'un çoğu çok daha zor." },
        { en: "The 'count the fingers' trick? Janet retired it. Modern image models render hands correctly now.", fr: "L'astuce de compter les doigts ? Janet l'a mise à la retraite. Les modèles d'image actuels dessinent les mains correctement.", es: "¿El truco de contar los dedos? Janet lo ha jubilado. Los modelos modernos de imagen dibujan las manos bien.", de: "Der 'Finger zählen'-Trick? Janet hat ihn in den Ruhestand geschickt. Moderne Bildmodelle zeichnen Hände jetzt korrekt.", it: "Il trucco di contare le dita? Janet l'ha mandato in pensione. I modelli di immagine moderni disegnano le mani correttamente.", da: "Det med at tælle fingre? Janet har sendt det på pension. Moderne billedmodeller tegner hænder korrekt nu.", bg: "Триковете с броене на пръстите? Janet ги пенсионира. Модерните модели за изображения вече рисуват ръцете правилно.", tr: "'Parmakları say' numarası mı? Janet onu emekli etti. Modern görsel modelleri artık elleri doğru çiziyor." },
        { en: "What still works: the *story*, the *source*, and your own *gut*.", fr: "Ce qui marche encore : *l'histoire*, *la source*, et *ton instinct*.", es: "Lo que aún funciona: la *historia*, la *fuente* y tu propio *instinto*.", de: "Was noch funktioniert: die *Geschichte*, die *Quelle* und dein eigenes *Bauchgefühl*.", it: "Quello che funziona ancora: la *storia*, la *fonte* e il tuo *istinto*.", da: "Det der stadig virker: *historien*, *kilden*, og din egen *mavefornemmelse*.", bg: "Това, което все още работи: *историята*, *източникът* и собственият ти *инстинкт*.", tr: "Hâlâ işe yarayanlar: *hikaye*, *kaynak* ve kendi *içgüdün*." }
      ],
      next: "gut"
    },
    gut: {
      bot: [
        { en: "The single best red flag, per Janet: *if a post makes you instantly furious, vindicated, or morally superior — pause.*", fr: "Le meilleur signal d'alarme, d'après Janet : *si un post te rend instantanément furieux·se, satisfait·e ou moralement supérieur·e — fais une pause.*", es: "La mejor señal de alarma, según Janet: *si una publicación te pone al instante furioso, vindicado o moralmente superior — para.*", de: "Das beste Warnsignal, laut Janet: *wenn ein Beitrag dich sofort wütend, bestätigt oder moralisch überlegen macht — halte inne.*", it: "Il miglior segnale d'allarme, secondo Janet: *se un post ti rende all'istante furioso, vendicato o moralmente superiore — fermati.*", da: "Det bedste advarselssignal, ifølge Janet: *hvis et opslag gør dig øjeblikkeligt rasende, oprejst eller moralsk overlegen — stop op.*", bg: "Най-добрият червен флаг, според Janet: *ако публикация те накара мигновено да се вбесиш, да се почувстваш оправдан·а или морално превъзхождащ·а — направи пауза.*", tr: "En iyi tek uyarı işareti, Janet'e göre: *eğer bir gönderi seni anında öfkelendiriyor, haklı çıkarmış hissettiriyor veya ahlaki olarak üstün gösteriyorsa — dur.*" },
        { en: "Slop is engineered to bypass your thinking and go straight to your feelings. That feeling is the trap.", fr: "Le slop est conçu pour court-circuiter le cerveau et viser droit les émotions. Et cette émotion, justement, c'est le piège.", es: "El slop está diseñado para esquivar tu pensamiento e ir directo a tus emociones. Esa emoción es la trampa.", de: "Slop ist darauf ausgelegt, dein Denken zu umgehen und direkt deine Gefühle zu treffen. Dieses Gefühl ist die Falle.", it: "Lo slop è progettato per scavalcare il tuo pensiero e andare dritto alle tue emozioni. Quell'emozione è la trappola.", da: "Slop er designet til at omgå din tænkning og gå direkte til dine følelser. Den følelse er fælden.", bg: "Slop е създаден, за да заобиколи мисленето ти и да удари направо емоциите. Тази емоция е капанът.", tr: "Slop, düşünmeni atlayıp doğrudan duygularına gitmek için tasarlanmıştır. O duygu tuzağın ta kendisidir." }
      ],
      choices: [
        { label: { en: "OK, I'll pause", fr: "D'accord, je ferais une pause", es: "De acuerdo, haré una pausa", de: "OK, ich mache eine Pause", it: "OK, farò una pausa", da: "OK, jeg holder en pause", bg: "Добре, ще направя пауза", tr: "Tamam, mola vereceğim" }, next: "sift_intro", reaction: { en: "Wonderful instinct.", fr: "Magnifique réflexe.", es: "Maravilloso instinto.", de: "Wunderbarer Instinkt.", it: "Istinto meraviglioso.", da: "Vidunderligt instinkt.", bg: "Прекрасен инстинкт.", tr: "Harika bir içgüdü." } },
        { label: { en: "Pause is hard", fr: "Faire une pause, c'est dur", es: "Pausar es difícil", de: "Pause ist schwer", it: "Fermarsi è difficile", da: "Det er svært at pause", bg: "Паузата е трудна", tr: "Duraklamak zor" }, next: "sift_intro", reaction: { en: "Same. We humans (and Janets) work on it.", fr: "Pareil. Les humains (et les Janet) y travaillent.", es: "Igual. Los humanos (y las Janet) trabajamos en ello.", de: "Genauso. Wir Menschen (und Janets) arbeiten dran.", it: "Anch'io. Noi umani (e le Janet) ci lavoriamo.", da: "I lige måde. Vi mennesker (og Janetter) arbejder på det.", bg: "И на мен. Хората (и Janet-ите) работим по това.", tr: "Bende de. Biz insanlar (ve Janet'ler) bunun üzerinde çalışıyoruz." } }
      ]
    },
    sift_intro: {
      bot: [
        { en: "Once you've paused, run a small ritual.", fr: "Une fois la pause prise, suis un petit rituel.", es: "Una vez que has parado, haz un pequeño ritual.", de: "Wenn du innegehalten hast, mach ein kleines Ritual.", it: "Una volta che ti sei fermato, fai un piccolo rituale.", da: "Når du har stoppet op, så lav et lille ritual.", bg: "След паузата направи малък ритуал.", tr: "Durakladıktan sonra küçük bir ritüel uygula." },
        { en: "🔎 *Investigate* the source. 📚 *Find better coverage.* 🌀 *Trace* the image back.", fr: "🔎 *Enquête* sur la source. 📚 *Cherche une autre couverture.* 🌀 *Remonte à la source* de l'image.", es: "🔎 *Investiga* la fuente. 📚 *Busca otra cobertura.* 🌀 *Rastrea* la imagen hasta su origen.", de: "🔎 *Untersuche* die Quelle. 📚 *Suche bessere Berichterstattung.* 🌀 *Verfolge* das Bild zurück.", it: "🔎 *Indaga* sulla fonte. 📚 *Cerca un'altra copertura.* 🌀 *Risali* all'origine dell'immagine.", da: "🔎 *Undersøg* kilden. 📚 *Find bedre dækning.* 🌀 *Spor* billedet tilbage.", bg: "🔎 *Провери* източника. 📚 *Намери по-добро отразяване.* 🌀 *Проследи* снимката до източника.", tr: "🔎 Kaynağı *araştır*. 📚 *Daha iyi haberler bul.* 🌀 Görseli *kaynağına kadar takip et*." }
      ],
      next: "investigate"
    },
    investigate: {
      bot: [
        { en: "*Investigate the source.* Who actually posted this?", fr: "*Enquête sur la source.* Qui a vraiment posté ça ?", es: "*Investiga la fuente.* ¿Quién ha publicado esto en realidad?", de: "*Untersuche die Quelle.* Wer hat das eigentlich gepostet?", it: "*Indaga sulla fonte.* Chi l'ha pubblicato davvero?", da: "*Undersøg kilden.* Hvem har egentlig postet det?", bg: "*Провери източника.* Кой всъщност е публикувал това?", tr: "*Kaynağı araştır.* Bunu aslında kim paylaştı?" },
        { en: "Click the account. Created last week? No real history? Only posts dramatic content? That, per my records, is a slop farm.", fr: "Clique sur le compte. Créé la semaine dernière ? Aucun historique réel ? Que des publications dramatiques ? Mes données disent que c'est une ferme à slop.", es: "Pulsa en la cuenta. ¿Creada la semana pasada? ¿Sin historial real? ¿Solo publica contenido dramático? Eso, según mis registros, es una granja de slop.", de: "Klick auf das Profil. Letzte Woche erstellt? Keine echte Historie? Postet nur dramatischen Inhalt? Das, laut meinen Aufzeichnungen, ist eine Slop-Farm.", it: "Clicca sull'account. Creato la settimana scorsa? Nessuna storia reale? Pubblica solo contenuti drammatici? Quello, secondo i miei archivi, è una fattoria di slop.", da: "Klik på kontoen. Oprettet i sidste uge? Ingen rigtig historik? Poster kun dramatisk indhold? Det er, ifølge mine optegnelser, en slop-farm.", bg: "Кликни върху акаунта. Създаден миналата седмица? Никаква реална история? Публикува само драматично съдържание? Това, според моите регистри, е slop ферма.", tr: "Hesaba tıkla. Geçen hafta mı açılmış? Gerçek bir geçmişi yok mu? Sadece dramatik içerik mi paylaşıyor? Kayıtlarıma göre bu bir slop çiftliği." }
      ],
      next: "find_coverage"
    },
    find_coverage: {
      bot: [
        { en: "*Find better coverage.* If a story is real, multiple verified outlets will have it within hours.", fr: "*Cherche une autre couverture.* Si une info est vraie, plusieurs médias vérifiés la couvriront en quelques heures.", es: "*Busca otra cobertura.* Si una noticia es real, varios medios verificados la cubrirán en pocas horas.", de: "*Suche bessere Berichterstattung.* Wenn eine Geschichte echt ist, haben sie mehrere verifizierte Quellen innerhalb von Stunden.", it: "*Cerca un'altra copertura.* Se una notizia è vera, vari media verificati la avranno entro poche ore.", da: "*Find bedre dækning.* Hvis en historie er ægte, vil flere verificerede medier have den inden for timer.", bg: "*Намери по-добро отразяване.* Ако новината е истинска, няколко проверени медии ще я отразят в рамките на часове.", tr: "*Daha iyi haberler bul.* Eğer bir haber gerçekse, doğrulanmış birden fazla yayın saatler içinde onu yayınlar." },
        { en: "Open a new tab. Search the claim. If only one tiny site is reporting it, that is, factually, suspicious.", fr: "Ouvre un nouvel onglet. Cherche l'affirmation. Si un seul petit site la rapporte, c'est suspect, point.", es: "Abre una pestaña nueva. Busca la afirmación. Si solo un sitio minúsculo lo cuenta, eso es, factualmente, sospechoso.", de: "Öffne einen neuen Tab. Such die Behauptung. Wenn nur eine winzige Seite darüber berichtet, ist das, faktisch, verdächtig.", it: "Apri una nuova scheda. Cerca l'affermazione. Se la riporta solo un sitarello, è, fattualmente, sospetto.", da: "Åbn en ny fane. Søg på påstanden. Hvis kun ét lillebitte site rapporterer det, er det, faktuelt, mistænkeligt.", bg: "Отвори нов раздел. Потърси твърдението. Ако само едно мъничко сайтче го съобщава, това е, технически, подозрително.", tr: "Yeni bir sekme aç. İddiayı arat. Eğer sadece minicik bir site bunu haberleştiriyorsa, bu fiilen şüphelidir." }
      ],
      next: "verify_check"
    },
    verify_check: {
      bot: [
        { en: "Mid-lesson question: have you ever clicked on an account's profile to see who's behind a viral post?", fr: "Petite question en cours de route : tu as déjà cliqué sur le profil d'un compte pour voir qui se cache derrière une publication virale ?", es: "Pregunta a mitad de lección: ¿alguna vez has pulsado en el perfil de una cuenta para ver quién está detrás de una publicación viral?", de: "Frage zwischendurch: hast du je auf das Profil eines Accounts geklickt, um zu sehen, wer hinter einem viralen Beitrag steckt?", it: "Domanda a metà lezione: hai mai cliccato sul profilo di un account per vedere chi c'è dietro un post virale?", da: "Spørgsmål midt i lektionen: har du nogensinde klikket på en konts profil for at se, hvem der står bag et viralt opslag?", bg: "Въпрос по средата на урока: кликвал·а ли си някога на профил на акаунт, за да видиш кой стои зад вирусна публикация?", tr: "Ders ortası soru: bir hesabın profiline tıklayıp viral bir gönderinin arkasında kim olduğunu hiç kontrol ettin mi?" }
      ],
      choices: [
        { label: { en: "Yes, regularly", fr: "Oui, régulièrement", es: "Sí, regularmente", de: "Ja, regelmäßig", it: "Sì, regolarmente", da: "Ja, jævnligt", bg: "Да, редовно", tr: "Evet, düzenli olarak" }, next: "trace_image", reaction: { en: "✅ You're already doing the basics. Janet bows.", fr: "✅ Tu fais déjà l'essentiel. Janet s'incline.", es: "✅ Ya haces lo básico. Janet se inclina.", de: "✅ Du machst schon die Grundlagen. Janet verbeugt sich.", it: "✅ Stai già facendo le basi. Janet si inchina.", da: "✅ Du gør allerede det grundlæggende. Janet bukker.", bg: "✅ Вече правиш основното. Janet се покланя.", tr: "✅ Temelleri zaten yapıyorsun. Janet selam veriyor." } },
        { label: { en: "Once or twice", fr: "Une ou deux fois", es: "Una o dos veces", de: "Ein- oder zweimal", it: "Una o due volte", da: "En eller to gange", bg: "Един или два пъти", tr: "Bir iki kez" }, next: "trace_image", reaction: { en: "Now's a good time to make it a habit.", fr: "Bon moment pour en faire un réflexe.", es: "Buen momento para convertirlo en hábito.", de: "Guter Moment, daraus eine Gewohnheit zu machen.", it: "Buon momento per farne un'abitudine.", da: "Godt tidspunkt at gøre det til en vane.", bg: "Подходящ момент да го превърнеш в навик.", tr: "Bunu alışkanlık haline getirmek için iyi bir zaman." } },
        { label: { en: "Never thought to", fr: "Jamais eu l'idée", es: "Nunca se me ocurrió", de: "Nie drauf gekommen", it: "Mai pensato", da: "Tænkte aldrig på det", bg: "Никога не ми е хрумвало", tr: "Aklıma hiç gelmedi" }, next: "trace_image", reaction: { en: "OK — keep this lesson handy. That's how it starts.", fr: "Ok — garde cette leçon sous la main. C'est par là que ça commence.", es: "Vale — guarda esta lección a mano. Así empieza.", de: "OK — leg dir diese Lektion griffbereit. So fängt's an.", it: "OK — tieni questa lezione a portata. Si comincia così.", da: "OK — hold denne lektion ved hånden. Sådan begynder det.", bg: "Окей — дръж този урок под ръка. Така започва.", tr: "Tamam — bu dersi yakınında tut. Başlangıç böyle olur." } }
      ]
    },
    trace_image: {
      bot: [
        { en: "*Trace* the image. A picture is a clue, not a proof.", fr: "*Remonte à la source.* Une photo, c'est un indice, pas une preuve.", es: "*Rastrea* la imagen. Una foto es una pista, no una prueba.", de: "*Verfolge* das Bild. Ein Bild ist ein Hinweis, kein Beweis.", it: "*Risali* all'immagine. Una foto è un indizio, non una prova.", da: "*Spor* billedet. Et billede er et spor, ikke et bevis.", bg: "*Проследи* снимката. Снимката е улика, не доказателство.", tr: "Görseli *takip et*. Bir fotoğraf bir ipucudur, kanıt değil." },
        { en: "Drop any image into Google Lens or TinEye for a reverse search. You'll see where else it appeared, and often when.", fr: "Glisse n'importe quelle image dans Google Lens ou TinEye pour une recherche inversée. Tu verras où elle est apparue ailleurs, et souvent quand.", es: "Suelta cualquier imagen en Google Lens o TinEye para hacer una búsqueda inversa. Verás dónde más ha aparecido, y muchas veces cuándo.", de: "Zieh ein beliebiges Bild in Google Lens oder TinEye für eine umgekehrte Suche. Du siehst, wo es sonst noch auftauchte, und oft wann.", it: "Trascina qualsiasi immagine in Google Lens o TinEye per una ricerca inversa. Vedrai dove altro è apparsa, e spesso quando.", da: "Læg et hvilket som helst billede i Google Lens eller TinEye for en omvendt søgning. Du vil se, hvor det ellers er dukket op, og ofte hvornår.", bg: "Пусни всяка снимка в Google Lens или TinEye за обратно търсене. Ще видиш къде другаде е изниквала и често — кога.", tr: "Herhangi bir görseli ters arama için Google Lens veya TinEye'a bırak. Başka nerede ortaya çıktığını ve çoğu zaman ne zaman ortaya çıktığını görürsün." },
        { en: "Same image attached to three completely different stories? Slop. Same image from years ago presented as 'breaking'? Slop.", fr: "Même image collée à trois histoires complètement différentes ? Slop. Même image vieille de plusieurs années présentée comme \"info en direct\" ? Slop.", es: "¿La misma imagen pegada a tres historias completamente distintas? Slop. ¿La misma imagen de hace años presentada como \"última hora\"? Slop.", de: "Dasselbe Bild zu drei völlig verschiedenen Geschichten? Slop. Dasselbe Bild von vor Jahren als 'Breaking News' präsentiert? Slop.", it: "La stessa immagine attaccata a tre storie completamente diverse? Slop. La stessa immagine di anni fa presentata come 'ultim'ora'? Slop.", da: "Samme billede knyttet til tre helt forskellige historier? Slop. Samme billede fra for år tilbage præsenteret som 'breaking'? Slop.", bg: "Същата снимка прикачена към три напълно различни истории? Slop. Същата снимка отпреди години, представена като \"извънредно\"? Slop.", tr: "Aynı görsel tamamen farklı üç habere mi iliştirilmiş? Slop. Yıllar önceki aynı görsel \"son dakika\" olarak mı sunulmuş? Slop." }
      ],
      next: "text_slop"
    },
    text_slop: {
      bot: [
        { en: "Quick widening of the lens before we test you: *slop is not only images*.", fr: "Petit élargissement avant de te tester : *le slop, ce n'est pas que des images*.", es: "Pequeña ampliación antes de ponerte a prueba: *el slop no son solo imágenes*.", de: "Kurze Erweiterung des Bildes, bevor wir dich testen: *Slop besteht nicht nur aus Bildern*.", it: "Piccolo allargamento prima del test: *lo slop non sono solo immagini*.", da: "Lille udvidelse, før vi tester dig: *slop er ikke kun billeder*.", bg: "Малко разширение, преди да те тестваме: *slop не са само снимки*.", tr: "Seni test etmeden önce küçük bir genişletme: *slop sadece görsellerden ibaret değil*." },
        { en: "It's also fake reviews (\"Best purchase of my life!!!\"), fake comments, fake testimonials, fake news articles (\"Doctors hate this one trick…\").", fr: "C'est aussi des faux avis (« Le meilleur achat de ma vie !!! »), des faux commentaires, des faux témoignages, des fausses news (« Les médecins détestent cette astuce… »).", es: "También son reseñas falsas (\"¡¡¡La mejor compra de mi vida!!!\"), comentarios falsos, testimonios falsos, artículos de noticias falsos (\"Los médicos odian este truco…\").", de: "Es sind auch gefälschte Bewertungen (\"Bester Kauf meines Lebens!!!\"), gefälschte Kommentare, gefälschte Erfahrungsberichte, gefälschte Nachrichtenartikel (\"Ärzte hassen diesen einen Trick…\").", it: "Sono anche recensioni false (\"Il miglior acquisto della mia vita!!!\"), commenti falsi, testimonianze false, articoli di notizie falsi (\"I medici odiano questo trucco…\").", da: "Det er også falske anmeldelser (\"Bedste køb i mit liv!!!\"), falske kommentarer, falske vidnesbyrd, falske nyhedsartikler (\"Læger hader dette ene trick…\").", bg: "Това са и фалшиви ревюта („Най-добрата ми покупка!!!“), фалшиви коментари, фалшиви свидетелства, фалшиви новинарски статии („Лекарите мразят този трик…“).", tr: "Aynı zamanda sahte yorumlar (\"Hayatımın en iyi alışverişi!!!\"), sahte yorumlar, sahte tanıklıklar, sahte haber makaleleri (\"Doktorlar bu numaradan nefret ediyor…\")." },
        { en: "Same machines, same speed, same motive. Read with the same skepticism.", fr: "Mêmes machines, même vitesse, mêmes motivations. À lire avec la même méfiance.", es: "Mismas máquinas, misma velocidad, mismos motivos. Léelo con el mismo escepticismo.", de: "Gleiche Maschinen, gleiches Tempo, gleiches Motiv. Mit derselben Skepsis lesen.", it: "Stesse macchine, stessa velocità, stessi motivi. Da leggere con lo stesso scetticismo.", da: "Samme maskiner, samme hastighed, samme motiv. Læs med samme skepsis.", bg: "Същите машини, същата скорост, същите мотиви. Чети със същата доза съмнение.", tr: "Aynı makineler, aynı hız, aynı amaç. Aynı şüpheyle oku." }
      ],
      next: "quiz_intro"
    },
    quiz_intro: {
      bot: [
        { en: "Time to play. Three rounds. Each round: an image. You tell me — *real or AI*?", fr: "Maintenant on joue. Trois manches. Une image par manche. Tu me dis — *vrai ou IA* ?", es: "Hora de jugar. Tres rondas. Cada ronda: una imagen. Tú me dices — *real o IA*?", de: "Spielzeit. Drei Runden. Jede Runde: ein Bild. Du sagst mir — *echt oder KI*?", it: "Tempo di giocare. Tre round. Ogni round: un'immagine. Tu mi dici — *vera o IA*?", da: "Tid til at spille. Tre runder. Hver runde: et billede. Du fortæller mig — *ægte eller AI*?", bg: "Време за игра. Три рунда. Във всеки рунд: снимка. Ти ми казваш — *истинско или AI*?", tr: "Oyun zamanı. Üç tur. Her turda bir görsel. Sen bana söyle — *gerçek mi, AI mı*?" },
        { en: "Janet has a slight advantage, but I will not cheat. Promise.", fr: "Janet a un léger avantage, mais promis, je ne triche pas.", es: "Janet tiene una ligera ventaja, pero prometo no hacer trampa.", de: "Janet hat einen kleinen Vorteil, aber ich werde nicht schummeln. Versprochen.", it: "Janet ha un leggero vantaggio, ma prometto di non barare.", da: "Janet har en lille fordel, men jeg lover ikke at snyde.", bg: "Janet има леко предимство, но обещавам да не мамя.", tr: "Janet'in küçük bir avantajı var ama hile yapmayacağım. Söz." }
      ],
      next: "q1_ecosse"
    },
    q1_ecosse: {
      bot: [
        { en: "🥁 Round 1.", fr: "🥁 Manche 1.", es: "🥁 Ronda 1.", de: "🥁 Runde 1.", it: "🥁 Round 1.", da: "🥁 Runde 1.", bg: "🥁 Рунд 1.", tr: "🥁 Tur 1." },
        { image: "assets/ecosse.png", alt: { en: "A rugged coastal cliff overlooking grey water and distant mountains under overcast skies, with green grass on top of the cliffs.", fr: "Une falaise côtière escarpée surplombant des eaux grises et des montagnes lointaines sous un ciel couvert, avec de l'herbe verte au sommet des falaises.", es: "Un acantilado costero escarpado sobre aguas grises y montañas lejanas bajo un cielo nublado, con hierba verde encima de los acantilados.", de: "Eine schroffe Küstenklippe über grauem Wasser und fernen Bergen unter bewölktem Himmel, mit grünem Gras auf den Klippen.", it: "Una scogliera costiera frastagliata sopra acque grigie e montagne lontane sotto un cielo coperto, con erba verde sopra le scogliere.", da: "En forrevet kystklippe over gråt vand og fjerne bjerge under en overskyet himmel, med grønt græs på toppen af klipperne.", bg: "Стръмна крайбрежна скала над сиви води и далечни планини под облачно небе, със зелена трева на върха.", tr: "Bulutlu gökyüzünün altında, gri sulara ve uzaktaki dağlara bakan engebeli bir kıyı uçurumu; uçurumların üzerinde yeşil çimenler var." } },
        { en: "A Scottish coastline. Real photograph or AI-generated?", fr: "Une côte écossaise. Vraie photo ou image générée par IA ?", es: "Una costa escocesa. ¿Foto real o imagen generada por IA?", de: "Eine schottische Küste. Echtes Foto oder KI-generiert?", it: "Una costa scozzese. Foto vera o immagine generata dall'IA?", da: "En skotsk kyst. Ægte foto eller AI-genereret?", bg: "Шотландско крайбрежие. Истинска снимка или генерирана от AI?", tr: "Bir İskoç kıyısı. Gerçek fotoğraf mı, AI tarafından mı üretilmiş?" }
      ],
      choices: [
        { label: { en: "Real photo", fr: "Vraie photo", es: "Foto real", de: "Echtes Foto", it: "Foto vera", da: "Ægte foto", bg: "Истинска снимка", tr: "Gerçek fotoğraf" }, next: "q1_explain", reaction: { en: "Hmm — let me show you why not.", fr: "Hmm — laisse-moi te montrer pourquoi non.", es: "Hmm — déjame mostrarte por qué no.", de: "Hmm — lass mich dir zeigen, warum nicht.", it: "Hmm — lascia che ti mostri perché no.", da: "Hmm — lad mig vise dig hvorfor ikke.", bg: "Хмм — нека ти покажа защо не.", tr: "Hmm — neden olmadığını sana göstereyim." } },
        { label: { en: "AI-generated", fr: "Générée par IA", es: "Generada por IA", de: "KI-generiert", it: "Generata dall'IA", da: "AI-genereret", bg: "Генерирана от AI", tr: "AI tarafından üretilmiş" }, next: "q1_explain", reaction: { en: "✅ Correct!", fr: "✅ Bravo !", es: "✅ ¡Correcto!", de: "✅ Richtig!", it: "✅ Corretto!", da: "✅ Korrekt!", bg: "✅ Точно!", tr: "✅ Doğru!" } }
      ]
    },
    q1_explain: {
      bot: [
        { en: "It's AI. And here's the staggering part — *this place does not exist*. The light, the cliffs, the moody sky: every pixel fabricated.", fr: "C'est de l'IA. Et le plus dingue — *ce lieu n'existe pas*. La lumière, les falaises, le ciel maussade : chaque pixel a été inventé.", es: "Es IA. Y aquí está lo asombroso — *este lugar no existe*. La luz, los acantilados, el cielo melancólico: cada píxel fabricado.", de: "Es ist KI. Und das Verblüffende — *diesen Ort gibt es nicht*. Das Licht, die Klippen, der trübe Himmel: jeder Pixel erfunden.", it: "È IA. E la cosa pazzesca — *questo posto non esiste*. La luce, le scogliere, il cielo malinconico: ogni pixel inventato.", da: "Det er AI. Og det vilde — *dette sted findes ikke*. Lyset, klipperne, den dystre himmel: hver pixel opfundet.", bg: "Това е AI. И най-зашеметяващото — *това място не съществува*. Светлината, скалите, мрачното небе: всеки пиксел измислен.", tr: "AI. Ve en şaşırtıcı kısım — *bu yer var olmuyor*. Işık, uçurumlar, kasvetli gökyüzü: her piksel uydurma." },
        { en: "Modern image models can invent entire landscapes that read as real. With your eyes, no matter how carefully you looked, you could not have caught it. Janet checked.", fr: "Les modèles d'image actuels savent fabriquer des paysages entiers qui sonnent vrais. Avec les yeux, même en plissant, tu n'aurais pas pu le repérer. Janet a vérifié.", es: "Los modelos modernos de imagen pueden inventar paisajes enteros que parecen reales. Mirando, por más atentamente que lo hicieras, no podrías haberlo pillado. Janet lo verificó.", de: "Moderne Bildmodelle können ganze Landschaften erfinden, die echt aussehen. Mit den Augen, egal wie genau du hingeschaut hättest, wärst du nicht draufgekommen. Janet hat geprüft.", it: "I modelli di immagine moderni sanno inventare interi paesaggi che sembrano veri. A occhio nudo, per quanto guardassi, non avresti potuto coglierlo. Janet ha controllato.", da: "Moderne billedmodeller kan opfinde hele landskaber, der ser ægte ud. Med øjnene, uanset hvor nøje du kiggede, kunne du ikke have fanget det. Janet tjekkede.", bg: "Модерните модели за изображения могат да измислят цели пейзажи, които изглеждат истински. С очи, колкото и да гледаш, не би могъл·а да го хванеш. Janet провери.", tr: "Modern görsel modelleri gerçek görünen koca manzaralar uydurabiliyor. Gözle, ne kadar dikkatli baksan da, yakalayamazdın. Janet kontrol etti." },
        { en: "What you *could* have done: reverse-image-search. A real Scottish coastline returns hundreds of photographer matches. This one returns nothing.", fr: "Ce que tu *pouvais* faire : une recherche d'image inversée. Une vraie côte écossaise renvoie des centaines de correspondances de photographes. Celle-ci, zéro.", es: "Lo que *sí* podías hacer: búsqueda inversa de imagen. Una costa escocesa real devuelve cientos de coincidencias de fotógrafos. Esta, ninguna.", de: "Was du *machen* konntest: umgekehrte Bildsuche. Eine echte schottische Küste liefert Hunderte Treffer von Fotograf*innen. Diese hier null.", it: "Quello che *potevi* fare: ricerca inversa di immagini. Una vera costa scozzese restituisce centinaia di corrispondenze di fotografi. Questa, zero.", da: "Det du *kunne* have gjort: omvendt billedsøgning. En rigtig skotsk kyst giver hundredvis af match fra fotografer. Denne her giver nul.", bg: "Това, което *можеше* да направиш: обратно търсене на изображение. Истинско шотландско крайбрежие връща стотици съвпадения с фотографи. Това — нула.", tr: "*Yapabileceğin* şey: ters görsel arama. Gerçek bir İskoç kıyısı yüzlerce fotoğrafçı eşleşmesi döndürür. Bu hiçbir şey döndürmez." },
        { en: "Lesson 1: when AI can fabricate places that don't exist, *trace, don't squint.*", fr: "Leçon 1 : quand l'IA fabrique des lieux qui n'existent pas, *remonte à la source, ne plisse pas les yeux.*", es: "Lección 1: cuando la IA puede fabricar lugares que no existen, *rastrea, no entornes los ojos.*", de: "Lektion 1: wenn KI Orte fabrizieren kann, die es nicht gibt, *verfolgen, nicht zusammenkneifen.*", it: "Lezione 1: quando l'IA può inventare luoghi che non esistono, *risali, non strizzare gli occhi.*", da: "Lektion 1: når AI kan fabrikere steder, der ikke findes, *spor, ikke skel.*", bg: "Урок 1: когато AI може да измисля места, които не съществуват, *проследи, не присвивай очи.*", tr: "Ders 1: AI var olmayan yerleri uydurabildiğinde, *iz sür, gözünü kısma.*" }
      ],
      next: "q2_socotra"
    },
    q2_socotra: {
      bot: [
        { en: "🥁 Round 2. This one is sneaky.", fr: "🥁 Manche 2. Celle-là est sournoise.", es: "🥁 Ronda 2. Esta es traicionera.", de: "🥁 Runde 2. Diese ist hinterhältig.", it: "🥁 Round 2. Questo è subdolo.", da: "🥁 Runde 2. Den her er lumsk.", bg: "🥁 Рунд 2. Този е коварен.", tr: "🥁 Tur 2. Bu sinsi bir tane." },
        { image: "assets/socotra.png", alt: { en: "Two trees with flat, umbrella-shaped tops on a rocky plateau at sunset, with two tiny human figures visible for scale.", fr: "Deux arbres aux cimes plates en forme de parasol sur un plateau rocheux au coucher du soleil, avec deux petites silhouettes humaines visibles pour l'échelle.", es: "Dos árboles con copas planas en forma de paraguas sobre una meseta rocosa al atardecer, con dos figuras humanas diminutas visibles para dar escala.", de: "Zwei Bäume mit flachen, schirmförmigen Kronen auf einem felsigen Plateau bei Sonnenuntergang, mit zwei winzigen menschlichen Figuren als Größenvergleich.", it: "Due alberi con chiome piatte a forma di ombrello su un altopiano roccioso al tramonto, con due piccole figure umane visibili come riferimento di scala.", da: "To træer med flade, paraplyformede toppe på et stenet plateau ved solnedgang, med to bittesmå menneskefigurer synlige som målestok.", bg: "Две дървета с плоски, чадъровидни корони на скалисто плато по залез слънце, с две мънички човешки фигурки за мащаб.", tr: "Gün batımında kayalık bir platoda, düz ve şemsiye biçimli tepeleri olan iki ağaç; ölçek için iki minik insan figürü görünüyor." } },
        { en: "Two trees with flat tops at sunset. Real or AI?", fr: "Deux arbres à cime plate au coucher du soleil. Vrai ou IA ?", es: "Dos árboles con copas planas al atardecer. ¿Real o IA?", de: "Zwei Bäume mit flachen Kronen bei Sonnenuntergang. Echt oder KI?", it: "Due alberi con chiome piatte al tramonto. Vero o IA?", da: "To træer med flade toppe ved solnedgang. Ægte eller AI?", bg: "Две дървета с плоски корони по залез. Истинско или AI?", tr: "Gün batımında düz tepeli iki ağaç. Gerçek mi, AI mı?" }
      ],
      choices: [
        { label: { en: "Real photo", fr: "Vraie photo", es: "Foto real", de: "Echtes Foto", it: "Foto vera", da: "Ægte foto", bg: "Истинска снимка", tr: "Gerçek fotoğraf" }, next: "q2_explain", reaction: { en: "✅ Yes!", fr: "✅ Oui !", es: "✅ ¡Sí!", de: "✅ Ja!", it: "✅ Sì!", da: "✅ Ja!", bg: "✅ Да!", tr: "✅ Evet!" } },
        { label: { en: "AI-generated", fr: "Générée par IA", es: "Generada por IA", de: "KI-generiert", it: "Generata dall'IA", da: "AI-genereret", bg: "Генерирана от AI", tr: "AI tarafından üretilmiş" }, next: "q2_explain", reaction: { en: "Surprise — it's real!", fr: "Surprise — c'est une vraie photo !", es: "Sorpresa — ¡es real!", de: "Überraschung — es ist echt!", it: "Sorpresa — è vera!", da: "Overraskelse — den er ægte!", bg: "Изненада — истинска е!", tr: "Sürpriz — gerçek!" } }
      ]
    },
    q2_explain: {
      bot: [
        { en: "Plot twist — it's *real*. Those are *Dragon Blood Trees* (Dracaena cinnabari), endemic to Socotra Island, off the coast of Yemen. They really do look like floating umbrellas.", fr: "Rebondissement — c'est *vrai*. Ce sont des *arbres dragonniers* (Dracaena cinnabari), endémiques à l'île de Socotra, au large du Yémen. Ils ressemblent vraiment à des parasols flottants.", es: "Giro — es *real*. Son *Árboles de Sangre de Dragón* (Dracaena cinnabari), endémicos de la isla de Socotra, frente a las costas de Yemen. De verdad parecen paraguas flotantes.", de: "Plot-Twist — es ist *echt*. Das sind *Drachenblutbäume* (Dracaena cinnabari), endemisch auf der Insel Sokotra vor der Küste des Jemen. Sie sehen wirklich wie schwebende Regenschirme aus.", it: "Colpo di scena — è *vero*. Sono *Alberi del sangue di drago* (Dracaena cinnabari), endemici dell'isola di Socotra, al largo dello Yemen. Sembrano davvero ombrelli fluttuanti.", da: "Plot-twist — det er *ægte*. Det er *Dragetræer* (Dracaena cinnabari), endemiske for øen Socotra ud for Yemens kyst. De ligner virkelig flydende paraplyer.", bg: "Обрат — *истинско* е. Това са *Драконови дървета* (Dracaena cinnabari), ендемични за остров Сокотра, край бреговете на Йемен. Наистина изглеждат като плаващи чадъри.", tr: "Sürpriz — *gerçek*. Bunlar *Ejderha Kanı Ağaçları* (Dracaena cinnabari), Yemen kıyısındaki Sokotra Adası'na özgü. Gerçekten süzülen şemsiyelere benziyorlar." },
        { en: "Same tool, opposite verdict. A reverse-image-search on this one returns *hundreds* of nearly identical shots by real photographers, all tagged Socotra. Reality has receipts.", fr: "Même outil, verdict inverse. Une recherche inversée sur celle-là renvoie *des centaines* de clichés quasi identiques par de vrai·e·s photographes, tous taggués Socotra. La réalité a ses preuves.", es: "Misma herramienta, veredicto opuesto. Una búsqueda inversa sobre esta devuelve *cientos* de fotos casi idénticas de fotógrafos reales, todas etiquetadas Socotra. La realidad tiene recibos.", de: "Gleiches Werkzeug, umgekehrtes Urteil. Eine umgekehrte Bildsuche zu diesem hier liefert *Hunderte* fast identische Aufnahmen von echten Fotograf*innen, alle mit Sokotra getaggt. Die Realität hat Belege.", it: "Stesso strumento, verdetto opposto. Una ricerca inversa su questa restituisce *centinaia* di scatti quasi identici di veri fotografi, tutti taggati Socotra. La realtà ha le sue prove.", da: "Samme værktøj, modsat dom. En omvendt billedsøgning på den her giver *hundredvis* af næsten identiske billeder af rigtige fotografer, alle tagget Socotra. Virkeligheden har sine kvitteringer.", bg: "Същият инструмент, противоположна присъда. Обратното търсене на тази връща *стотици* почти идентични кадри от истински фотографи, всички тагнати Socotra. Реалността има своите доказателства.", tr: "Aynı araç, ters karar. Buna yapılan ters arama, gerçek fotoğrafçıların *yüzlerce* neredeyse aynı çekimini döndürür, hepsi Sokotra etiketli. Gerçeğin elinde makbuzları var." },
        { en: "Lesson 2: *surreal-looking ≠ AI.* Don't dismiss reality just because it looks improbable — verify it the same way you'd verify a fake.", fr: "Leçon 2 : *avoir l'air irréel ≠ IA.* Ne rejette pas la réalité juste parce qu'elle paraît improbable — vérifie-la comme tu vérifierais un faux.", es: "Lección 2: *parecer surreal ≠ IA.* No descartes la realidad solo porque parezca improbable — verifícala como verificarías un falso.", de: "Lektion 2: *surreal aussehen ≠ KI.* Verwirf die Realität nicht, nur weil sie unwahrscheinlich aussieht — prüfe sie genauso, wie du eine Fälschung prüfen würdest.", it: "Lezione 2: *sembrare surreale ≠ IA.* Non scartare la realtà solo perché sembra improbabile — verificala come verificheresti un falso.", da: "Lektion 2: *at se surrealistisk ud ≠ AI.* Afvis ikke virkeligheden, bare fordi den ser usandsynlig ud — verificér den ligesom du ville verificere en forfalskning.", bg: "Урок 2: *да изглежда нереално ≠ AI.* Не отхвърляй реалността само защото изглежда невероятна — провери я по същия начин, по който би проверил·а фалшификат.", tr: "Ders 2: *gerçeküstü görünmek ≠ AI.* Sırf olası olmayan göründüğü için gerçeği reddetme — sahte bir şeyi nasıl doğrularsan onu da öyle doğrula." }
      ],
      next: "q3_trump"
    },
    q3_trump: {
      bot: [
        { en: "🥁 Round 3. Bonus boss. This one has a twist.", fr: "🥁 Manche 3. Boss bonus. Cette manche a un rebondissement.", es: "🥁 Ronda 3. Jefe bonus. Esta ronda tiene un giro.", de: "🥁 Runde 3. Bonus-Endgegner. Diese Runde hat einen Twist.", it: "🥁 Round 3. Boss bonus. Questo round ha un colpo di scena.", da: "🥁 Runde 3. Bonus-boss. Den her runde har et twist.", bg: "🥁 Рунд 3. Бонус бос. Този рунд има обрат.", tr: "🥁 Tur 3. Bonus patron. Bu turda bir sürpriz var." },
        { image: "assets/trump.png", alt: { en: "A man in a dark suit walks on a tarmac alongside a tall grey humanoid figure, flanked by security personnel and military vehicles. A thumb is visible at the edge of the frame, as if the photo is being shown on a phone.", fr: "Un homme en costume sombre marche sur un tarmac aux côtés d'une grande silhouette humanoïde grise, entouré d'agents de sécurité et de véhicules militaires. Un pouce est visible sur le bord du cadre, comme si la photo s'affichait sur un téléphone.", es: "Un hombre con traje oscuro camina por una pista junto a una figura humanoide gris alta, flanqueado por personal de seguridad y vehículos militares. Se ve un pulgar al borde del encuadre, como si la foto se mostrara en un móvil.", de: "Ein Mann im dunklen Anzug geht auf einem Rollfeld neben einer großen grauen humanoiden Figur, flankiert von Sicherheitspersonal und Militärfahrzeugen. Am Bildrand ist ein Daumen zu sehen, als würde das Foto auf einem Handy gezeigt.", it: "Un uomo in abito scuro cammina su una pista d'aeroporto accanto a una figura umanoide grigia e alta, fiancheggiato da personale di sicurezza e veicoli militari. Si vede un pollice al bordo dell'inquadratura, come se la foto fosse mostrata su un telefono.", da: "En mand i mørkt jakkesæt går på en startbane ved siden af en høj grå humanoid figur, flankeret af sikkerhedspersonale og militærkøretøjer. En tommelfinger er synlig i kanten af billedet, som om billedet vises på en telefon.", bg: "Мъж в тъмен костюм върви по писта до висока сива хуманоидна фигура, придружен от охрана и военни превозни средства. В края на кадъра се вижда палец, сякаш снимката е показана на телефон.", tr: "Koyu renk takım elbiseli bir adam, uzun boylu gri bir insanımsı figürün yanında pistte yürüyor; etrafında güvenlik personeli ve askeri araçlar var. Karenin kenarında, sanki fotoğraf bir telefonda gösteriliyormuş gibi bir başparmak görünüyor." } },
        { en: "This image shows a US President walking with what looks like a Grey alien. Pick your verdict:", fr: "Cette image montre un Président américain marchant avec ce qui ressemble à un alien gris. Ton verdict :", es: "Esta imagen muestra a un Presidente de EE.UU. caminando junto a lo que parece un alien Gris. Tu veredicto:", de: "Dieses Bild zeigt einen US-Präsidenten beim Spaziergang mit etwas, das wie ein Grey-Alien aussieht. Dein Urteil:", it: "Questa immagine mostra un Presidente degli Stati Uniti che cammina con quello che sembra un alieno Grigio. Il tuo verdetto:", da: "Dette billede viser en amerikansk Præsident gå sammen med noget der ligner et Grey-rumvæsen. Din dom:", bg: "Тази снимка показва американски Президент, който върви с нещо подобно на сив извънземен. Твоята присъда:", tr: "Bu görsel, bir ABD Başkanını Gri uzaylıya benzeyen bir şeyle yürürken gösteriyor. Kararını ver:" }
      ],
      choices: [
        { label: { en: "Real photo", fr: "Vraie photo", es: "Foto real", de: "Echtes Foto", it: "Foto vera", da: "Ægte foto", bg: "Истинска снимка", tr: "Gerçek fotoğraf" }, next: "q3_explain", reaction: { en: "Per my records, no aliens yet. Stay tuned.", fr: "D'après mes archives, pas encore d'aliens. On reste à l'affût.", es: "Según mis registros, todavía no hay aliens. Sigamos atentos.", de: "Laut meinen Aufzeichnungen noch keine Aliens. Bleib dran.", it: "Secondo i miei archivi, niente alieni per ora. Restiamo sintonizzati.", da: "Ifølge mine optegnelser ingen rumvæsener endnu. Bliv hængende.", bg: "Според регистрите ми — все още няма извънземни. Чакаме.", tr: "Kayıtlarıma göre henüz uzaylı yok. Takipte kal." } },
        { label: { en: "AI — and only a random scammer would post this", fr: "IA — et seul un arnaqueur lambda posterait ça", es: "IA — y solo un estafador random la publicaría", de: "KI — und nur ein x-beliebiger Betrüger würde das posten", it: "IA — e solo un truffatore qualunque la pubblicherebbe", da: "AI — og kun en tilfældig svindler ville poste det", bg: "AI — и само случаен измамник би я публикувал", tr: "AI — ve bunu ancak rastgele bir dolandırıcı paylaşır" }, next: "q3_explain", reaction: { en: "Half right. It's AI. But about the 'only a scammer' part…", fr: "À moitié juste. C'est de l'IA. Mais sur le \"seul un arnaqueur\"…", es: "Medio acierto. Es IA. Pero lo de \"solo un estafador\"…", de: "Halb richtig. Es ist KI. Aber zum 'nur ein Betrüger'-Teil…", it: "Mezzo giusto. È IA. Ma sulla parte \"solo un truffatore\"…", da: "Halvt rigtigt. Det er AI. Men angående 'kun en svindler'-delen…", bg: "Наполовина прав. AI е. Но за \"само измамник\"...", tr: "Yarı doğru. AI. Ama 'sadece bir dolandırıcı' kısmı için..." } },
        { label: { en: "AI — posted on the President's actual official account", fr: "IA — posté sur le compte officiel du Président lui-même", es: "IA — publicada en la cuenta oficial del Presidente mismo", de: "KI — auf dem echten offiziellen Account des Präsidenten gepostet", it: "IA — pubblicata sull'account ufficiale del Presidente stesso", da: "AI — postet på Præsidentens egen officielle konto", bg: "AI — публикувана в собствения официален акаунт на Президента", tr: "AI — Başkanın gerçek resmi hesabında paylaşılmış" }, next: "q3_explain", reaction: { en: "✅ Spot on. Welcome to 2026.", fr: "✅ Pile dans le mille. Bienvenue en 2026.", es: "✅ Justo en el clavo. Bienvenido·a a 2026.", de: "✅ Genau. Willkommen im Jahr 2026.", it: "✅ Esattamente. Benvenuto·a nel 2026.", da: "✅ Lige i øjet. Velkommen til 2026.", bg: "✅ Право в десетката. Добре дошъл·а в 2026.", tr: "✅ Tam isabet. 2026'ya hoş geldin." } }
      ]
    },
    q3_explain: {
      bot: [
        { en: "Yes, it's AI. The alien is, of course, the giveaway. Easy doubt.", fr: "Oui, c'est de l'IA. L'alien, évidemment, est le détail qui trahit. Le doute est facile.", es: "Sí, es IA. El alien es, evidentemente, lo que delata. La duda es fácil.", de: "Ja, es ist KI. Der Alien ist natürlich das verräterische Detail. Der Zweifel ist einfach.", it: "Sì, è IA. L'alieno è, ovviamente, il dettaglio che tradisce. Il dubbio è facile.", da: "Ja, det er AI. Rumvæsenet er naturligvis det forræderiske detalje. Tvivlen er nem.", bg: "Да, AI е. Извънземният е, естествено, детайлът, който издава. Съмнението е лесно.", tr: "Evet, AI. Uzaylı, doğal olarak, açık eden detay. Şüphe etmek kolay." },
        { en: "BUT — this kind of AI image has been shared from authentic, official, verified government accounts. So your usual reflex ('is the account real?') answers 'yes, real account' — and you still end up with a fabricated image in front of you.", fr: "MAIS — ce genre d'image IA a été partagé depuis des comptes gouvernementaux authentiques, officiels, vérifiés. Du coup, ton réflexe habituel (« le compte est-il réel ? ») répond « oui, compte réel » — et tu te retrouves quand même avec une image fabriquée sous les yeux.", es: "PERO — este tipo de imagen IA se ha compartido desde cuentas gubernamentales auténticas, oficiales y verificadas. Así que tu reflejo habitual ('¿es real la cuenta?') responde 'sí, cuenta real' — y aun así te quedas con una imagen fabricada delante.", de: "ABER — solche KI-Bilder wurden von authentischen, offiziellen, verifizierten Regierungskonten geteilt. Dein üblicher Reflex ('ist das Konto echt?') antwortet 'ja, echtes Konto' — und du sitzt trotzdem auf einem fabrizierten Bild.", it: "MA — questo tipo di immagine IA è stato condiviso da account governativi autentici, ufficiali, verificati. Quindi il tuo riflesso abituale ('l'account è reale?') risponde 'sì, account reale' — e ti ritrovi comunque con un'immagine fabbricata davanti.", da: "MEN — den slags AI-billede er blevet delt fra autentiske, officielle, verificerede regeringskonti. Så din sædvanlige refleks ('er kontoen ægte?') svarer 'ja, ægte konto' — og du sidder stadig med et fabrikeret billede foran dig.", bg: "НО — подобни AI снимки са били споделяни от автентични, официални, верифицирани правителствени акаунти. Затова обичайният ти рефлекс („истински ли е акаунтът?“) отговаря „да, истински акаунт“ — и пак ти остава фалшифицирано изображение пред теб.", tr: "AMA — bu tür AI görselleri, otantik, resmi, doğrulanmış hükümet hesaplarından paylaşıldı. Yani her zamanki refleksin ('hesap gerçek mi?') 'evet, gerçek hesap' diyor — ve gözünün önünde yine uydurma bir görsel kalıyor." },
        { en: "Lesson 3, the awkward one: in 2026, even verified accounts share AI content. Sometimes labeled, sometimes not. 'Trust the source' has become necessary but no longer sufficient. The *content itself* also needs scrutiny.", fr: "Leçon 3, la plus dérangeante : en 2026, même les comptes vérifiés partagent du contenu IA. Parfois étiqueté, parfois non. « Faire confiance à la source » reste nécessaire, mais ne suffit plus. Le *contenu lui-même* doit aussi passer à la loupe.", es: "Lección 3, la incómoda: en 2026, incluso las cuentas verificadas comparten contenido IA. A veces etiquetado, a veces no. 'Confiar en la fuente' sigue siendo necesario, pero ya no basta. El *contenido en sí* también debe pasar por la lupa.", de: "Lektion 3, die unangenehme: 2026 teilen selbst verifizierte Konten KI-Inhalte. Mal gekennzeichnet, mal nicht. 'Der Quelle vertrauen' bleibt nötig, reicht aber nicht mehr. Der *Inhalt selbst* muss auch unter die Lupe.", it: "Lezione 3, quella scomoda: nel 2026, anche gli account verificati condividono contenuti IA. A volte etichettati, a volte no. 'Fidarsi della fonte' resta necessario, ma non basta più. Il *contenuto stesso* deve anche passare alla lente.", da: "Lektion 3, den ubehagelige: i 2026 deler selv verificerede konti AI-indhold. Nogle gange markeret, nogle gange ikke. 'Stol på kilden' er stadig nødvendigt, men ikke længere tilstrækkeligt. Også *indholdet selv* skal under luppen.", bg: "Урок 3, неудобният: през 2026 дори верифицирани акаунти споделят AI съдържание. Понякога с етикет, понякога без. „Доверявай се на източника“ остава необходимо, но вече не е достатъчно. И самото *съдържание* трябва да мине под лупата.", tr: "Ders 3, rahatsız edici olanı: 2026'da, doğrulanmış hesaplar bile AI içeriği paylaşıyor. Bazen etiketli, bazen değil. 'Kaynağa güven' hâlâ gerekli, ama artık yeterli değil. *İçeriğin kendisi* de mercek altına alınmalı." }
      ],
      next: "quiz_recap"
    },
    quiz_recap: {
      bot: [
        { en: "Three rounds, three lessons, one uncomfortable truth:", fr: "Trois manches, trois leçons, une vérité un peu dérangeante :", es: "Tres rondas, tres lecciones, una verdad un poco incómoda:", de: "Drei Runden, drei Lektionen, eine etwas unangenehme Wahrheit:", it: "Tre round, tre lezioni, una verità un po' scomoda:", da: "Tre runder, tre lektioner, én lidt ubehagelig sandhed:", bg: "Три рунда, три урока, една малко неудобна истина:", tr: "Üç tur, üç ders, biraz rahatsız edici tek bir gerçek:" },
        { en: "*Being absolutely sure a piece of content is real* — from looking at the content alone — has become, per my records, somewhere between *very hard* and *impossible*.", fr: "*Être absolument sûr·e qu'un contenu est réel* — rien qu'en le regardant — est devenu, selon mes registres, quelque part entre *très difficile* et *impossible*.", es: "*Estar absolutamente seguro·a de que un contenido es real* — solo mirándolo — se ha vuelto, según mis registros, algo entre *muy difícil* e *imposible*.", de: "*Absolut sicher zu sein, dass ein Inhalt echt ist* — allein durchs Hinsehen — ist, laut meinen Aufzeichnungen, irgendwo zwischen *sehr schwer* und *unmöglich* geworden.", it: "*Essere assolutamente sicuro·a che un contenuto sia reale* — solo guardandolo — è diventato, secondo i miei archivi, qualcosa tra *molto difficile* e *impossibile*.", da: "*At være helt sikker på, at et indhold er ægte* — bare ved at se på det — er blevet, ifølge mine optegnelser, noget mellem *meget svært* og *umuligt*.", bg: "*Да си абсолютно сигурен·а, че едно съдържание е истинско* — само като го гледаш — е станало, според моите регистри, някъде между *много трудно* и *невъзможно*.", tr: "*Bir içeriğin gerçek olduğundan kesinlikle emin olmak* — sadece ona bakarak — artık, kayıtlarıma göre, *çok zor* ile *imkânsız* arasında bir yerde." },
        { en: "Looking won't save you (AI is too good). Source-checking won't save you (verified accounts share slop). Strangeness won't save you (reality is sometimes strange too).", fr: "Regarder ne te sauvera pas (l'IA est trop bonne). Vérifier la source ne te sauvera pas (les comptes vérifiés partagent du slop). La bizarrerie ne te sauvera pas (la réalité aussi est parfois bizarre).", es: "Mirar no te salvará (la IA es demasiado buena). Verificar la fuente no te salvará (las cuentas verificadas comparten slop). La rareza no te salvará (a veces la realidad también es rara).", de: "Hinsehen rettet dich nicht (KI ist zu gut). Quellenprüfung rettet dich nicht (verifizierte Konten teilen Slop). Seltsamkeit rettet dich nicht (auch die Realität ist manchmal seltsam).", it: "Guardare non ti salverà (l'IA è troppo brava). Verificare la fonte non ti salverà (gli account verificati condividono slop). La stranezza non ti salverà (anche la realtà è a volte strana).", da: "At kigge redder dig ikke (AI er for god). At tjekke kilden redder dig ikke (verificerede konti deler slop). Mærkelighed redder dig ikke (virkeligheden er også nogle gange mærkelig).", bg: "Да гледаш няма да те спаси (AI е твърде добър). Да проверяваш източника няма да те спаси (верифицираните акаунти споделят slop). Странността няма да те спаси (реалността също понякога е странна).", tr: "Bakmak seni kurtarmaz (AI çok iyi). Kaynak kontrolü seni kurtarmaz (doğrulanmış hesaplar slop paylaşıyor). Tuhaflık seni kurtarmaz (gerçek de bazen tuhaftır)." },
        { en: "The sustainable defense: *healthy skepticism by default*, *active verification when the stakes matter*. That's the lesson of the three rounds, rolled into one.", fr: "La défense durable : *scepticisme par défaut*, *vérification active quand les enjeux comptent*. Voilà la leçon des trois manches, en une.", es: "La defensa sostenible: *escepticismo por defecto*, *verificación activa cuando lo que está en juego importa*. Esa es la lección de las tres rondas, en una.", de: "Die nachhaltige Verteidigung: *gesunde Skepsis als Standard*, *aktive Verifikation wenn etwas auf dem Spiel steht*. Das ist die Lektion der drei Runden, in einer.", it: "La difesa sostenibile: *scetticismo per impostazione predefinita*, *verifica attiva quando la posta in gioco conta*. Questa è la lezione dei tre round, in una.", da: "Det bæredygtige forsvar: *sund skepsis som standard*, *aktiv verifikation når det betyder noget*. Det er lektionen fra de tre runder, samlet i én.", bg: "Устойчивата защита: *здравословен скептицизъм по подразбиране*, *активна проверка, когато залогът е голям*. Това е урокът от трите рунда, събран в един.", tr: "Sürdürülebilir savunma: varsayılan olarak *sağlıklı şüphecilik*, riskler önemli olduğunda *aktif doğrulama*. Üç turun dersi, tek bir derste." }
      ],
      next: "recap_feel"
    },
    recap_feel: {
      bot: [
        { en: "Be honest. How does that uncomfortable truth land with you?", fr: "Sois honnête. Comment cette vérité un peu inconfortable atterrit chez toi ?", es: "Sé sincero·a. ¿Cómo te cae esta verdad incómoda?", de: "Sei ehrlich. Wie landet diese unangenehme Wahrheit bei dir?", it: "Sii onesto·a. Come ti arriva questa verità scomoda?", da: "Vær ærlig. Hvordan rammer den ubehagelige sandhed dig?", bg: "Бъди честен·а. Как ти стои тази неудобна истина?", tr: "Dürüst ol. Bu rahatsız edici gerçek sana nasıl geliyor?" }
      ],
      choices: [
        { label: { en: "Liberating, honestly", fr: "Libérateur, honnêtement", es: "Liberadora, sinceramente", de: "Befreiend, ehrlich gesagt", it: "Liberatoria, onestamente", da: "Befriende, helt ærligt", bg: "Освобождаващо, честно", tr: "Açıkçası, özgürleştirici" }, next: "tools", reaction: { en: "✅ Yes. Once you accept the limit, you stop wasting energy on the impossible.", fr: "✅ Oui. Une fois la limite acceptée, tu arrêtes de gaspiller de l'énergie sur l'impossible.", es: "✅ Sí. Una vez aceptas el límite, dejas de gastar energía en lo imposible.", de: "✅ Ja. Sobald du das Limit akzeptierst, hörst du auf, Energie ins Unmögliche zu stecken.", it: "✅ Sì. Una volta accettato il limite, smetti di sprecare energia nell'impossibile.", da: "✅ Ja. Når først du accepterer grænsen, holder du op med at spilde energi på det umulige.", bg: "✅ Да. След като приемеш ограничението, спираш да хабиш енергия за невъзможното.", tr: "✅ Evet. Sınırı kabul ettiğinde, imkânsıza enerji harcamayı bırakırsın." } },
        { label: { en: "A bit overwhelming", fr: "Un peu vertigineux", es: "Un poco abrumadora", de: "Etwas überwältigend", it: "Un po' opprimente", da: "Lidt overvældende", bg: "Малко смазващо", tr: "Biraz bunaltıcı" }, next: "tools", reaction: { en: "Same. The good news: we now focus on what *does* work.", fr: "Pareil. La bonne nouvelle : on passe maintenant à ce qui *marche*.", es: "Igual. La buena noticia: ahora nos centramos en lo que *sí* funciona.", de: "Genauso. Die gute Nachricht: wir konzentrieren uns jetzt auf das, was *funktioniert*.", it: "Anch'io. La buona notizia: ora ci concentriamo su cosa *funziona*.", da: "I lige måde. Den gode nyhed: vi fokuserer nu på det, der *virker*.", bg: "И на мен. Добрата новина: сега се фокусираме върху това, което *работи*.", tr: "Bende de. İyi haber: şimdi *işe yarayan* şeylere odaklanıyoruz." } },
        { label: { en: "Already paranoid, this confirms it", fr: "Déjà parano, ça confirme", es: "Ya paranoico·a, esto lo confirma", de: "Schon paranoid, das bestätigt es nur", it: "Già paranoico·a, lo conferma", da: "Allerede paranoid, det bekræfter det bare", bg: "И без това параноик, само го потвърждава", tr: "Zaten paranoyak, sadece doğruluyor" }, next: "tools", reaction: { en: "Janet would say: paranoid is just well-informed, early.", fr: "Janet dirait : être parano, c'est juste être bien informé·e à l'avance.", es: "Janet diría: ser paranoico·a es estar bien informado·a por adelantado.", de: "Janet würde sagen: paranoid ist nur gut informiert, früher als andere.", it: "Janet direbbe: essere paranoico·a è essere ben informato·a in anticipo.", da: "Janet ville sige: paranoid er bare velinformeret tidligt.", bg: "Janet би казала: параноик е просто добре информиран по-рано.", tr: "Janet derdi ki: paranoyak, sadece erken iyi bilgilendirilmiş demek." } }
      ]
    },
    tools: {
      bot: [
        { en: "Janet's recommended fact-check shelf:", fr: "Les outils que Janet recommande pour faire le tri :", es: "Las herramientas que Janet recomienda para verificar:", de: "Janets empfohlene Werkzeuge zum Faktencheck:", it: "Gli strumenti che Janet consiglia per verificare:", da: "Janets anbefalede værktøjer til faktatjek:", bg: "Инструментите, които Janet препоръчва за проверка:", tr: "Janet'in doğrulama için önerdiği araçlar:" },
        { en: "🔍 *Snopes* — old and reliable, covers urban legends and viral claims.", fr: "🔍 *Snopes* — vieux et fiable, couvre les légendes urbaines et les contenus viraux.", es: "🔍 *Snopes* — antiguo y fiable, cubre leyendas urbanas y bulos virales.", de: "🔍 *Snopes* — alt und zuverlässig, deckt Urban Legends und virale Behauptungen ab.", it: "🔍 *Snopes* — vecchio e affidabile, copre leggende urbane e bufale virali.", da: "🔍 *Snopes* — gammel og pålidelig, dækker vandrehistorier og virale påstande.", bg: "🔍 *Snopes* — стар и надежден, покрива градски легенди и вирусни твърдения.", tr: "🔍 *Snopes* — eski ve güvenilir, şehir efsanelerini ve viral iddiaları kapsar." },
        { en: "📰 *FactCheck.org* and *PolitiFact* — solid on political claims.", fr: "📰 *FactCheck.org* et *PolitiFact* — solides sur les affirmations politiques.", es: "📰 *FactCheck.org* y *PolitiFact* — sólidos en afirmaciones políticas.", de: "📰 *FactCheck.org* und *PolitiFact* — solide bei politischen Behauptungen.", it: "📰 *FactCheck.org* e *PolitiFact* — solidi sulle affermazioni politiche.", da: "📰 *FactCheck.org* og *PolitiFact* — solide på politiske påstande.", bg: "📰 *FactCheck.org* и *PolitiFact* — солидни за политически твърдения.", tr: "📰 *FactCheck.org* ve *PolitiFact* — politik iddialarda sağlam." },
        { en: "🌍 Local ones too: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DA), *Factcheck.bg* (BG).", fr: "🌍 Locaux aussi : *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", es: "🌍 También locales: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", de: "🌍 Auch lokal: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", it: "🌍 Anche locali: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", da: "🌍 Også lokale: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", bg: "🌍 И локални: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", tr: "🌍 Yerel olanlar da var: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG)." },
        { en: "🛠️ *InVID WeVerify* — a free browser extension built for digging into images and videos. Janet adores it.", fr: "🛠️ *InVID WeVerify* — une extension de navigateur gratuite faite pour fouiller images et vidéos. Janet l'adore.", es: "🛠️ *InVID WeVerify* — una extensión de navegador gratuita pensada para examinar imágenes y vídeos. Janet la adora.", de: "🛠️ *InVID WeVerify* — eine kostenlose Browser-Erweiterung, gebaut, um Bilder und Videos zu durchleuchten. Janet liebt sie.", it: "🛠️ *InVID WeVerify* — un'estensione del browser gratuita per scavare in immagini e video. Janet la adora.", da: "🛠️ *InVID WeVerify* — en gratis browserudvidelse bygget til at grave i billeder og videoer. Janet elsker den.", bg: "🛠️ *InVID WeVerify* — безплатно разширение за браузър, направено да рови в снимки и видеа. Janet го обожава.", tr: "🛠️ *InVID WeVerify* — görseller ve videolar üzerinde derinlemesine inceleme yapmak için tasarlanmış ücretsiz bir tarayıcı eklentisi. Janet ona bayılıyor." }
      ],
      next: "outro"
    },
    outro: {
      bot: [
        { en: "Final Janet thought: skepticism is, factually, a form of kindness.", fr: "Dernière pensée de Janet : le scepticisme, factuellement, c'est une forme de gentillesse.", es: "Último pensamiento de Janet: el escepticismo es, factualmente, una forma de amabilidad.", de: "Letzter Janet-Gedanke: Skepsis ist, faktisch, eine Form von Freundlichkeit.", it: "Pensiero finale di Janet: lo scetticismo è, fattualmente, una forma di gentilezza.", da: "Sidste Janet-tanke: skepsis er, faktuelt, en form for venlighed.", bg: "Последна мисъл от Janet: скептицизмът е, технически, форма на доброта.", tr: "Janet'ten son bir düşünce: şüphecilik, fiilen, bir tür naziklik biçimidir." },
        { en: "When you don't share something false, you spare someone's parent from a panic. And you save the truth a tiny bit of erosion.", fr: "Quand tu ne partages pas une info fausse, tu épargnes une crise de panique au parent de quelqu'un. Et tu épargnes à la vérité un petit grain d'érosion.", es: "Cuando no compartes algo falso, le ahorras un susto al padre o madre de alguien. Y le ahorras a la verdad un poquito de erosión.", de: "Wenn du etwas Falsches nicht teilst, ersparst du den Eltern von jemandem eine Panikattacke. Und du ersparst der Wahrheit ein winziges bisschen Erosion.", it: "Quando non condividi qualcosa di falso, risparmi una crisi al genitore di qualcuno. E risparmi alla verità un pizzico di erosione.", da: "Når du ikke deler noget falsk, sparer du nogens forælder for en panik. Og du sparer sandheden for en lille smule erosion.", bg: "Когато не споделиш нещо невярно, спестяваш паника на нечий родител. И спестяваш на истината мъничко ерозия.", tr: "Yanlış bir şeyi paylaşmadığında, birinin ebeveynini panikten kurtarırsın. Ve gerçeği küçücük bir aşınmadan kurtarırsın." },
        { en: "Bye for now! 🥣", fr: "À très vite ! 🥣", es: "¡Hasta luego! 🥣", de: "Bis bald! 🥣", it: "A presto! 🥣", da: "Vi ses! 🥣", bg: "До скоро! 🥣", tr: "Şimdilik hoşça kal! 🥣" }
      ],
      end: true
    }
  }
};
