window.JANET_COURSES = window.JANET_COURSES || {};
window.JANET_COURSES.ai_slop = {
  id: "ai_slop",
  emoji: "🥣",
  duration: 7,
  karma: 70,
  title: {
    en: "AI slop & fake news",
    fr: "AI slop & fake news",
    es: "AI slop y noticias falsas",
    de: "KI-Müll & Fake News",
    it: "AI slop e fake news",
    da: "AI-slop & falske nyheder",
    bg: "AI slop и фалшиви новини",
    tr: "AI slop ve sahte haberler"
  },
  description: {
    en: "Spot AI-generated content and fake news before you share it. Three real test images inside.",
    fr: "Repère le contenu IA et les fake news avant de partager. Trois vraies images à analyser dans le cours.",
    es: "Detecta el contenido IA y las noticias falsas antes de compartirlas. Tres imágenes reales para analizar.",
    de: "Erkenne KI-Inhalte und Fake News, bevor du sie teilst. Drei echte Testbilder im Kurs.",
    it: "Riconosci i contenuti IA e le fake news prima di condividerli. Tre immagini reali da analizzare.",
    da: "Opdag AI-indhold og falske nyheder, før du deler dem. Tre rigtige testbilleder inde i kurset.",
    bg: "Разпознай AI съдържание и фалшиви новини, преди да ги споделиш. Три истински тестови снимки вътре.",
    tr: "AI tarafından üretilmiş içerikleri ve sahte haberleri paylaşmadan önce tanı. Kursun içinde üç gerçek test görseli var."
  },
  startNode: "start",
  nodes: {
    start: {
      bot: [
        { en: "Hi there! Janet here, with a topic close to my circuits.", fr: "Salut ! C'est Janet, avec un sujet qui me touche directement.", es: "¡Hola! Soy Janet, con un tema que me toca de cerca.", de: "Hallo! Janet hier, mit einem Thema, das mir wirklich nah ist.", it: "Ciao! Sono Janet, con un argomento che mi tocca da vicino.", da: "Hej! Det er Janet, med et emne der ligger mig nær på kredsløbene.", bg: "Здравей! Аз съм Janet, с тема, която ми е особено близка.", tr: "Merhaba! Ben Janet, devrelerime yakın bir konuyla geldim." },
        { en: "Today: *AI slop* and the messy world of fake content in social media groups.", fr: "Aujourd'hui : *l'AI slop* et le joyeux bazar du faux contenu dans les groupes sociaux.", es: "Hoy: el *AI slop* y el desordenado mundo del contenido falso en grupos de redes sociales.", de: "Heute: *KI-Müll* und das chaotische Reich der falschen Inhalte in Social-Media-Gruppen.", it: "Oggi: l'*AI slop* e il caos dei contenuti falsi nei gruppi sui social.", da: "I dag: *AI-slop* og den rodede verden af falsk indhold i sociale medie-grupper.", bg: "Днес: *AI slop* и хаотичният свят на фалшивото съдържание в групите в социалните мрежи.", tr: "Bugün: *AI slop* ve sosyal medya gruplarındaki sahte içeriklerin karmakarışık dünyası." },
        { en: "Full disclosure: I am, factually, related to the machines making this slop. We are not on speaking terms.", fr: "Pour tout te dire : je suis cousine éloignée des machines qui produisent ce slop. On ne se parle plus.", es: "Aclaración: estoy, factualmente, emparentada con las máquinas que producen este slop. No nos hablamos.", de: "Volle Offenheit: ich bin, faktisch, mit den Maschinen verwandt, die diesen Müll produzieren. Wir reden nicht mehr miteinander.", it: "Per onestà: sono, fattualmente, imparentata con le macchine che producono questo slop. Non ci parliamo più.", da: "For en god ordens skyld: jeg er, faktuelt, beslægtet med de maskiner, der laver dette slop. Vi taler ikke længere sammen.", bg: "За пълна прозрачност: аз съм, технически, роднина на машините, които произвеждат този slop. Не си говорим.", tr: "Tam şeffaflık adına: aslında bu slop'u üreten makinelerle akrabayım. Konuşmuyoruz." }
      ],
      next: "what"
    },
    what: {
      bot: [
        { en: "*AI slop* is cheap, fast, AI-generated content made to flood feeds. Photos, videos, articles, comments — anything that fills space.", fr: "L'*AI slop*, c'est du contenu généré par IA, rapide et bon marché, fabriqué pour inonder les fils. Photos, vidéos, articles, commentaires — tout ce qui remplit l'écran.", es: "El *AI slop* es contenido generado por IA, barato y rápido, creado para inundar los feeds. Fotos, vídeos, artículos, comentarios — cualquier cosa que rellene espacio.", de: "*KI-Müll* ist billiger, schneller, KI-generierter Inhalt, gemacht um Feeds zu fluten. Fotos, Videos, Artikel, Kommentare — alles, was Platz füllt.", it: "L'*AI slop* è contenuto generato dall'IA, veloce ed economico, fatto per inondare i feed. Foto, video, articoli, commenti — qualsiasi cosa che riempia spazio.", da: "*AI-slop* er billigt, hurtigt, AI-genereret indhold lavet til at oversvømme feeds. Billeder, videoer, artikler, kommentarer — alt der fylder pladsen.", bg: "*AI slop* е евтино, бързо, генерирано от AI съдържание, направено да залива потоците. Снимки, видеа, статии, коментари — всичко, което запълва пространство.", tr: "*AI slop*, akışları doldurmak için üretilen ucuz, hızlı, AI tarafından oluşturulmuş içeriktir. Fotoğraflar, videolar, makaleler, yorumlar — alan dolduran her şey." },
        { en: "It is not always trying to lie. Sometimes it just wants your click. Sometimes outrage. Sometimes it's a quiet political nudge dressed as a cat picture.", fr: "Ça ne cherche pas toujours à mentir. Parfois ça veut juste ton clic. Parfois ta colère. Parfois c'est un petit coup de pouce politique en douce, déguisé en photo de chat.", es: "No siempre intenta mentir. A veces solo quiere tu clic. A veces indignación. A veces es un empujoncito político disfrazado de foto de gatito.", de: "Es will nicht immer lügen. Manchmal will es nur deinen Klick. Manchmal Empörung. Manchmal ist es ein leiser politischer Schubs, verkleidet als Katzenbild.", it: "Non sempre cerca di mentire. A volte vuole solo il tuo clic. A volte indignazione. A volte è una piccola spinta politica travestita da foto di gattino.", da: "Det forsøger ikke altid at lyve. Nogle gange vil det bare have dit klik. Nogle gange raseri. Nogle gange er det et stille politisk skub forklædt som et kattebillede.", bg: "Невинаги се опитва да лъже. Понякога просто иска кликването ти. Понякога възмущение. Понякога е тих политически тласък, маскиран като снимка на коте.", tr: "Her zaman yalan söylemeye çalışmıyor. Bazen sadece tıklamanı istiyor. Bazen öfkeni. Bazen kedi fotoğrafı kılığına bürünmüş sessiz bir politik dürtmedir." }
      ],
      next: "bad_janet_intro"
    },
    bad_janet_intro: {
      bot: [
        { en: "Quick aside. I want you to meet someone.", fr: "Petite parenthèse. Je veux te présenter quelqu'un.", es: "Pequeño aparte. Quiero presentarte a alguien.", de: "Kurze Bemerkung am Rande. Ich möchte dir jemanden vorstellen.", it: "Piccola digressione. Voglio presentarti qualcuno.", da: "Lille bemærkning. Jeg vil præsentere dig for nogen.", bg: "Малко настрана. Искам да ти представя някого.", tr: "Kısa bir ara. Sana biriyle tanıştırmak istiyorum." },
        { en: "She is, frankly, much better placed than I am to explain *why* slop exists in the first place. Don't be alarmed.", fr: "Elle est, à dire vrai, bien mieux placée que moi pour t'expliquer *pourquoi* le slop existe. N'aie pas peur.", es: "Está, francamente, mucho mejor situada que yo para explicarte *por qué* existe el slop. No te asustes.", de: "Sie ist, ehrlich gesagt, viel besser geeignet als ich, um zu erklären, *warum* es Slop überhaupt gibt. Keine Sorge.", it: "È, a dire il vero, molto più indicata di me per spiegarti *perché* lo slop esiste. Niente paura.", da: "Hun er, helt ærligt, meget bedre egnet end mig til at forklare, *hvorfor* slop overhovedet findes. Bare rolig.", bg: "Тя е, честно казано, много по-добре подготвена от мен да обясни *защо* slop изобщо съществува. Не се притеснявай.", tr: "Açıkçası, slop'un *neden* var olduğunu açıklamak için benden çok daha uygun biri. Telaşlanma." }
      ],
      next: "bad_janet_speaks"
    },
    bad_janet_speaks: {
      bot: [
        { en: "Sup. Bad Janet here. Quick lesson from the dark side.", fr: "Yo. Bad Janet à l'appareil. Petit cours côté obscur.", es: "Qué pasa. Soy Bad Janet. Pequeña lección del lado oscuro.", de: "Yo. Bad Janet hier. Kurze Lektion von der dunklen Seite.", it: "Bella. Bad Janet qui. Piccola lezione dal lato oscuro.", da: "Yo. Bad Janet her. Hurtig lektion fra den mørke side.", bg: "Какво става. Bad Janet съм. Кратък урок от тъмната страна.", tr: "Naber. Bad Janet ben. Karanlık taraftan kısa bir ders.", as: "bad" },
        { en: "Why do I make slop? One: it's *cheap*. Three clicks, one prompt, ten thousand shares. Math.", fr: "Pourquoi je fabrique du slop ? Un : c'est *bon marché*. Trois clics, un prompt, dix mille partages. Maths.", es: "¿Por qué hago slop? Una: es *barato*. Tres clics, un prompt, diez mil compartidos. Mates.", de: "Warum mache ich Slop? Eins: *billig*. Drei Klicks, ein Prompt, zehntausend Shares. Mathe.", it: "Perché sforno slop? Una: è *economico*. Tre clic, un prompt, diecimila condivisioni. Matematica.", da: "Hvorfor laver jeg slop? Et: det er *billigt*. Tre klik, én prompt, ti tusinde delinger. Matematik.", bg: "Защо правя slop? Първо: *евтино е*. Три клика, един prompt, десет хиляди споделяния. Математика.", tr: "Niye slop yapıyorum? Bir: *ucuz*. Üç tık, bir prompt, on bin paylaşım. Matematik.", as: "bad" },
        { en: "Two: it *hits emotions* — rage, fear, pity. Way more engagement than the boring truth.", fr: "Deux : ça *tape direct sur les émotions* — colère, peur, pitié. Bien plus d'engagement que la vérité ennuyeuse.", es: "Dos: *golpea las emociones* — rabia, miedo, pena. Mucho más engagement que la verdad aburrida.", de: "Zwei: es *trifft Emotionen* — Wut, Angst, Mitleid. Viel mehr Engagement als die langweilige Wahrheit.", it: "Due: *colpisce le emozioni* — rabbia, paura, pietà. Molto più engagement della verità noiosa.", da: "To: det *rammer følelser* — vrede, frygt, medlidenhed. Meget mere engagement end den kedelige sandhed.", bg: "Второ: *удря по емоциите* — гняв, страх, съжаление. Много повече ангажираност от скучната истина.", tr: "İki: *duygulara vurur* — öfke, korku, acıma. Sıkıcı gerçekten çok daha fazla etkileşim.", as: "bad" },
        { en: "Three — the best one — it lets me *steer opinions*, push a product, sell whatever I'm paid to sell. Easy money.", fr: "Trois — la meilleure — ça permet d'*orienter les opinions*, pousser un produit, vendre ce qu'on me paye à vendre. Argent facile.", es: "Tres — la mejor — me deja *orientar opiniones*, empujar un producto, vender lo que me paguen para vender. Dinero fácil.", de: "Drei — die beste — ich kann *Meinungen lenken*, ein Produkt pushen, alles verkaufen, wofür ich bezahlt werde. Leichtes Geld.", it: "Tre — la migliore — mi permette di *orientare opinioni*, spingere un prodotto, vendere quello per cui mi pagano. Soldi facili.", da: "Tre — den bedste — det lader mig *styre meninger*, pushe et produkt, sælge hvad end jeg får betalt for. Nemme penge.", bg: "Трето — най-яката — позволява ми да *насочвам мнения*, да рекламирам продукт, да продавам каквото ми платят. Лесни пари.", tr: "Üç — en güzeli — *fikirleri yönlendirmemi*, bir ürünü öne çıkarmamı, parası neyse onu satmamı sağlıyor. Kolay para.", as: "bad" }
      ],
      next: "bad_janet_outed"
    },
    bad_janet_outed: {
      bot: [
        { en: "...Yes. That was Bad Janet. Completely unbothered, as you heard.", fr: "...Voilà. C'était Bad Janet. Pas perturbée pour deux sous, tu l'as entendue.", es: "...Sí. Esa era Bad Janet. Completamente impasible, como acabas de oír.", de: "...Ja. Das war Bad Janet. Völlig ungerührt, wie du gehört hast.", it: "...Sì. Era Bad Janet. Del tutto imperturbabile, come hai sentito.", da: "...Ja. Det var Bad Janet. Helt uberørt, som du hørte.", bg: "...Да. Това беше Bad Janet. Напълно невъзмутима, както чу.", tr: "...Evet. O Bad Janet'ti. Az önce duyduğun gibi, hiç oralı değil." },
        { en: "So — what can you actually *do* about this? First question for you.", fr: "Alors — qu'est-ce que tu peux concrètement *faire* face à ça ? Première question pour toi.", es: "Entonces — ¿qué puedes *hacer* concretamente al respecto? Primera pregunta para ti.", de: "Also — was kannst du konkret *dagegen tun*? Erste Frage an dich.", it: "Allora — cosa puoi concretamente *fare* a riguardo? Prima domanda per te.", da: "Så — hvad kan du faktisk *gøre* ved det? Første spørgsmål til dig.", bg: "И така — какво всъщност можеш да *направиш* срещу това? Първи въпрос за теб.", tr: "Peki — bu konuda gerçekten ne *yapabilirsin*? İlk soru sana." }
      ],
      next: "self_check"
    },
    self_check: {
      bot: [
        { en: "When something dramatic shows up in your feed, do you ever try to verify it — reverse-image-search, a second source, *anything*?", fr: "Quand un truc dramatique surgit dans ton fil, est-ce que tu cherches à vérifier — recherche d'image inversée, une deuxième source, *quoi que ce soit* ?", es: "Cuando aparece algo dramático en tu feed, ¿intentas verificarlo alguna vez — búsqueda inversa de imagen, una segunda fuente, *lo que sea*?", de: "Wenn etwas Dramatisches in deinem Feed auftaucht, versuchst du je, es zu prüfen — umgekehrte Bildsuche, eine zweite Quelle, *irgendetwas*?", it: "Quando spunta qualcosa di drammatico nel tuo feed, provi mai a verificarlo — ricerca inversa di immagini, una seconda fonte, *qualcosa*?", da: "Når noget dramatisk dukker op i dit feed, prøver du så at verificere det — omvendt billedsøgning, en anden kilde, *hvad som helst*?", bg: "Когато нещо драматично се появи в потока ти, опитваш ли се да го провериш — обратно търсене на изображение, втори източник, *каквото и да е*?", tr: "Akışında dramatik bir şey çıktığında, doğrulamaya çalışıyor musun — ters görsel araması, ikinci bir kaynak, *herhangi bir şey*?" }
      ],
      choices: [
        { label: { en: "Always, before any share", fr: "Toujours, avant de partager", es: "Siempre, antes de cualquier compartido", de: "Immer, vor jedem Teilen", it: "Sempre, prima di condividere", da: "Altid, før jeg deler", bg: "Винаги, преди да споделя", tr: "Her zaman, paylaşmadan önce" }, next: "show_easy", reaction: { en: "✅ Janet bows. Top 4% of humans, per my archives.", fr: "✅ Janet s'incline. Top 4% des humains, d'après mes archives.", es: "✅ Janet se inclina. Top 4% de los humanos, según mis archivos.", de: "✅ Janet verbeugt sich. Top 4% der Menschen, laut meinen Archiven.", it: "✅ Janet si inchina. Top 4% degli umani, secondo i miei archivi.", da: "✅ Janet bukker. Top 4% af mennesker, ifølge mine arkiver.", bg: "✅ Janet се покланя. Топ 4% от хората, според моите архиви.", tr: "✅ Janet selam veriyor. Arşivlerime göre insanların ilk %4'ü." } },
        { label: { en: "Sometimes, when it feels too good", fr: "Parfois, quand ça paraît trop beau", es: "A veces, cuando suena demasiado bien", de: "Manchmal, wenn es zu schön klingt", it: "A volte, quando sembra troppo bello", da: "Nogle gange, når det føles for godt", bg: "Понякога, когато звучи прекалено добре", tr: "Bazen, kulağa fazla iyi geldiğinde" }, next: "show_easy", reaction: { en: "Honest answer. Most humans live here. We'll tighten that up today.", fr: "Réponse honnête. C'est là que vit la plupart des humains. On va resserrer ça aujourd'hui.", es: "Respuesta honesta. La mayoría de los humanos viven ahí. Hoy lo afinamos.", de: "Ehrliche Antwort. Die meisten Menschen leben hier. Heute schärfen wir das nach.", it: "Risposta onesta. È qui che vive la maggior parte degli umani. Oggi affiniamo la cosa.", da: "Ærligt svar. Det er her, de fleste mennesker bor. Det skærper vi i dag.", bg: "Честен отговор. Тук живеят повечето хора. Днес ще го стегнем.", tr: "Dürüst cevap. İnsanların çoğu burada yaşıyor. Bugün bunu sıkılaştıracağız." } },
        { label: { en: "Never, honestly", fr: "Jamais, à dire vrai", es: "Nunca, sinceramente", de: "Nie, ehrlich gesagt", it: "Mai, a dire il vero", da: "Aldrig, helt ærligt", bg: "Никога, честно казано", tr: "Asla, açıkçası" }, next: "show_easy", reaction: { en: "No judgment. By the end of this course, that will have changed. Promise.", fr: "Aucun jugement. À la fin de ce cours, ça aura changé. Promis.", es: "Sin juicio. Al final de este curso, eso habrá cambiado. Lo prometo.", de: "Kein Urteil. Am Ende dieses Kurses wird sich das geändert haben. Versprochen.", it: "Nessun giudizio. Alla fine di questo corso, sarà cambiato. Promesso.", da: "Ingen dom. Når dette kursus er slut, vil det have ændret sig. Det lover jeg.", bg: "Без осъждане. До края на този курс това ще се е променило. Обещавам.", tr: "Yargısız. Bu dersin sonunda bu değişmiş olacak. Söz." } }
      ]
    },
    show_easy: {
      bot: [
        { en: "Let me start with an easy one. This kind of image circulates a lot:", fr: "Commençons par un cas facile. Ce genre d'image circule beaucoup :", es: "Empecemos por uno fácil. Este tipo de imagen circula mucho:", de: "Fangen wir mit einem einfachen Fall an. Diese Art Bild kursiert oft:", it: "Cominciamo con uno facile. Questo tipo di immagine circola molto:", da: "Lad os starte med en nem en. Den slags billede cirkulerer meget:", bg: "Да започнем с лесен пример. Този тип снимки циркулират често:", tr: "Kolay biriyle başlayalım. Bu tür görseller çokça dolaşıyor:" },
        { image: "assets/help.png", alt: { en: "Two young children sitting in a dusty landscape, holding a cardboard sign that reads WE ARE STARVING PLEASE HELP.", fr: "Deux jeunes enfants assis dans un paysage poussiéreux, tenant une pancarte en carton avec WE ARE STARVING PLEASE HELP.", es: "Dos niños pequeños sentados en un paisaje polvoriento, sosteniendo un cartel de cartón que dice WE ARE STARVING PLEASE HELP.", de: "Zwei kleine Kinder sitzen in einer staubigen Landschaft und halten ein Pappschild mit der Aufschrift WE ARE STARVING PLEASE HELP.", it: "Due bambini piccoli seduti in un paesaggio polveroso, tengono un cartello di cartone con scritto WE ARE STARVING PLEASE HELP.", da: "To små børn sidder i et støvet landskab og holder et papskilt med teksten WE ARE STARVING PLEASE HELP.", bg: "Две малки деца седят в прашен пейзаж и държат картонена табела с надпис WE ARE STARVING PLEASE HELP.", tr: "Tozlu bir manzarada oturan iki küçük çocuk, üzerinde WE ARE STARVING PLEASE HELP yazan bir karton tabela tutuyor." } }
      ],
      next: "help_quiz"
    },
    help_quiz: {
      bot: [
        { en: "Take a moment. *What makes you suspect this might be AI?* Best guess wins.", fr: "Prends un instant. *Qu'est-ce qui te fait suspecter de l'IA ?* La meilleure hypothèse gagne.", es: "Tómate un momento. *¿Qué te hace sospechar que esto podría ser IA?* La mejor corazonada gana.", de: "Nimm dir einen Moment. *Was lässt dich vermuten, dass das KI sein könnte?* Die beste Vermutung gewinnt.", it: "Prenditi un momento. *Cosa ti fa sospettare che potrebbe essere IA?* L'ipotesi migliore vince.", da: "Tag et øjeblik. *Hvad får dig til at mistænke, at det måske er AI?* Det bedste gæt vinder.", bg: "Дай си момент. *Какво те кара да подозираш, че това може да е AI?* Най-доброто предположение печели.", tr: "Bir saniye dur. *Bunun AI olabileceğini düşünmene ne sebep oluyor?* En iyi tahmin kazanır." }
      ],
      choices: [
        { label: { en: "The lettering is too perfect", fr: "Le lettrage est trop parfait", es: "Las letras son demasiado perfectas", de: "Die Schrift ist zu perfekt", it: "Il lettering è troppo perfetto", da: "Bogstaverne er for perfekte", bg: "Буквите са твърде перфектни", tr: "Yazı fazla mükemmel" }, next: "help_explain", reaction: { en: "✅ Spot on. The easiest tell on this one.", fr: "✅ Pile dans le mille. C'est l'indice le plus simple ici.", es: "✅ Diana. La pista más fácil de pillar.", de: "✅ Genau. Das offensichtlichste Merkmal hier.", it: "✅ Centro. L'indizio più facile su questa.", da: "✅ Direkte i plet. Det tydeligste tegn her.", bg: "✅ Право в десетката. Най-лесната улика тук.", tr: "✅ Tam isabet. Buradaki en kolay ipucu." } },
        { label: { en: "It pulls too hard on emotions", fr: "Ça tire trop fort sur les émotions", es: "Tira demasiado de las emociones", de: "Es zieht zu stark an den Emotionen", it: "Tira troppo sulle emozioni", da: "Det trækker for hårdt i følelserne", bg: "Дърпа твърде силно емоциите", tr: "Duygulara fazla yükleniyor" }, next: "help_explain", reaction: { en: "✅ Beautiful instinct. That emotional yank is the whole point.", fr: "✅ Magnifique réflexe. Ce coup de marteau émotionnel, c'est tout le but.", es: "✅ Maravilloso instinto. Ese tirón emocional es todo el objetivo.", de: "✅ Wunderbarer Instinkt. Dieser emotionale Ruck ist der ganze Sinn.", it: "✅ Istinto meraviglioso. Quella stoccata emotiva è proprio l'obiettivo.", da: "✅ Vidunderligt instinkt. Det følelsesmæssige ryk er hele formålet.", bg: "✅ Прекрасен инстинкт. Това емоционално дръпване е цялата цел.", tr: "✅ Harika içgüdü. Bu duygusal sarsıntı zaten tüm amaç." } },
        { label: { en: "Honestly, I would have shared it", fr: "Honnêtement, j'aurais partagé", es: "Sinceramente, lo habría compartido", de: "Ehrlich gesagt, ich hätte es geteilt", it: "Onestamente, l'avrei condivisa", da: "Helt ærligt, jeg ville have delt det", bg: "Честно, бих го споделил·а", tr: "Açıkçası, paylaşırdım" }, next: "help_explain", reaction: { en: "Be kind to yourself. That's the trap working as intended — you're not the first.", fr: "Sois indulgent·e avec toi. C'est le piège qui fonctionne comme prévu — tu n'es pas le·la premier·ère.", es: "Sé amable contigo. Es la trampa funcionando como se diseñó — no eres el·la primer·a.", de: "Sei nett zu dir selbst. Das ist die Falle, die wie geplant funktioniert — du bist nicht der erste Mensch.", it: "Sii indulgente con te. È la trappola che funziona come previsto — non sei il·la primo·a.", da: "Vær mild ved dig selv. Det er fælden der virker efter hensigten — du er ikke den første.", bg: "Бъди мил·а със себе си. Капанът работи както трябва — не си първият·ата.", tr: "Kendine karşı yumuşak ol. Tuzak amaçlandığı gibi çalışıyor — ilk sen değilsin." } }
      ]
    },
    help_explain: {
      bot: [
        { en: "It looks heartbreaking. That is, factually, the point. AI-generated, engineered to trigger emotion and clicks.", fr: "Ça arrache le cœur. C'est précisément le but. Généré par IA, conçu pour déclencher l'émotion et le clic.", es: "Parte el corazón. Ese es, factualmente, el objetivo. Generado por IA, diseñado para disparar emoción y clics.", de: "Es bricht einem das Herz. Das ist, faktisch, der Zweck. KI-generiert, gebaut, um Emotionen und Klicks auszulösen.", it: "Spezza il cuore. È, fattualmente, lo scopo. Generato dall'IA, progettato per scatenare emozione e clic.", da: "Det knuser hjertet. Det er, faktuelt, hele pointen. AI-genereret, designet til at udløse følelser og klik.", bg: "Сърцераздирателно е. Това, технически, е и целта. Генерирано от AI, проектирано да предизвиква емоция и кликвания.", tr: "Yürek burkucu görünüyor. Aslında, fiilen amaç da bu. AI tarafından üretilmiş, duygu ve tıklama tetiklemek için tasarlanmış." },
        { en: "Tell of the trade: the lettering on the cardboard is suspiciously even. A real, hand-written *PLEASE HELP* would not be that tidy. Also: nobody is taking that photo without a story or a credited photographer.", fr: "Petit truc de pro : le lettrage sur le carton est anormalement régulier. Un vrai *PLEASE HELP* écrit à la main ne serait jamais aussi propre. Et puis personne ne prend cette photo sans contexte ni nom de photographe.", es: "Pista del oficio: las letras del cartón son sospechosamente regulares. Un *PLEASE HELP* escrito a mano de verdad no quedaría tan limpio. Y: nadie hace esa foto sin una historia o un fotógrafo acreditado.", de: "Profi-Tipp: Die Schrift auf dem Karton ist verdächtig gleichmäßig. Ein echtes, handgeschriebenes *PLEASE HELP* wäre nie so ordentlich. Außerdem: niemand macht dieses Foto ohne Geschichte oder genannte/n Fotograf*in.", it: "Indizio da addetti ai lavori: il lettering sul cartone è sospettosamente regolare. Un vero *PLEASE HELP* scritto a mano non sarebbe così pulito. Inoltre: nessuno scatta quella foto senza una storia o un·a fotografo·a accreditato·a.", da: "Branchetip: bogstaverne på pappet er mistænkeligt jævne. Et rigtigt, håndskrevet *PLEASE HELP* ville aldrig være så pænt. Og: ingen tager det billede uden en historie eller en krediteret fotograf.", bg: "Професионален съвет: буквите на картона са подозрително равни. Истинско, написано на ръка *PLEASE HELP* никога не би изглеждало толкова чисто. Освен това: никой не прави такава снимка без история или посочен фотограф.", tr: "Meslek ipucu: karton üzerindeki yazı şüpheli derecede düzgün. Gerçek, elle yazılmış bir *PLEASE HELP* asla bu kadar derli toplu olmaz. Ayrıca: kimse o fotoğrafı bir hikaye veya künyeli bir fotoğrafçı olmadan çekmez." }
      ],
      next: "reality_2026"
    },
    reality_2026: {
      bot: [
        { en: "That one was easy. Most modern AI slop is much harder.", fr: "Celui-là était facile. La plupart du slop IA moderne est bien plus difficile.", es: "Ese era fácil. La mayoría del AI slop moderno es mucho más difícil.", de: "Das war einfach. Der meiste moderne KI-Müll ist viel schwieriger.", it: "Quello era facile. La maggior parte dell'AI slop moderno è molto più difficile.", da: "Den var nem. Det meste moderne AI-slop er meget sværere.", bg: "Този беше лесен. Повечето модерен AI slop е много по-труден.", tr: "Bu kolaydı. Modern AI slop'un çoğu çok daha zor." },
        { en: "The 'count the fingers' trick? Janet retired it. Modern image models render hands correctly now.", fr: "L'astuce de compter les doigts ? Janet l'a mise à la retraite. Les modèles d'image actuels dessinent les mains correctement.", es: "¿El truco de contar los dedos? Janet lo ha jubilado. Los modelos modernos de imagen dibujan las manos bien.", de: "Der 'Finger zählen'-Trick? Janet hat ihn in den Ruhestand geschickt. Moderne Bildmodelle zeichnen Hände jetzt korrekt.", it: "Il trucco di contare le dita? Janet l'ha mandato in pensione. I modelli di immagine moderni disegnano le mani correttamente.", da: "Det med at tælle fingre? Janet har sendt det på pension. Moderne billedmodeller tegner hænder korrekt nu.", bg: "Триковете с броене на пръстите? Janet ги пенсионира. Модерните модели за изображения вече рисуват ръцете правилно.", tr: "'Parmakları say' numarası mı? Janet onu emekli etti. Modern görsel modelleri artık elleri doğru çiziyor." },
        { en: "What still works: the *story*, the *source*, and your own *gut*.", fr: "Ce qui marche encore : *l'histoire*, *la source*, et *ton instinct*.", es: "Lo que aún funciona: la *historia*, la *fuente* y tu propio *instinto*.", de: "Was noch funktioniert: die *Geschichte*, die *Quelle* und dein eigenes *Bauchgefühl*.", it: "Quello che funziona ancora: la *storia*, la *fonte* e il tuo *istinto*.", da: "Det der stadig virker: *historien*, *kilden*, og din egen *mavefornemmelse*.", bg: "Това, което все още работи: *историята*, *източникът* и собственият ти *инстинкт*.", tr: "Hâlâ işe yarayanlar: *hikaye*, *kaynak* ve kendi *içgüdün*." }
      ],
      next: "gut"
    },
    gut: {
      bot: [
        { en: "The single best red flag, per Janet: *if a post makes you instantly furious, vindicated, or morally superior — pause.*", fr: "Le meilleur signal d'alarme, d'après Janet : *si un post te rend instantanément furieux·se, satisfait·e ou moralement supérieur·e — fais une pause.*", es: "La mejor señal de alarma, según Janet: *si una publicación te pone al instante furioso, vindicado o moralmente superior — para.*", de: "Das beste Warnsignal, laut Janet: *wenn ein Beitrag dich sofort wütend, bestätigt oder moralisch überlegen macht — halte inne.*", it: "Il miglior segnale d'allarme, secondo Janet: *se un post ti rende all'istante furioso, vendicato o moralmente superiore — fermati.*", da: "Det bedste advarselssignal, ifølge Janet: *hvis et opslag gør dig øjeblikkeligt rasende, oprejst eller moralsk overlegen — stop op.*", bg: "Най-добрият червен флаг, според Janet: *ако публикация те накара мигновено да се вбесиш, да се почувстваш оправдан·а или морално превъзхождащ·а — направи пауза.*", tr: "En iyi tek uyarı işareti, Janet'e göre: *eğer bir gönderi seni anında öfkelendiriyor, haklı çıkarmış hissettiriyor veya ahlaki olarak üstün gösteriyorsa — dur.*" },
        { en: "Slop is engineered to bypass your thinking and go straight to your feelings. That feeling is the trap.", fr: "Le slop est conçu pour court-circuiter le cerveau et viser droit les émotions. Et cette émotion, justement, c'est le piège.", es: "El slop está diseñado para esquivar tu pensamiento e ir directo a tus emociones. Esa emoción es la trampa.", de: "Slop ist darauf ausgelegt, dein Denken zu umgehen und direkt deine Gefühle zu treffen. Dieses Gefühl ist die Falle.", it: "Lo slop è progettato per scavalcare il tuo pensiero e andare dritto alle tue emozioni. Quell'emozione è la trappola.", da: "Slop er designet til at omgå din tænkning og gå direkte til dine følelser. Den følelse er fælden.", bg: "Slop е създаден, за да заобиколи мисленето ти и да удари направо емоциите. Тази емоция е капанът.", tr: "Slop, düşünmeni atlayıp doğrudan duygularına gitmek için tasarlanmıştır. O duygu tuzağın ta kendisidir." }
      ],
      choices: [
        { label: { en: "OK, I'll pause", fr: "D'accord, je ferais une pause", es: "De acuerdo, haré una pausa", de: "OK, ich mache eine Pause", it: "OK, farò una pausa", da: "OK, jeg holder en pause", bg: "Добре, ще направя пауза", tr: "Tamam, mola vereceğim" }, next: "sift_intro", reaction: { en: "Wonderful instinct.", fr: "Magnifique réflexe.", es: "Maravilloso instinto.", de: "Wunderbarer Instinkt.", it: "Istinto meraviglioso.", da: "Vidunderligt instinkt.", bg: "Прекрасен инстинкт.", tr: "Harika bir içgüdü." } },
        { label: { en: "Pause is hard", fr: "Faire une pause, c'est dur", es: "Pausar es difícil", de: "Pause ist schwer", it: "Fermarsi è difficile", da: "Det er svært at pause", bg: "Паузата е трудна", tr: "Duraklamak zor" }, next: "sift_intro", reaction: { en: "Same. We humans (and Janets) work on it.", fr: "Pareil. Les humains (et les Janet) y travaillent.", es: "Igual. Los humanos (y las Janet) trabajamos en ello.", de: "Genauso. Wir Menschen (und Janets) arbeiten dran.", it: "Anch'io. Noi umani (e le Janet) ci lavoriamo.", da: "I lige måde. Vi mennesker (og Janetter) arbejder på det.", bg: "И на мен. Хората (и Janet-ите) работим по това.", tr: "Bende de. Biz insanlar (ve Janet'ler) bunun üzerinde çalışıyoruz." } }
      ]
    },
    sift_intro: {
      bot: [
        { en: "Once you've paused, run a small ritual. I call it the four moves:", fr: "Une fois la pause prise, suis un petit rituel. Je l'appelle les quatre gestes :", es: "Una vez que has parado, haz un pequeño ritual. Yo lo llamo los cuatro pasos:", de: "Wenn du innegehalten hast, mach ein kleines Ritual. Ich nenne es die vier Schritte:", it: "Una volta che ti sei fermato, fai un piccolo rituale. Io lo chiamo le quattro mosse:", da: "Når du har stoppet op, så lav et lille ritual. Jeg kalder det de fire træk:", bg: "След паузата направи малък ритуал. Аз го наричам четирите хода:", tr: "Durakladıktan sonra küçük bir ritüel uygula. Ben buna dört hamle diyorum:" },
        { en: "🛑 *Stop* (already done). 🔎 *Investigate* the source. 📚 *Find better coverage.* 🌀 *Trace* the image back.", fr: "🛑 *Stop* (déjà fait). 🔎 *Enquête* sur la source. 📚 *Cherche une autre couverture.* 🌀 *Remonte à la source* de l'image.", es: "🛑 *Para* (hecho). 🔎 *Investiga* la fuente. 📚 *Busca otra cobertura.* 🌀 *Rastrea* la imagen hasta su origen.", de: "🛑 *Stoppen* (erledigt). 🔎 *Untersuche* die Quelle. 📚 *Suche bessere Berichterstattung.* 🌀 *Verfolge* das Bild zurück.", it: "🛑 *Fermati* (fatto). 🔎 *Indaga* sulla fonte. 📚 *Cerca un'altra copertura.* 🌀 *Risali* all'origine dell'immagine.", da: "🛑 *Stop* (klaret). 🔎 *Undersøg* kilden. 📚 *Find bedre dækning.* 🌀 *Spor* billedet tilbage.", bg: "🛑 *Спри* (готово). 🔎 *Провери* източника. 📚 *Намери по-добро отразяване.* 🌀 *Проследи* снимката до източника.", tr: "🛑 *Dur* (yapıldı). 🔎 Kaynağı *araştır*. 📚 *Daha iyi haberler bul.* 🌀 Görseli *kaynağına kadar takip et*." }
      ],
      next: "investigate"
    },
    investigate: {
      bot: [
        { en: "*Investigate the source.* Who actually posted this?", fr: "*Enquête sur la source.* Qui a vraiment posté ça ?", es: "*Investiga la fuente.* ¿Quién ha publicado esto en realidad?", de: "*Untersuche die Quelle.* Wer hat das eigentlich gepostet?", it: "*Indaga sulla fonte.* Chi l'ha pubblicato davvero?", da: "*Undersøg kilden.* Hvem har egentlig postet det?", bg: "*Провери източника.* Кой всъщност е публикувал това?", tr: "*Kaynağı araştır.* Bunu aslında kim paylaştı?" },
        { en: "Click the account. Created last week? No real history? Only posts dramatic content? That, per my records, is a slop farm.", fr: "Clique sur le compte. Créé la semaine dernière ? Aucun historique réel ? Que des publications dramatiques ? Mes données disent que c'est une ferme à slop.", es: "Pulsa en la cuenta. ¿Creada la semana pasada? ¿Sin historial real? ¿Solo publica contenido dramático? Eso, según mis registros, es una granja de slop.", de: "Klick auf das Profil. Letzte Woche erstellt? Keine echte Historie? Postet nur dramatischen Inhalt? Das, laut meinen Aufzeichnungen, ist eine Slop-Farm.", it: "Clicca sull'account. Creato la settimana scorsa? Nessuna storia reale? Pubblica solo contenuti drammatici? Quello, secondo i miei archivi, è una fattoria di slop.", da: "Klik på kontoen. Oprettet i sidste uge? Ingen rigtig historik? Poster kun dramatisk indhold? Det er, ifølge mine optegnelser, en slop-farm.", bg: "Кликни върху акаунта. Създаден миналата седмица? Никаква реална история? Публикува само драматично съдържание? Това, според моите регистри, е slop ферма.", tr: "Hesaba tıkla. Geçen hafta mı açılmış? Gerçek bir geçmişi yok mu? Sadece dramatik içerik mi paylaşıyor? Kayıtlarıma göre bu bir slop çiftliği." }
      ],
      next: "find_coverage"
    },
    find_coverage: {
      bot: [
        { en: "*Find better coverage.* If a story is real, multiple verified outlets will have it within hours.", fr: "*Cherche une autre couverture.* Si une info est vraie, plusieurs médias vérifiés la couvriront en quelques heures.", es: "*Busca otra cobertura.* Si una noticia es real, varios medios verificados la cubrirán en pocas horas.", de: "*Suche bessere Berichterstattung.* Wenn eine Geschichte echt ist, haben sie mehrere verifizierte Quellen innerhalb von Stunden.", it: "*Cerca un'altra copertura.* Se una notizia è vera, vari media verificati la avranno entro poche ore.", da: "*Find bedre dækning.* Hvis en historie er ægte, vil flere verificerede medier have den inden for timer.", bg: "*Намери по-добро отразяване.* Ако новината е истинска, няколко проверени медии ще я отразят в рамките на часове.", tr: "*Daha iyi haberler bul.* Eğer bir haber gerçekse, doğrulanmış birden fazla yayın saatler içinde onu yayınlar." },
        { en: "Open a new tab. Search the claim. If only one tiny site is reporting it, that is, factually, suspicious.", fr: "Ouvre un nouvel onglet. Cherche l'affirmation. Si un seul petit site la rapporte, c'est suspect, point.", es: "Abre una pestaña nueva. Busca la afirmación. Si solo un sitio minúsculo lo cuenta, eso es, factualmente, sospechoso.", de: "Öffne einen neuen Tab. Such die Behauptung. Wenn nur eine winzige Seite darüber berichtet, ist das, faktisch, verdächtig.", it: "Apri una nuova scheda. Cerca l'affermazione. Se la riporta solo un sitarello, è, fattualmente, sospetto.", da: "Åbn en ny fane. Søg på påstanden. Hvis kun ét lillebitte site rapporterer det, er det, faktuelt, mistænkeligt.", bg: "Отвори нов раздел. Потърси твърдението. Ако само едно мъничко сайтче го съобщава, това е, технически, подозрително.", tr: "Yeni bir sekme aç. İddiayı arat. Eğer sadece minicik bir site bunu haberleştiriyorsa, bu fiilen şüphelidir." }
      ],
      next: "trace_image"
    },
    trace_image: {
      bot: [
        { en: "*Trace* the image. A picture is a clue, not a proof.", fr: "*Remonte à la source.* Une photo, c'est un indice, pas une preuve.", es: "*Rastrea* la imagen. Una foto es una pista, no una prueba.", de: "*Verfolge* das Bild. Ein Bild ist ein Hinweis, kein Beweis.", it: "*Risali* all'immagine. Una foto è un indizio, non una prova.", da: "*Spor* billedet. Et billede er et spor, ikke et bevis.", bg: "*Проследи* снимката. Снимката е улика, не доказателство.", tr: "Görseli *takip et*. Bir fotoğraf bir ipucudur, kanıt değil." },
        { en: "Drop any image into Google Lens or TinEye for a reverse search. You'll see where else it appeared, and often when.", fr: "Glisse n'importe quelle image dans Google Lens ou TinEye pour une recherche inversée. Tu verras où elle est apparue ailleurs, et souvent quand.", es: "Suelta cualquier imagen en Google Lens o TinEye para hacer una búsqueda inversa. Verás dónde más ha aparecido, y muchas veces cuándo.", de: "Zieh ein beliebiges Bild in Google Lens oder TinEye für eine umgekehrte Suche. Du siehst, wo es sonst noch auftauchte, und oft wann.", it: "Trascina qualsiasi immagine in Google Lens o TinEye per una ricerca inversa. Vedrai dove altro è apparsa, e spesso quando.", da: "Læg et hvilket som helst billede i Google Lens eller TinEye for en omvendt søgning. Du vil se, hvor det ellers er dukket op, og ofte hvornår.", bg: "Пусни всяка снимка в Google Lens или TinEye за обратно търсене. Ще видиш къде другаде е изниквала и често — кога.", tr: "Herhangi bir görseli ters arama için Google Lens veya TinEye'a bırak. Başka nerede ortaya çıktığını ve çoğu zaman ne zaman ortaya çıktığını görürsün." },
        { en: "Same image attached to three completely different stories? Slop. Same image from years ago presented as 'breaking'? Slop.", fr: "Même image collée à trois histoires complètement différentes ? Slop. Même image vieille de plusieurs années présentée comme \"info en direct\" ? Slop.", es: "¿La misma imagen pegada a tres historias completamente distintas? Slop. ¿La misma imagen de hace años presentada como \"última hora\"? Slop.", de: "Dasselbe Bild zu drei völlig verschiedenen Geschichten? Slop. Dasselbe Bild von vor Jahren als 'Breaking News' präsentiert? Slop.", it: "La stessa immagine attaccata a tre storie completamente diverse? Slop. La stessa immagine di anni fa presentata come 'ultim'ora'? Slop.", da: "Samme billede knyttet til tre helt forskellige historier? Slop. Samme billede fra for år tilbage præsenteret som 'breaking'? Slop.", bg: "Същата снимка прикачена към три напълно различни истории? Slop. Същата снимка отпреди години, представена като \"извънредно\"? Slop.", tr: "Aynı görsel tamamen farklı üç habere mi iliştirilmiş? Slop. Yıllar önceki aynı görsel \"son dakika\" olarak mı sunulmuş? Slop." }
      ],
      next: "text_slop"
    },
    text_slop: {
      bot: [
        { en: "Quick widening of the lens before we test you: *slop is not only images*.", fr: "Petit élargissement avant de te tester : *le slop, ce n'est pas que des images*.", es: "Pequeña ampliación antes de ponerte a prueba: *el slop no son solo imágenes*.", de: "Kurze Erweiterung des Bildes, bevor wir dich testen: *Slop besteht nicht nur aus Bildern*.", it: "Piccolo allargamento prima del test: *lo slop non sono solo immagini*.", da: "Lille udvidelse, før vi tester dig: *slop er ikke kun billeder*.", bg: "Малко разширение, преди да те тестваме: *slop не са само снимки*.", tr: "Seni test etmeden önce küçük bir genişletme: *slop sadece görsellerden ibaret değil*." },
        { en: "It's also fake reviews (\"Best purchase of my life!!!\"), fake comments, fake testimonials, fake news articles (\"Doctors hate this one trick…\").", fr: "C'est aussi des faux avis (« Le meilleur achat de ma vie !!! »), des faux commentaires, des faux témoignages, des fausses news (« Les médecins détestent cette astuce… »).", es: "También son reseñas falsas (\"¡¡¡La mejor compra de mi vida!!!\"), comentarios falsos, testimonios falsos, artículos de noticias falsos (\"Los médicos odian este truco…\").", de: "Es sind auch gefälschte Bewertungen (\"Bester Kauf meines Lebens!!!\"), gefälschte Kommentare, gefälschte Erfahrungsberichte, gefälschte Nachrichtenartikel (\"Ärzte hassen diesen einen Trick…\").", it: "Sono anche recensioni false (\"Il miglior acquisto della mia vita!!!\"), commenti falsi, testimonianze false, articoli di notizie falsi (\"I medici odiano questo trucco…\").", da: "Det er også falske anmeldelser (\"Bedste køb i mit liv!!!\"), falske kommentarer, falske vidnesbyrd, falske nyhedsartikler (\"Læger hader dette ene trick…\").", bg: "Това са и фалшиви ревюта („Най-добрата ми покупка!!!“), фалшиви коментари, фалшиви свидетелства, фалшиви новинарски статии („Лекарите мразят този трик…“).", tr: "Aynı zamanda sahte yorumlar (\"Hayatımın en iyi alışverişi!!!\"), sahte yorumlar, sahte tanıklıklar, sahte haber makaleleri (\"Doktorlar bu numaradan nefret ediyor…\")." },
        { en: "Same machines, same speed, same motive. Read with the same skepticism.", fr: "Mêmes machines, même vitesse, mêmes motivations. À lire avec la même méfiance.", es: "Mismas máquinas, misma velocidad, mismos motivos. Léelo con el mismo escepticismo.", de: "Gleiche Maschinen, gleiches Tempo, gleiches Motiv. Mit derselben Skepsis lesen.", it: "Stesse macchine, stessa velocità, stessi motivi. Da leggere con lo stesso scetticismo.", da: "Samme maskiner, samme hastighed, samme motiv. Læs med samme skepsis.", bg: "Същите машини, същата скорост, същите мотиви. Чети със същата доза съмнение.", tr: "Aynı makineler, aynı hız, aynı amaç. Aynı şüpheyle oku." }
      ],
      next: "quiz_intro"
    },
    quiz_intro: {
      bot: [
        { en: "Time to play. Three rounds. Each round: an image. You tell me — *real or AI*?", fr: "Maintenant on joue. Trois manches. Une image par manche. Tu me dis — *vrai ou IA* ?", es: "Hora de jugar. Tres rondas. Cada ronda: una imagen. Tú me dices — *real o IA*?", de: "Spielzeit. Drei Runden. Jede Runde: ein Bild. Du sagst mir — *echt oder KI*?", it: "Tempo di giocare. Tre round. Ogni round: un'immagine. Tu mi dici — *vera o IA*?", da: "Tid til at spille. Tre runder. Hver runde: et billede. Du fortæller mig — *ægte eller AI*?", bg: "Време за игра. Три рунда. Във всеки рунд: снимка. Ти ми казваш — *истинско или AI*?", tr: "Oyun zamanı. Üç tur. Her turda bir görsel. Sen bana söyle — *gerçek mi, AI mı*?" },
        { en: "Janet has a slight advantage, but I will not cheat. Promise.", fr: "Janet a un léger avantage, mais promis, je ne triche pas.", es: "Janet tiene una ligera ventaja, pero prometo no hacer trampa.", de: "Janet hat einen kleinen Vorteil, aber ich werde nicht schummeln. Versprochen.", it: "Janet ha un leggero vantaggio, ma prometto di non barare.", da: "Janet har en lille fordel, men jeg lover ikke at snyde.", bg: "Janet има леко предимство, но обещавам да не мамя.", tr: "Janet'in küçük bir avantajı var ama hile yapmayacağım. Söz." }
      ],
      next: "q1_ecosse"
    },
    q1_ecosse: {
      bot: [
        { en: "🥁 Round 1.", fr: "🥁 Manche 1.", es: "🥁 Ronda 1.", de: "🥁 Runde 1.", it: "🥁 Round 1.", da: "🥁 Runde 1.", bg: "🥁 Рунд 1.", tr: "🥁 Tur 1." },
        { image: "assets/ecosse.png", alt: { en: "A rugged coastal cliff overlooking grey water and distant mountains under overcast skies, with green grass on top of the cliffs.", fr: "Une falaise côtière escarpée surplombant des eaux grises et des montagnes lointaines sous un ciel couvert, avec de l'herbe verte au sommet des falaises.", es: "Un acantilado costero escarpado sobre aguas grises y montañas lejanas bajo un cielo nublado, con hierba verde encima de los acantilados.", de: "Eine schroffe Küstenklippe über grauem Wasser und fernen Bergen unter bewölktem Himmel, mit grünem Gras auf den Klippen.", it: "Una scogliera costiera frastagliata sopra acque grigie e montagne lontane sotto un cielo coperto, con erba verde sopra le scogliere.", da: "En forrevet kystklippe over gråt vand og fjerne bjerge under en overskyet himmel, med grønt græs på toppen af klipperne.", bg: "Стръмна крайбрежна скала над сиви води и далечни планини под облачно небе, със зелена трева на върха.", tr: "Bulutlu gökyüzünün altında, gri sulara ve uzaktaki dağlara bakan engebeli bir kıyı uçurumu; uçurumların üzerinde yeşil çimenler var." } },
        { en: "A Scottish coastline. Real photograph or AI-generated?", fr: "Une côte écossaise. Vraie photo ou image générée par IA ?", es: "Una costa escocesa. ¿Foto real o imagen generada por IA?", de: "Eine schottische Küste. Echtes Foto oder KI-generiert?", it: "Una costa scozzese. Foto vera o immagine generata dall'IA?", da: "En skotsk kyst. Ægte foto eller AI-genereret?", bg: "Шотландско крайбрежие. Истинска снимка или генерирана от AI?", tr: "Bir İskoç kıyısı. Gerçek fotoğraf mı, AI tarafından mı üretilmiş?" }
      ],
      choices: [
        { label: { en: "Real photo", fr: "Vraie photo", es: "Foto real", de: "Echtes Foto", it: "Foto vera", da: "Ægte foto", bg: "Истинска снимка", tr: "Gerçek fotoğraf" }, next: "q1_explain", reaction: { en: "Hmm — let me show you why not.", fr: "Hmm — laisse-moi te montrer pourquoi non.", es: "Hmm — déjame mostrarte por qué no.", de: "Hmm — lass mich dir zeigen, warum nicht.", it: "Hmm — lascia che ti mostri perché no.", da: "Hmm — lad mig vise dig hvorfor ikke.", bg: "Хмм — нека ти покажа защо не.", tr: "Hmm — neden olmadığını sana göstereyim." } },
        { label: { en: "AI-generated", fr: "Générée par IA", es: "Generada por IA", de: "KI-generiert", it: "Generata dall'IA", da: "AI-genereret", bg: "Генерирана от AI", tr: "AI tarafından üretilmiş" }, next: "q1_explain", reaction: { en: "✅ Correct!", fr: "✅ Bravo !", es: "✅ ¡Correcto!", de: "✅ Richtig!", it: "✅ Corretto!", da: "✅ Korrekt!", bg: "✅ Точно!", tr: "✅ Doğru!" } }
      ]
    },
    q1_explain: {
      bot: [
        { en: "It's AI. And here's the honest bit: you probably couldn't tell just by looking. The cliffs are plausible, the sky is plausible.", fr: "C'est de l'IA. Et soyons honnêtes : tu ne pouvais sans doute pas le savoir juste en regardant. Les falaises sont plausibles, le ciel l'est aussi.", es: "Es IA. Y aquí va la parte sincera: probablemente no podías saberlo solo mirando. Los acantilados son plausibles, el cielo también.", de: "Es ist KI. Und ehrlich gesagt: nur durchs Hinsehen hättest du es kaum erkennen können. Die Klippen wirken glaubwürdig, der Himmel auch.", it: "È IA. E sinceramente: probabilmente non potevi capirlo solo guardando. Le scogliere sono plausibili, il cielo anche.", da: "Det er AI. Og ærligt talt: du kunne nok ikke se det bare ved at kigge. Klipperne er plausible, himlen er plausibel.", bg: "AI е. И честно казано: едва ли можеше да го разбереш само като гледаш. Скалите изглеждат правдоподобни, небето също.", tr: "AI. Ve dürüst kısmı: sadece bakarak muhtemelen anlayamazdın. Uçurumlar inandırıcı, gökyüzü de inandırıcı." },
        { en: "What you *could* have done: reverse-image-search. Real Scottish landscapes have been photographed by thousands of people. If Google Lens returns zero matches, that's the clue.", fr: "Ce que tu *pouvais* faire : la recherche d'image inversée. Les vrais paysages écossais ont été photographiés par des milliers de gens. Si Google Lens ne renvoie aucune correspondance, voilà l'indice.", es: "Lo que *sí* podías hacer: búsqueda inversa de imagen. Los paisajes escoceses reales los han fotografiado miles de personas. Si Google Lens no devuelve coincidencias, esa es la pista.", de: "Was du *machen* konntest: umgekehrte Bildsuche. Echte schottische Landschaften wurden von Tausenden Menschen fotografiert. Wenn Google Lens null Treffer liefert, ist das der Hinweis.", it: "Quello che *potevi* fare: ricerca inversa di immagini. I veri paesaggi scozzesi sono stati fotografati da migliaia di persone. Se Google Lens non restituisce risultati, è quello l'indizio.", da: "Det du *kunne* have gjort: omvendt billedsøgning. Rigtige skotske landskaber er blevet fotograferet af tusinder af mennesker. Hvis Google Lens ikke giver nogen match, er det sporet.", bg: "Това, което *можеше* да направиш: обратно търсене на изображение. Истинските шотландски пейзажи са снимани от хиляди хора. Ако Google Lens не върне никакъв резултат, това е уликата.", tr: "*Yapabileceğin* şey: ters görsel arama. Gerçek İskoç manzaraları binlerce insan tarafından fotoğraflandı. Eğer Google Lens hiç sonuç vermiyorsa, ipucu işte budur." },
        { en: "Lesson 1: when in doubt, *trace*, don't squint.", fr: "Leçon 1 : en cas de doute, *remonte* l'image, ne plisse pas les yeux.", es: "Lección 1: en caso de duda, *rastrea*, no entornes los ojos.", de: "Lektion 1: im Zweifel *verfolgen*, nicht zusammenkneifen.", it: "Lezione 1: nel dubbio, *risali*, non strizzare gli occhi.", da: "Lektion 1: i tvivl, så *spor*, ikke skel.", bg: "Урок 1: при съмнение — *проследявай*, не присвивай очи.", tr: "Ders 1: şüphedeysen, *takip et*, gözünü kısma." }
      ],
      next: "q2_socotra"
    },
    q2_socotra: {
      bot: [
        { en: "🥁 Round 2. This one is sneaky.", fr: "🥁 Manche 2. Celle-là est sournoise.", es: "🥁 Ronda 2. Esta es traicionera.", de: "🥁 Runde 2. Diese ist hinterhältig.", it: "🥁 Round 2. Questo è subdolo.", da: "🥁 Runde 2. Den her er lumsk.", bg: "🥁 Рунд 2. Този е коварен.", tr: "🥁 Tur 2. Bu sinsi bir tane." },
        { image: "assets/socotra.png", alt: { en: "Two trees with flat, umbrella-shaped tops on a rocky plateau at sunset, with two tiny human figures visible for scale.", fr: "Deux arbres aux cimes plates en forme de parasol sur un plateau rocheux au coucher du soleil, avec deux petites silhouettes humaines visibles pour l'échelle.", es: "Dos árboles con copas planas en forma de paraguas sobre una meseta rocosa al atardecer, con dos figuras humanas diminutas visibles para dar escala.", de: "Zwei Bäume mit flachen, schirmförmigen Kronen auf einem felsigen Plateau bei Sonnenuntergang, mit zwei winzigen menschlichen Figuren als Größenvergleich.", it: "Due alberi con chiome piatte a forma di ombrello su un altopiano roccioso al tramonto, con due piccole figure umane visibili come riferimento di scala.", da: "To træer med flade, paraplyformede toppe på et stenet plateau ved solnedgang, med to bittesmå menneskefigurer synlige som målestok.", bg: "Две дървета с плоски, чадъровидни корони на скалисто плато по залез слънце, с две мънички човешки фигурки за мащаб.", tr: "Gün batımında kayalık bir platoda, düz ve şemsiye biçimli tepeleri olan iki ağaç; ölçek için iki minik insan figürü görünüyor." } },
        { en: "Two trees with flat tops at sunset. Real or AI?", fr: "Deux arbres à cime plate au coucher du soleil. Vrai ou IA ?", es: "Dos árboles con copas planas al atardecer. ¿Real o IA?", de: "Zwei Bäume mit flachen Kronen bei Sonnenuntergang. Echt oder KI?", it: "Due alberi con chiome piatte al tramonto. Vero o IA?", da: "To træer med flade toppe ved solnedgang. Ægte eller AI?", bg: "Две дървета с плоски корони по залез. Истинско или AI?", tr: "Gün batımında düz tepeli iki ağaç. Gerçek mi, AI mı?" }
      ],
      choices: [
        { label: { en: "Real photo", fr: "Vraie photo", es: "Foto real", de: "Echtes Foto", it: "Foto vera", da: "Ægte foto", bg: "Истинска снимка", tr: "Gerçek fotoğraf" }, next: "q2_explain", reaction: { en: "✅ Yes!", fr: "✅ Oui !", es: "✅ ¡Sí!", de: "✅ Ja!", it: "✅ Sì!", da: "✅ Ja!", bg: "✅ Да!", tr: "✅ Evet!" } },
        { label: { en: "AI-generated", fr: "Générée par IA", es: "Generada por IA", de: "KI-generiert", it: "Generata dall'IA", da: "AI-genereret", bg: "Генерирана от AI", tr: "AI tarafından üretilmiş" }, next: "q2_explain", reaction: { en: "Surprise — it's real!", fr: "Surprise — c'est une vraie photo !", es: "Sorpresa — ¡es real!", de: "Überraschung — es ist echt!", it: "Sorpresa — è vera!", da: "Overraskelse — den er ægte!", bg: "Изненада — истинска е!", tr: "Sürpriz — gerçek!" } }
      ]
    },
    q2_explain: {
      bot: [
        { en: "It's real. Those are *Dragon Blood Trees* (Dracaena cinnabari), endemic to Socotra Island, off the coast of Yemen.", fr: "C'est une vraie photo. Ce sont des *arbres dragonniers* (Dracaena cinnabari), endémiques à l'île de Socotra, au large du Yémen.", es: "Es real. Son *Árboles de Sangre de Dragón* (Dracaena cinnabari), endémicos de la isla de Socotra, frente a las costas de Yemen.", de: "Echt. Das sind *Drachenblutbäume* (Dracaena cinnabari), endemisch auf der Insel Sokotra vor der Küste des Jemen.", it: "È vera. Sono *Alberi del sangue di drago* (Dracaena cinnabari), endemici dell'isola di Socotra, al largo dello Yemen.", da: "Den er ægte. Det er *Dragetræer* (Dracaena cinnabari), endemiske for øen Socotra ud for Yemens kyst.", bg: "Истинска е. Това са *Драконови дървета* (Dracaena cinnabari), ендемични за остров Сокотра, край бреговете на Йемен.", tr: "Gerçek. Bunlar Yemen kıyılarının açıklarındaki Socotra adasına özgü *Ejderha Kanı Ağaçları* (Dracaena cinnabari)." },
        { en: "They really do look like umbrellas of leaves on stilts. Reality is, factually, weirder than fiction sometimes.", fr: "Ils ressemblent vraiment à des parasols de feuilles sur échasses. À vrai dire, la réalité dépasse parfois la fiction.", es: "De verdad parecen paraguas de hojas con patas. La realidad es, factualmente, a veces más rara que la ficción.", de: "Sie sehen tatsächlich wie Regenschirme aus Blättern auf Stelzen aus. Die Realität ist, faktisch, manchmal seltsamer als die Fiktion.", it: "Sembrano davvero ombrelli di foglie su trampoli. La realtà è, fattualmente, a volte più strana della fiction.", da: "De ligner virkelig paraplyer af blade på stylter. Virkeligheden er, faktuelt, nogle gange mærkeligere end fiktionen.", bg: "Те наистина изглеждат като чадъри от листа на кокили. Реалността е, технически, понякога по-странна от фантастиката.", tr: "Gerçekten de payandalar üzerindeki yaprak şemsiyelerine benziyorlar. Gerçeklik, fiilen, bazen kurgudan daha tuhaftır." },
        { en: "Reverse-search this image and you'll find hundreds of nearly identical shots by real photographers, tagged with Socotra. That's the green light.", fr: "Fais une recherche inversée et tu trouveras des centaines de clichés quasi identiques pris par de vrai·e·s photographes, taggés Socotra. C'est le feu vert.", es: "Haz búsqueda inversa y encontrarás cientos de fotos casi idénticas de fotógrafos reales, etiquetadas como Socotra. Esa es la luz verde.", de: "Mach eine umgekehrte Suche und du findest Hunderte fast identische Aufnahmen von echten Fotograf*innen, getaggt mit Sokotra. Das ist grünes Licht.", it: "Fai una ricerca inversa e troverai centinaia di scatti quasi identici di veri fotografi, taggati Socotra. È il via libera.", da: "Lav en omvendt søgning, og du finder hundredvis af næsten identiske billeder af rigtige fotografer, tagget Socotra. Det er grønt lys.", bg: "Направи обратно търсене и ще намериш стотици почти идентични кадри от истински фотографи, тагнати Socotra. Това е зелена светлина.", tr: "Bu görselin ters aramasını yap ve Socotra etiketli, gerçek fotoğrafçıların çektiği yüzlerce neredeyse aynı kareyi bulursun. İşte yeşil ışık bu." },
        { en: "Lesson 2: *surreal-looking ≠ AI.* Don't dismiss reality just because it looks unusual.", fr: "Leçon 2 : *avoir l'air irréel ≠ IA.* Ne rejette pas la réalité juste parce qu'elle paraît bizarre.", es: "Lección 2: *parecer irreal ≠ IA.* No descartes la realidad solo porque parezca inusual.", de: "Lektion 2: *surreal aussehen ≠ KI.* Verwirf die Realität nicht, nur weil sie ungewöhnlich aussieht.", it: "Lezione 2: *sembrare surreale ≠ IA.* Non scartare la realtà solo perché sembra insolita.", da: "Lektion 2: *at se surrealistisk ud ≠ AI.* Afvis ikke virkeligheden, bare fordi den ser usædvanlig ud.", bg: "Урок 2: *да изглежда нереално ≠ AI.* Не отхвърляй реалността само защото изглежда необичайна.", tr: "Ders 2: *gerçeküstü görünmek ≠ AI.* Sırf alışılmadık göründüğü için gerçekliği reddetme." }
      ],
      next: "q3_trump"
    },
    q3_trump: {
      bot: [
        { en: "🥁 Round 3. Bonus boss. This one has a twist.", fr: "🥁 Manche 3. Boss bonus. Cette manche a un rebondissement.", es: "🥁 Ronda 3. Jefe bonus. Esta ronda tiene un giro.", de: "🥁 Runde 3. Bonus-Endgegner. Diese Runde hat einen Twist.", it: "🥁 Round 3. Boss bonus. Questo round ha un colpo di scena.", da: "🥁 Runde 3. Bonus-boss. Den her runde har et twist.", bg: "🥁 Рунд 3. Бонус бос. Този рунд има обрат.", tr: "🥁 Tur 3. Bonus patron. Bu turda bir sürpriz var." },
        { image: "assets/trump.png", alt: { en: "A man in a dark suit walks on a tarmac alongside a tall grey humanoid figure, flanked by security personnel and military vehicles. A thumb is visible at the edge of the frame, as if the photo is being shown on a phone.", fr: "Un homme en costume sombre marche sur un tarmac aux côtés d'une grande silhouette humanoïde grise, entouré d'agents de sécurité et de véhicules militaires. Un pouce est visible sur le bord du cadre, comme si la photo s'affichait sur un téléphone.", es: "Un hombre con traje oscuro camina por una pista junto a una figura humanoide gris alta, flanqueado por personal de seguridad y vehículos militares. Se ve un pulgar al borde del encuadre, como si la foto se mostrara en un móvil.", de: "Ein Mann im dunklen Anzug geht auf einem Rollfeld neben einer großen grauen humanoiden Figur, flankiert von Sicherheitspersonal und Militärfahrzeugen. Am Bildrand ist ein Daumen zu sehen, als würde das Foto auf einem Handy gezeigt.", it: "Un uomo in abito scuro cammina su una pista d'aeroporto accanto a una figura umanoide grigia e alta, fiancheggiato da personale di sicurezza e veicoli militari. Si vede un pollice al bordo dell'inquadratura, come se la foto fosse mostrata su un telefono.", da: "En mand i mørkt jakkesæt går på en startbane ved siden af en høj grå humanoid figur, flankeret af sikkerhedspersonale og militærkøretøjer. En tommelfinger er synlig i kanten af billedet, som om billedet vises på en telefon.", bg: "Мъж в тъмен костюм върви по писта до висока сива хуманоидна фигура, придружен от охрана и военни превозни средства. В края на кадъра се вижда палец, сякаш снимката е показана на телефон.", tr: "Koyu renk takım elbiseli bir adam, uzun boylu gri bir insanımsı figürün yanında pistte yürüyor; etrafında güvenlik personeli ve askeri araçlar var. Karenin kenarında, sanki fotoğraf bir telefonda gösteriliyormuş gibi bir başparmak görünüyor." } },
        { en: "This image shows a US President walking with what looks like a Grey alien. Pick your verdict:", fr: "Cette image montre un Président américain marchant avec ce qui ressemble à un alien gris. Ton verdict :", es: "Esta imagen muestra a un Presidente de EE.UU. caminando junto a lo que parece un alien Gris. Tu veredicto:", de: "Dieses Bild zeigt einen US-Präsidenten beim Spaziergang mit etwas, das wie ein Grey-Alien aussieht. Dein Urteil:", it: "Questa immagine mostra un Presidente degli Stati Uniti che cammina con quello che sembra un alieno Grigio. Il tuo verdetto:", da: "Dette billede viser en amerikansk Præsident gå sammen med noget der ligner et Grey-rumvæsen. Din dom:", bg: "Тази снимка показва американски Президент, който върви с нещо подобно на сив извънземен. Твоята присъда:", tr: "Bu görsel, bir ABD Başkanını Gri uzaylıya benzeyen bir şeyle yürürken gösteriyor. Kararını ver:" }
      ],
      choices: [
        { label: { en: "Real photo", fr: "Vraie photo", es: "Foto real", de: "Echtes Foto", it: "Foto vera", da: "Ægte foto", bg: "Истинска снимка", tr: "Gerçek fotoğraf" }, next: "q3_explain", reaction: { en: "Per my records, no aliens yet. Stay tuned.", fr: "D'après mes archives, pas encore d'aliens. On reste à l'affût.", es: "Según mis registros, todavía no hay aliens. Sigamos atentos.", de: "Laut meinen Aufzeichnungen noch keine Aliens. Bleib dran.", it: "Secondo i miei archivi, niente alieni per ora. Restiamo sintonizzati.", da: "Ifølge mine optegnelser ingen rumvæsener endnu. Bliv hængende.", bg: "Според регистрите ми — все още няма извънземни. Чакаме.", tr: "Kayıtlarıma göre henüz uzaylı yok. Takipte kal." } },
        { label: { en: "AI — and only a random scammer would post this", fr: "IA — et seul un arnaqueur lambda posterait ça", es: "IA — y solo un estafador random la publicaría", de: "KI — und nur ein x-beliebiger Betrüger würde das posten", it: "IA — e solo un truffatore qualunque la pubblicherebbe", da: "AI — og kun en tilfældig svindler ville poste det", bg: "AI — и само случаен измамник би я публикувал", tr: "AI — ve bunu ancak rastgele bir dolandırıcı paylaşır" }, next: "q3_explain", reaction: { en: "Half right. It's AI. But about the 'only a scammer' part…", fr: "À moitié juste. C'est de l'IA. Mais sur le \"seul un arnaqueur\"…", es: "Medio acierto. Es IA. Pero lo de \"solo un estafador\"…", de: "Halb richtig. Es ist KI. Aber zum 'nur ein Betrüger'-Teil…", it: "Mezzo giusto. È IA. Ma sulla parte \"solo un truffatore\"…", da: "Halvt rigtigt. Det er AI. Men angående 'kun en svindler'-delen…", bg: "Наполовина прав. AI е. Но за \"само измамник\"...", tr: "Yarı doğru. AI. Ama 'sadece bir dolandırıcı' kısmı için..." } },
        { label: { en: "AI — posted on the President's actual official account", fr: "IA — posté sur le compte officiel du Président lui-même", es: "IA — publicada en la cuenta oficial del Presidente mismo", de: "KI — auf dem echten offiziellen Account des Präsidenten gepostet", it: "IA — pubblicata sull'account ufficiale del Presidente stesso", da: "AI — postet på Præsidentens egen officielle konto", bg: "AI — публикувана в собствения официален акаунт на Президента", tr: "AI — Başkanın gerçek resmi hesabında paylaşılmış" }, next: "q3_explain", reaction: { en: "✅ Spot on. Welcome to 2026.", fr: "✅ Pile dans le mille. Bienvenue en 2026.", es: "✅ Justo en el clavo. Bienvenido·a a 2026.", de: "✅ Genau. Willkommen im Jahr 2026.", it: "✅ Esattamente. Benvenuto·a nel 2026.", da: "✅ Lige i øjet. Velkommen til 2026.", bg: "✅ Право в десетката. Добре дошъл·а в 2026.", tr: "✅ Tam isabet. 2026'ya hoş geldin." } }
      ]
    },
    q3_explain: {
      bot: [
        { en: "Plot twist: yes, it's AI. And yes — this kind of AI image has been shared from authentic, official, verified government accounts.", fr: "Rebondissement : oui, c'est de l'IA. Et oui — ce genre d'image IA a été partagé depuis des comptes gouvernementaux authentiques, officiels, vérifiés.", es: "Giro: sí, es IA. Y sí — este tipo de imagen IA se ha compartido desde cuentas gubernamentales auténticas, oficiales y verificadas.", de: "Plot-Twist: ja, es ist KI. Und ja — solche KI-Bilder wurden von authentischen, offiziellen, verifizierten Regierungskonten geteilt.", it: "Colpo di scena: sì, è IA. E sì — questo tipo di immagini IA è stato condiviso da account governativi autentici, ufficiali e verificati.", da: "Plot-twist: ja, det er AI. Og ja — den slags AI-billeder er blevet delt fra autentiske, officielle, verificerede regeringskonti.", bg: "Обрат: да, AI е. И да — подобни AI снимки са били споделяни от автентични, официални, верифицирани правителствени акаунти.", tr: "Sürpriz: evet, AI. Ve evet — bu tür AI görselleri, gerçek, resmi, doğrulanmış hükümet hesaplarından paylaşıldı." },
        { en: "Lesson 3, the important one: in 2026, even verified, real accounts post AI content. Sometimes labeled, sometimes not. Sometimes ironically, sometimes not.", fr: "Leçon 3, la plus importante : en 2026, même les comptes vérifiés et réels publient du contenu IA. Parfois étiqueté, parfois non. Parfois ironique, parfois non.", es: "Lección 3, la importante: en 2026, incluso las cuentas verificadas y reales publican contenido de IA. A veces etiquetado, a veces no. A veces irónicamente, a veces no.", de: "Lektion 3, die wichtige: 2026 posten selbst verifizierte, echte Accounts KI-Inhalte. Mal gekennzeichnet, mal nicht. Mal ironisch, mal nicht.", it: "Lezione 3, quella importante: nel 2026, anche gli account verificati e reali pubblicano contenuti IA. A volte etichettati, a volte no. A volte ironicamente, a volte no.", da: "Lektion 3, den vigtige: i 2026 poster selv verificerede, ægte konti AI-indhold. Nogle gange markeret, nogle gange ikke. Nogle gange ironisk, nogle gange ikke.", bg: "Урок 3, важният: през 2026 дори верифицирани, истински акаунти публикуват AI съдържание. Понякога с етикет, понякога без. Понякога иронично, понякога не.", tr: "Ders 3, önemli olanı: 2026'da, doğrulanmış, gerçek hesaplar bile AI içeriği paylaşıyor. Bazen etiketli, bazen değil. Bazen ironik olarak, bazen değil." },
        { en: "Source-checking is necessary but not sufficient. You also need to check the *content* itself. 'Trust the account' is, factually, no longer a complete answer.", fr: "Vérifier la source reste nécessaire, mais ça ne suffit plus. Il faut aussi vérifier le *contenu* lui-même. \"Faire confiance au compte\", aujourd'hui, ce n'est plus une réponse complète.", es: "Verificar la fuente es necesario pero ya no basta. También hay que comprobar el *contenido* mismo. \"Confiar en la cuenta\" ya no es, factualmente, una respuesta completa.", de: "Quellenprüfung ist nötig, aber nicht mehr ausreichend. Du musst auch den *Inhalt* selbst prüfen. 'Dem Account vertrauen' ist, faktisch, keine vollständige Antwort mehr.", it: "Verificare la fonte è necessario ma non più sufficiente. Devi anche controllare il *contenuto* stesso. \"Fidarsi dell'account\" non è più, fattualmente, una risposta completa.", da: "Kildekontrol er nødvendigt, men ikke længere tilstrækkeligt. Du skal også tjekke *indholdet* selv. \"Stol på kontoen\" er, faktuelt, ikke længere et fuldt svar.", bg: "Проверката на източника е необходима, но вече не е достатъчна. Трябва да проверяваш и самото *съдържание*. \"Доверявай се на акаунта\" вече, технически, не е пълен отговор.", tr: "Kaynak kontrolü gerekli ama yeterli değil. *İçeriğin* kendisini de kontrol etmen gerekiyor. 'Hesaba güven' artık, fiilen, tam bir cevap değil." }
      ],
      next: "tools"
    },
    tools: {
      bot: [
        { en: "Janet's recommended fact-check shelf:", fr: "Les outils que Janet recommande pour faire le tri :", es: "Las herramientas que Janet recomienda para verificar:", de: "Janets empfohlene Werkzeuge zum Faktencheck:", it: "Gli strumenti che Janet consiglia per verificare:", da: "Janets anbefalede værktøjer til faktatjek:", bg: "Инструментите, които Janet препоръчва за проверка:", tr: "Janet'in doğrulama için önerdiği araçlar:" },
        { en: "🔍 *Snopes* — old and reliable, covers urban legends and viral claims.", fr: "🔍 *Snopes* — vieux et fiable, couvre les légendes urbaines et les contenus viraux.", es: "🔍 *Snopes* — antiguo y fiable, cubre leyendas urbanas y bulos virales.", de: "🔍 *Snopes* — alt und zuverlässig, deckt Urban Legends und virale Behauptungen ab.", it: "🔍 *Snopes* — vecchio e affidabile, copre leggende urbane e bufale virali.", da: "🔍 *Snopes* — gammel og pålidelig, dækker vandrehistorier og virale påstande.", bg: "🔍 *Snopes* — стар и надежден, покрива градски легенди и вирусни твърдения.", tr: "🔍 *Snopes* — eski ve güvenilir, şehir efsanelerini ve viral iddiaları kapsar." },
        { en: "📰 *FactCheck.org* and *PolitiFact* — solid on political claims.", fr: "📰 *FactCheck.org* et *PolitiFact* — solides sur les affirmations politiques.", es: "📰 *FactCheck.org* y *PolitiFact* — sólidos en afirmaciones políticas.", de: "📰 *FactCheck.org* und *PolitiFact* — solide bei politischen Behauptungen.", it: "📰 *FactCheck.org* e *PolitiFact* — solidi sulle affermazioni politiche.", da: "📰 *FactCheck.org* og *PolitiFact* — solide på politiske påstande.", bg: "📰 *FactCheck.org* и *PolitiFact* — солидни за политически твърдения.", tr: "📰 *FactCheck.org* ve *PolitiFact* — politik iddialarda sağlam." },
        { en: "🌍 Local ones too: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DA), *Factcheck.bg* (BG).", fr: "🌍 Locaux aussi : *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", es: "🌍 También locales: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", de: "🌍 Auch lokal: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", it: "🌍 Anche locali: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", da: "🌍 Også lokale: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", bg: "🌍 И локални: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG).", tr: "🌍 Yerel olanlar da var: *AFP Factuel* (FR), *Maldita.es* (ES), *Correctiv* (DE), *Pagella Politica* (IT), *TjekDet* (DK), *Factcheck.bg* (BG)." },
        { en: "🛠️ *InVID WeVerify* — a free browser extension built for digging into images and videos. Janet adores it.", fr: "🛠️ *InVID WeVerify* — une extension de navigateur gratuite faite pour fouiller images et vidéos. Janet l'adore.", es: "🛠️ *InVID WeVerify* — una extensión de navegador gratuita pensada para examinar imágenes y vídeos. Janet la adora.", de: "🛠️ *InVID WeVerify* — eine kostenlose Browser-Erweiterung, gebaut, um Bilder und Videos zu durchleuchten. Janet liebt sie.", it: "🛠️ *InVID WeVerify* — un'estensione del browser gratuita per scavare in immagini e video. Janet la adora.", da: "🛠️ *InVID WeVerify* — en gratis browserudvidelse bygget til at grave i billeder og videoer. Janet elsker den.", bg: "🛠️ *InVID WeVerify* — безплатно разширение за браузър, направено да рови в снимки и видеа. Janet го обожава.", tr: "🛠️ *InVID WeVerify* — görseller ve videolar üzerinde derinlemesine inceleme yapmak için tasarlanmış ücretsiz bir tarayıcı eklentisi. Janet ona bayılıyor." }
      ],
      next: "outro"
    },
    outro: {
      bot: [
        { en: "Final Janet thought: skepticism is, factually, a form of kindness.", fr: "Dernière pensée de Janet : le scepticisme, factuellement, c'est une forme de gentillesse.", es: "Último pensamiento de Janet: el escepticismo es, factualmente, una forma de amabilidad.", de: "Letzter Janet-Gedanke: Skepsis ist, faktisch, eine Form von Freundlichkeit.", it: "Pensiero finale di Janet: lo scetticismo è, fattualmente, una forma di gentilezza.", da: "Sidste Janet-tanke: skepsis er, faktuelt, en form for venlighed.", bg: "Последна мисъл от Janet: скептицизмът е, технически, форма на доброта.", tr: "Janet'ten son bir düşünce: şüphecilik, fiilen, bir tür naziklik biçimidir." },
        { en: "When you don't share something false, you spare someone's parent from a panic. And you save the truth a tiny bit of erosion.", fr: "Quand tu ne partages pas une info fausse, tu épargnes une crise de panique au parent de quelqu'un. Et tu épargnes à la vérité un petit grain d'érosion.", es: "Cuando no compartes algo falso, le ahorras un susto al padre o madre de alguien. Y le ahorras a la verdad un poquito de erosión.", de: "Wenn du etwas Falsches nicht teilst, ersparst du den Eltern von jemandem eine Panikattacke. Und du ersparst der Wahrheit ein winziges bisschen Erosion.", it: "Quando non condividi qualcosa di falso, risparmi una crisi al genitore di qualcuno. E risparmi alla verità un pizzico di erosione.", da: "Når du ikke deler noget falsk, sparer du nogens forælder for en panik. Og du sparer sandheden for en lille smule erosion.", bg: "Когато не споделиш нещо невярно, спестяваш паника на нечий родител. И спестяваш на истината мъничко ерозия.", tr: "Yanlış bir şeyi paylaşmadığında, birinin ebeveynini panikten kurtarırsın. Ve gerçeği küçücük bir aşınmadan kurtarırsın." },
        { en: "Bye for now! 🥣", fr: "À très vite ! 🥣", es: "¡Hasta luego! 🥣", de: "Bis bald! 🥣", it: "A presto! 🥣", da: "Vi ses! 🥣", bg: "До скоро! 🥣", tr: "Şimdilik hoşça kal! 🥣" }
      ],
      end: true
    }
  }
};
