window.JANET_COURSES = window.JANET_COURSES || {};
window.JANET_COURSES.ceo_fraud = {
  id: "ceo_fraud",
  emoji: "🎭",
  duration: 5,
  karma: 50,
  title: {
    en: "Impersonation scams",
    fr: "Arnaques par usurpation",
    es: "Estafas por suplantación",
    de: "Identitätsbetrug",
    it: "Truffe d'impersonificazione",
    da: "Identitetstyveri-svindel",
    bg: "Измами с фалшива самоличност",
    tr: "Kimliğe bürünme dolandırıcılıkları"
  },
  description: {
    en: "When \"your boss\" — or your husband, wife, or kid — asks for an urgent favor.",
    fr: "Quand \"ton patron\" — ou ton mari, ta femme, ton enfant — te demande un service urgent.",
    es: "Cuando \"tu jefe\" — o tu marido, tu mujer, tu hijo — te pide un favor urgente.",
    de: "Wenn \"dein Chef\" — oder dein Mann, deine Frau, dein Kind — um einen dringenden Gefallen bittet.",
    it: "Quando \"il tuo capo\" — o tuo marito, tua moglie, tuo figlio — chiede un favore urgente.",
    da: "Når \"din chef\" — eller din mand, kone eller barn — beder om en hastetjeneste.",
    bg: "Когато \"шефът ти\" — или съпругът, съпругата или детето ти — иска спешна услуга.",
    tr: "\"Patronun\" — ya da kocan, karın veya çocuğun — senden acil bir iyilik istediğinde."
  },
  startNode: "start",
  nodes: {
    start: {
      bot: [
        { en: "Hi there! Janet here.", fr: "Salut ! C'est Janet.", es: "¡Hola! Soy Janet.", de: "Hallo! Hier ist Janet.", it: "Ciao! Sono Janet.", da: "Hej! Det er Janet.", bg: "Здравей! Аз съм Janet.", tr: "Merhaba! Ben Janet." },
        { en: "Today's scam costs *families* and *companies* billions of dollars a year, and — fun fact — it almost always plays out the exact same way.", fr: "L'arnaque du jour coûte des milliards chaque année, aux *familles* comme aux *entreprises*, et — anecdote — elle se déroule presque toujours pareil.", es: "La estafa de hoy le cuesta a las *familias* y a las *empresas* miles de millones de dólares al año, y — dato curioso — casi siempre se desarrolla exactamente de la misma manera.", de: "Der heutige Betrug kostet *Familien* und *Unternehmen* jährlich Milliarden, und — kurioses Detail — er läuft fast immer exakt gleich ab.", it: "La truffa di oggi costa miliardi di dollari l'anno a *famiglie* e *aziende*, e — curiosità — si svolge quasi sempre esattamente nello stesso modo.", da: "Dagens svindel koster *familier* og *virksomheder* milliarder af dollars om året, og — sjov detalje — den udspiller sig næsten altid på præcis samme måde.", bg: "Днешната измама струва на *семействата* и *компаниите* милиарди долари годишно, и — забавен факт — почти винаги протича по абсолютно същия начин.", tr: "Bugünkü dolandırıcılık *ailelere* ve *şirketlere* yılda milyarlarca dolara mal oluyor ve — ilginç bir bilgi — neredeyse her zaman tam olarak aynı şekilde işliyor." },
        { en: "It goes by many names. *CEO fraud*. *Whaling*. *Impersonation scam*. *Grandparent scam*. *Hi mom* scam. Different costume — exact same trick.", fr: "Elle a plein de noms. *Fraude au président*. *Whaling*. *Arnaque par usurpation*. *Arnaque aux grands-parents*. *Arnaque coucou maman*. Costume différent — exactement le même tour.", es: "Tiene muchos nombres. *Fraude del CEO*. *Whaling*. *Estafa de suplantación*. *Estafa de los abuelos*. *Estafa \"hola mamá\"*. Disfraz distinto — exactamente el mismo truco.", de: "Sie hat viele Namen. *CEO-Betrug*. *Whaling*. *Identitätsbetrug*. *Enkeltrick*. *Hallo-Mama*-Masche. Anderes Kostüm — exakt derselbe Trick.", it: "Ha tanti nomi. *Frode del CEO*. *Whaling*. *Truffa d'impersonificazione*. *Truffa dei nonni*. Truffa *ciao mamma*. Costume diverso — esattamente lo stesso trucco.", da: "Den har mange navne. *CEO-svindel*. *Whaling*. *Identitetssvindel*. *Bedsteforælder-svindel*. *Hej mor*-svindel. Forskelligt kostume — præcis samme trick.", bg: "Има много имена. *CEO измама*. *Whaling*. *Измама с фалшива самоличност*. *Измама с баби и дядовци*. Измамата *здравей, мамо*. Различен костюм — абсолютно същият трик.", tr: "Birçok adı var. *CEO dolandırıcılığı*. *Whaling*. *Kimliğe bürünme dolandırıcılığı*. *Büyükanne-büyükbaba dolandırıcılığı*. *Anne ben* dolandırıcılığı. Farklı kostüm — tıpatıp aynı oyun." }
      ],
      choices: [{ label: { en: "Walk me through it", fr: "Explique-moi", es: "Cuéntame paso a paso", de: "Erklär es mir", it: "Spiegamela passo passo", da: "Forklar mig det", bg: "Разкажи ми подробно", tr: "Adım adım anlat" }, next: "setup" }]
    },
    setup: {
      bot: [
        { en: "The plot is always the same, whether the scam wears a suit or a smiley face:", fr: "Le scénario est toujours le même, que l'arnaque porte une cravate ou un smiley :", es: "El guion es siempre el mismo, ya sea que la estafa lleve traje o una carita sonriente:", de: "Das Drehbuch ist immer dasselbe, ob der Betrug einen Anzug trägt oder einen Smiley:", it: "La trama è sempre la stessa, sia che la truffa indossi un completo o uno smiley:", da: "Plottet er altid det samme, uanset om svindlen har jakkesæt på eller en smiley:", bg: "Сюжетът винаги е същият, независимо дали измамата носи костюм или усмихнато лице:", tr: "Senaryo her zaman aynıdır, dolandırıcılık ister takım elbise giysin ister gülen yüz takınsın:" },
        { en: "1. Someone impersonates a person you trust — your boss, your spouse, your child, your parent, your best friend.", fr: "1. Quelqu'un se fait passer pour une personne de confiance — ton patron, ton conjoint, ton enfant, ton parent, ton meilleur ami.", es: "1. Alguien se hace pasar por una persona en la que confías — tu jefe, tu pareja, tu hijo, tu padre, tu mejor amigo.", de: "1. Jemand gibt sich als eine Vertrauensperson aus — dein Chef, dein Partner, dein Kind, dein Elternteil, dein bester Freund.", it: "1. Qualcuno si finge una persona di cui ti fidi — il tuo capo, il tuo partner, tuo figlio, un tuo genitore, il tuo migliore amico.", da: "1. Nogen udgiver sig for at være en, du stoler på — din chef, din partner, dit barn, din forælder, din bedste ven.", bg: "1. Някой се представя за човек, на когото имаш доверие — шефът ти, партньорът ти, детето ти, родителят ти, най-добрият ти приятел.", tr: "1. Biri güvendiğin birinin kimliğine bürünür — patronun, eşin, çocuğun, annen-baban, en yakın arkadaşın." },
        { en: "2. They contact you on a *new* channel — a different number, a different email — with a panicked story.", fr: "2. Cette personne te contacte sur un *nouveau* canal — autre numéro, autre email — avec une histoire affolée.", es: "2. Te contacta por un canal *nuevo* — otro número, otro correo — con una historia desesperada.", de: "2. Diese Person kontaktiert dich über einen *neuen* Kanal — eine andere Nummer, eine andere E-Mail — mit einer panischen Geschichte.", it: "2. Ti contatta su un canale *nuovo* — un numero diverso, un'email diversa — con una storia in preda al panico.", da: "2. Personen kontakter dig på en *ny* kanal — et andet nummer, en anden e-mail — med en panisk historie.", bg: "2. Свързва се с теб през *нов* канал — друг номер, друг имейл — с паническа история.", tr: "2. Sana *yeni* bir kanaldan ulaşır — farklı bir numara, farklı bir e-posta — panik dolu bir hikâyeyle." },
        { en: "3. They ask for money, codes, or sensitive info, and they ask *fast*, in *private*, *right now*.", fr: "3. Elle demande de l'argent, des codes, ou des infos sensibles. *Vite*. *En secret*. *Maintenant*.", es: "3. Pide dinero, códigos o información sensible, y lo pide *rápido*, en *privado*, *ahora mismo*.", de: "3. Sie verlangt Geld, Codes oder sensible Informationen — *schnell*, *vertraulich*, *sofort*.", it: "3. Chiede soldi, codici o informazioni sensibili, e lo chiede *in fretta*, in *privato*, *subito*.", da: "3. De beder om penge, koder eller følsomme oplysninger — *hurtigt*, *i hemmelighed*, *lige nu*.", bg: "3. Иска пари, кодове или чувствителна информация, и пита *бързо*, *тайно*, *веднага*.", tr: "3. Para, kod ya da hassas bilgi ister; üstelik *hızlıca*, *gizlice*, *şu anda* ister." }
      ],
      next: "example_work"
    },
    example_work: {
      bot: [
        { en: "Work version. You get an email from your CEO:", fr: "Version boulot. Tu reçois un email de ton PDG :", es: "Versión trabajo. Recibes un correo de tu CEO:", de: "Berufsversion. Du bekommst eine E-Mail von deinem CEO:", it: "Versione lavoro. Ricevi un'email dal tuo CEO:", da: "Arbejdsversion. Du får en e-mail fra din CEO:", bg: "Работна версия. Получаваш имейл от твоя CEO:", tr: "İş versiyonu. CEO'ndan bir e-posta alıyorsun:" },
        { en: "*\"Hi — I'm in a board meeting and can't take calls. Can you wire €38,400 to this supplier today? Confidential, please don't mention it to the team yet.\"*", fr: "*\"Coucou — je suis en conseil d'administration, je ne peux pas répondre. Tu peux virer 38 400 € à ce fournisseur aujourd'hui ? Confidentiel, n'en parle pas à l'équipe.\"*", es: "*\"Hola — estoy en un consejo de administración y no puedo atender llamadas. ¿Puedes transferir 38.400 € a este proveedor hoy? Es confidencial, por favor no lo menciones al equipo todavía.\"*", de: "*\"Hallo — ich bin gerade in einer Vorstandssitzung und kann nicht ans Telefon. Kannst du heute €38.400 an diesen Lieferanten überweisen? Vertraulich, bitte sag dem Team noch nichts davon.\"*", it: "*\"Ciao — sono in riunione di consiglio e non posso rispondere al telefono. Puoi fare un bonifico di 38.400 € a questo fornitore oggi? È riservato, per favore non dirlo ancora al team.\"*", da: "*\"Hej — jeg er til bestyrelsesmøde og kan ikke tage telefonen. Kan du overføre 38.400 € til denne leverandør i dag? Det er fortroligt, så nævn det venligst ikke for teamet endnu.\"*", bg: "*\"Здравей — на заседание на борда съм и не мога да отговарям на обаждания. Можеш ли да преведеш 38 400 € на този доставчик днес? Поверително е, моля не казвай на екипа още.\"*", tr: "*\"Selam — yönetim kurulu toplantısındayım, telefonlara bakamıyorum. Bugün bu tedarikçiye €38.400 havale edebilir misin? Gizli, lütfen ekibe henüz söyleme.\"*" },
        { en: "Even the *amount* is engineered. Small enough to slip under approval thresholds, big enough to hurt.", fr: "Même le *montant* est calculé. Assez petit pour passer sous les seuils d'approbation, assez gros pour faire mal.", es: "Incluso el *importe* está calculado. Lo bastante pequeño para colarse bajo los umbrales de aprobación, lo bastante grande para hacer daño.", de: "Selbst der *Betrag* ist berechnet. Klein genug, um unter den Freigabegrenzen durchzurutschen, groß genug, um wehzutun.", it: "Persino la *cifra* è studiata. Abbastanza piccola da passare sotto le soglie di approvazione, abbastanza grande da fare male.", da: "Selv *beløbet* er nøje udregnet. Lille nok til at glide under godkendelsesgrænserne, stort nok til at gøre ondt.", bg: "Дори *сумата* е изчислена. Достатъчно малка, за да се промъкне под праговете за одобрение, достатъчно голяма, за да заболи.", tr: "*Miktar* bile özenle seçilmiş. Onay eşiklerinin altından sızacak kadar küçük, can yakacak kadar büyük." }
      ],
      next: "example_home"
    },
    example_home: {
      bot: [
        { en: "Home version. You get a text from an unknown number:", fr: "Version maison. Tu reçois un SMS d'un numéro inconnu :", es: "Versión hogar. Recibes un SMS de un número desconocido:", de: "Privatversion. Du bekommst eine SMS von einer unbekannten Nummer:", it: "Versione casa. Ricevi un SMS da un numero sconosciuto:", da: "Hjemmeversion. Du får en sms fra et ukendt nummer:", bg: "Домашна версия. Получаваш SMS от непознат номер:", tr: "Ev versiyonu. Bilinmeyen bir numaradan mesaj alıyorsun:" },
        { en: "*\"Hi mom, my phone is broken, this is my new number. I really need you to pay a bill for me today — I'll explain tonight. Don't worry dad, he'll just stress.\"*", fr: "*\"Coucou maman, mon téléphone est cassé, voici mon nouveau numéro. J'ai vraiment besoin que tu paies une facture pour moi aujourd'hui — j'expliquerai ce soir. N'en parle pas à papa, ça va le stresser pour rien.\"*", es: "*\"Hola mamá, se me rompió el móvil, este es mi nuevo número. Necesito que me pagues una factura hoy mismo — te explico esta noche. No le digas nada a papá, solo va a estresarse.\"*", de: "*\"Hi Mama, mein Handy ist kaputt, das ist meine neue Nummer. Ich brauche dich wirklich, kannst du heute eine Rechnung für mich bezahlen? Ich erkläre es heute Abend. Sag Papa nichts, er stresst sich nur.\"*", it: "*\"Ciao mamma, il mio telefono è rotto, questo è il mio nuovo numero. Ho davvero bisogno che tu mi paghi una bolletta oggi — ti spiego stasera. Non dire niente a papà, si stresserebbe inutilmente.\"*", da: "*\"Hej mor, min telefon er gået i stykker, det her er mit nye nummer. Jeg har virkelig brug for, at du betaler en regning for mig i dag — jeg forklarer i aften. Sig ikke noget til far, han bliver bare stresset.\"*", bg: "*\"Здрасти, мамо, телефонът ми е счупен, това е новият ми номер. Наистина имам нужда да ми платиш една сметка днес — ще ти обясня довечера. Не казвай на татко, само ще се притесни.\"*", tr: "*\"Anne, telefonum bozuldu, bu yeni numaram. Bugün benim için bir fatura ödemen lazım — akşam anlatırım. Babama söyleme, sadece boş yere strese girer.\"*" },
        { en: "Same scam, lower budget, higher heartbreak.", fr: "Même arnaque, budget plus petit, peine plus grande.", es: "Misma estafa, presupuesto menor, golpe emocional mayor.", de: "Gleicher Betrug, kleineres Budget, größerer Herzschmerz.", it: "Stessa truffa, budget più basso, dolore più grande.", da: "Samme svindel, mindre budget, større hjertesorg.", bg: "Същата измама, по-малък бюджет, по-голяма сърдечна болка.", tr: "Aynı dolandırıcılık, daha düşük bütçe, daha büyük gönül yarası." }
      ],
      next: "example_spouse"
    },
    example_spouse: {
      bot: [
        { en: "Spouse version. Your partner — supposedly — emails from a slightly-off address:", fr: "Version conjoint·e. Ton ou ta partenaire — soi-disant — t'écrit depuis une adresse un peu bizarre :", es: "Versión pareja. Tu pareja — supuestamente — te escribe desde una dirección ligeramente extraña:", de: "Partner-Version. Dein·e Partner·in — angeblich — schreibt dir von einer leicht seltsamen Adresse:", it: "Versione partner. Il tuo/la tua partner — presunto/a tale — ti scrive da un indirizzo leggermente strano:", da: "Partner-version. Din partner — angiveligt — skriver fra en lidt mærkelig adresse:", bg: "Версия партньор. Партньорът ти — уж — ти пише от леко странен адрес:", tr: "Eş versiyonu. Eşin — sözde — biraz tuhaf bir adresten e-posta atıyor:" },
        { en: "*\"Honey, I'm with the notary and they need a transfer this morning to finalize. Can you wire it from the joint account? I'll call you after.\"*", fr: "*\"Chéri·e, je suis chez le notaire, il nous faut un virement ce matin pour finaliser. Tu peux l'envoyer depuis le compte joint ? Je t'appelle après.\"*", es: "*\"Cariño, estoy con el notario y necesitan una transferencia esta mañana para cerrar. ¿Puedes mandarla desde la cuenta conjunta? Te llamo después.\"*", de: "*\"Schatz, ich bin beim Notar und sie brauchen heute Morgen eine Überweisung, um abzuschließen. Kannst du es vom gemeinsamen Konto schicken? Ich rufe dich danach an.\"*", it: "*\"Tesoro, sono dal notaio e serve un bonifico stamattina per chiudere. Puoi farlo dal conto cointestato? Ti chiamo dopo.\"*", da: "*\"Skat, jeg er hos notaren, og de skal bruge en overførsel her til morgen for at afslutte. Kan du sende den fra fælleskontoen? Jeg ringer bagefter.\"*", bg: "*\"Скъпи/а, при нотариуса съм и им трябва превод тази сутрин, за да приключим. Можеш ли да го направиш от общата ни сметка? Ще ти звънна след това.\"*", tr: "*\"Aşkım, noterdeyim ve işi bitirmek için bu sabah bir havale gerekiyor. Ortak hesaptan gönderebilir misin? Sonra seni ararım.\"*" },
        { en: "Notice the pattern: urgent, slightly out of reach by phone, money moving fast. Per Janet's records, that pattern is the entire scam.", fr: "Tu vois le schéma : urgent, à peine injoignable par téléphone, argent qui file vite. Dans les registres de Janet, ce schéma à lui tout seul, c'est toute l'arnaque.", es: "Fíjate en el patrón: urgente, ligeramente inaccesible por teléfono, dinero moviéndose rápido. Según los registros de Janet, ese patrón es toda la estafa.", de: "Achte auf das Muster: dringend, telefonisch leicht unerreichbar, Geld in Bewegung. Laut Janets Aufzeichnungen ist genau dieses Muster der ganze Betrug.", it: "Nota lo schema: urgente, leggermente irraggiungibile al telefono, soldi che si muovono in fretta. Secondo gli archivi di Janet, quello schema è l'intera truffa.", da: "Læg mærke til mønstret: presserende, lidt uden for rækkevidde på telefonen, penge der flytter sig hurtigt. Ifølge Janets optegnelser er det mønster hele svindlen.", bg: "Забележи модела: спешно, леко недостъпен по телефона, бързо движещи се пари. Според регистрите на Janet, този модел е цялата измама.", tr: "Örüntüye dikkat et: acil, telefonla az biraz ulaşılmaz, hızla hareket eden para. Janet'in kayıtlarına göre, bu örüntü dolandırıcılığın ta kendisi." }
      ],
      choices: [{ label: { en: "Devious", fr: "Vicieux", es: "Retorcido", de: "Hinterhältig", it: "Subdolo", da: "Lumsk", bg: "Коварно", tr: "Sinsi" }, next: "voice_clone" }]
    },
    voice_clone: {
      bot: [
        { en: "Modern twist alert. Scammers now use *AI to clone voices* from a few seconds of someone's social media video.", fr: "Petite touche moderne. Les arnaqueurs utilisent désormais *l'IA pour cloner une voix* à partir de quelques secondes de vidéo sur les réseaux sociaux.", es: "Alerta de novedad moderna. Los estafadores ahora usan *IA para clonar voces* a partir de unos segundos de vídeo en redes sociales.", de: "Moderne Variante alarmierend. Betrüger nutzen jetzt *KI, um Stimmen zu klonen*, aus wenigen Sekunden Social-Media-Video.", it: "Allarme novità moderna. I truffatori ora usano *l'IA per clonare le voci* da pochi secondi di video sui social media.", da: "Moderne twist-alarm. Svindlere bruger nu *AI til at klone stemmer* ud fra få sekunders video på sociale medier.", bg: "Внимание, модерен обрат. Измамниците сега използват *AI, за да клонират гласове* от няколко секунди видео в социалните мрежи.", tr: "Modern dönüş uyarısı. Dolandırıcılar artık sosyal medyadaki birkaç saniyelik videodan *yapay zekâ ile ses klonluyor*." },
        { en: "A panicked phone call \"from your daughter\" can sound exactly like her — sobbing, scared, begging for help.", fr: "Un appel paniqué \"de ta fille\" peut sonner exactement comme elle — en larmes, terrifiée, te suppliant de l'aider.", es: "Una llamada desesperada \"de tu hija\" puede sonar exactamente como ella — sollozando, asustada, suplicando ayuda.", de: "Ein panischer Anruf \"von deiner Tochter\" kann genau wie sie klingen — schluchzend, verängstigt, um Hilfe bettelnd.", it: "Una telefonata in preda al panico \"di tua figlia\" può suonare esattamente come lei — singhiozzando, spaventata, che implora aiuto.", da: "Et panisk telefonopkald \"fra din datter\" kan lyde præcis som hende — hulkende, bange, tiggende om hjælp.", bg: "Паническо телефонно обаждане \"от дъщеря ти\" може да звучи точно като нея — ридаеща, уплашена, молеща за помощ.", tr: "\"Kızından\" gelen panik dolu bir telefon, tıpatıp onun gibi gelebilir — hıçkırarak, korkmuş, yardım için yalvararak." },
        { en: "Janet wishes this were science fiction. Janet has the data. It is, sadly, not.", fr: "Janet aimerait que ce soit de la science-fiction. Mais Janet a les données. Et malheureusement, non, ce n'en est plus.", es: "Janet desearía que esto fuera ciencia ficción. Janet tiene los datos. Lamentablemente, no lo es.", de: "Janet wünschte, das wäre Science-Fiction. Janet hat die Daten. Es ist leider nicht so.", it: "Janet vorrebbe che fosse fantascienza. Janet ha i dati. Purtroppo, non lo è.", da: "Janet ville ønske, det var science fiction. Janet har data. Det er det desværre ikke.", bg: "Janet би искала това да е научна фантастика. Janet има данните. За съжаление, не е.", tr: "Janet bunun bilim kurgu olmasını isterdi. Janet'te veriler var. Maalesef öyle değil." }
      ],
      next: "signals"
    },
    signals: {
      bot: [
        { en: "Good news: spotting it is easier than it sounds. The red flags are *loud*, whether the impersonator is a CEO or a cousin.", fr: "Bonne nouvelle : repérer l'arnaque est plus simple qu'on ne pense. Les signaux d'alarme sont *gros*, que l'imposteur joue le PDG ou le cousin.", es: "Buenas noticias: detectarla es más fácil de lo que parece. Las señales de alarma son *muy llamativas*, ya sea que el impostor finja ser un CEO o un primo.", de: "Gute Nachricht: Es zu erkennen ist einfacher als gedacht. Die Warnsignale sind *laut*, ob der Hochstapler einen CEO oder einen Cousin spielt.", it: "Buona notizia: individuarla è più facile di quanto sembri. I segnali d'allarme sono *forti*, che l'impostore faccia il CEO o il cugino.", da: "Godt nyt: at spotte det er nemmere, end det lyder. Advarselslamperne er *kraftige*, uanset om bedrageren spiller CEO eller fætter.", bg: "Добра новина: разпознаването е по-лесно, отколкото звучи. Червените флагове са *крещящи*, независимо дали измамникът играе CEO или братовчед.", tr: "İyi haber: fark etmek kulağa geldiğinden çok daha kolay. Kırmızı bayraklar *gürültülüdür*, dolandırıcı ister CEO'yu ister kuzeni oynasın." },
        { en: "🚩 *Urgency + secrecy.* \"Right now, and please don't tell anyone.\"", fr: "🚩 *Urgence + secret.* \"Tout de suite, et n'en parle à personne.\"", es: "🚩 *Urgencia + secretismo.* \"Ahora mismo, y por favor no se lo digas a nadie.\"", de: "🚩 *Dringlichkeit + Geheimhaltung.* \"Sofort, und sag bitte niemandem etwas.\"", it: "🚩 *Urgenza + segretezza.* \"Subito, e per favore non dirlo a nessuno.\"", da: "🚩 *Hastværk + hemmelighed.* \"Lige nu, og sig det venligst ikke til nogen.\"", bg: "🚩 *Спешност + потайност.* \"Веднага, и моля те, не казвай на никого.\"", tr: "🚩 *Aciliyet + gizlilik.* \"Hemen şimdi ve lütfen kimseye söyleme.\"" },
        { en: "🚩 *A brand new channel.* Your son who always calls suddenly texts from an unknown number. Your boss who emails suddenly WhatsApps.", fr: "🚩 *Un canal tout neuf.* Ton fils qui appelle d'habitude t'envoie soudain un SMS d'un numéro inconnu. Ton patron qui email passe soudain par WhatsApp.", es: "🚩 *Un canal totalmente nuevo.* Tu hijo, que siempre llama, de repente te escribe desde un número desconocido. Tu jefe, que escribe correos, de repente te manda WhatsApps.", de: "🚩 *Ein brandneuer Kanal.* Dein Sohn, der sonst immer anruft, schreibt plötzlich von einer unbekannten Nummer. Dein Chef, der sonst mailt, schreibt plötzlich auf WhatsApp.", it: "🚩 *Un canale del tutto nuovo.* Tuo figlio che chiama sempre, all'improvviso ti scrive da un numero sconosciuto. Il tuo capo che manda email, all'improvviso ti scrive su WhatsApp.", da: "🚩 *En helt ny kanal.* Din søn, der altid ringer, sender pludselig en sms fra et ukendt nummer. Din chef, der mailer, skriver pludselig på WhatsApp.", bg: "🚩 *Чисто нов канал.* Синът ти, който винаги звъни, внезапно пише SMS от непознат номер. Шефът ти, който пише имейли, внезапно пише в WhatsApp.", tr: "🚩 *Yepyeni bir kanal.* Hep arayan oğlun aniden bilinmeyen bir numaradan mesaj atıyor. Hep e-posta yazan patronun aniden WhatsApp'tan yazıyor." },
        { en: "🚩 *A request that skips the usual rules.* No double-checks. No procedures. No \"let me call you back.\"", fr: "🚩 *Une demande qui zappe les règles habituelles.* Pas de vérification. Pas de procédure. Pas de \"je te rappelle.\"", es: "🚩 *Una petición que se salta las reglas habituales.* Sin verificaciones. Sin procedimientos. Sin \"déjame que te llame luego.\"", de: "🚩 *Eine Anfrage, die die üblichen Regeln umgeht.* Keine Gegenchecks. Keine Verfahren. Kein \"Ich rufe dich zurück.\"", it: "🚩 *Una richiesta che salta le regole abituali.* Niente doppi controlli. Nessuna procedura. Nessun \"ti richiamo io.\"", da: "🚩 *En anmodning, der springer de sædvanlige regler over.* Ingen dobbelttjek. Ingen procedurer. Intet \"jeg ringer tilbage.\"", bg: "🚩 *Молба, която прескача обичайните правила.* Без двойни проверки. Без процедури. Без \"ще ти звънна по-късно.\"", tr: "🚩 *Olağan kuralları atlayan bir istek.* Çift kontrol yok. Prosedür yok. \"Seni sonra ararım\" yok." },
        { en: "🚩 *The ask is money, gift cards, codes, or sensitive documents.* Almost always one of those four.", fr: "🚩 *La demande, c'est de l'argent, des cartes cadeau, des codes ou des documents sensibles.* Presque toujours l'un des quatre.", es: "🚩 *Lo que te piden es dinero, tarjetas regalo, códigos o documentos sensibles.* Casi siempre una de esas cuatro cosas.", de: "🚩 *Es geht um Geld, Geschenkkarten, Codes oder sensible Dokumente.* Fast immer eines dieser vier.", it: "🚩 *La richiesta è soldi, gift card, codici o documenti sensibili.* Quasi sempre uno di questi quattro.", da: "🚩 *Anmodningen handler om penge, gavekort, koder eller følsomme dokumenter.* Næsten altid en af de fire.", bg: "🚩 *Молбата е за пари, подаръчни карти, кодове или чувствителни документи.* Почти винаги едно от тези четири.", tr: "🚩 *İstek para, hediye kartı, kod ya da hassas belgedir.* Neredeyse her zaman bu dördünden biri." }
      ],
      next: "test"
    },
    test: {
      bot: [
        { en: "Quick scenario. Late afternoon. You get a WhatsApp from \"your husband\" (new number, profile photo missing):", fr: "Petit cas. Fin d'après-midi. Tu reçois un WhatsApp de \"ton mari\" (nouveau numéro, photo de profil manquante) :", es: "Escenario rápido. Última hora de la tarde. Recibes un WhatsApp de \"tu marido\" (número nuevo, sin foto de perfil):", de: "Schnelles Szenario. Später Nachmittag. Du bekommst eine WhatsApp von \"deinem Mann\" (neue Nummer, kein Profilbild):", it: "Scenario veloce. Tardo pomeriggio. Ricevi un WhatsApp da \"tuo marito\" (numero nuovo, foto profilo mancante):", da: "Hurtigt scenarie. Sen eftermiddag. Du får en WhatsApp fra \"din mand\" (nyt nummer, intet profilbillede):", bg: "Бърз сценарий. Късно следобед. Получаваш WhatsApp от \"съпруга ти\" (нов номер, липсваща профилна снимка):", tr: "Hızlı senaryo. Öğleden sonra geç saat. \"Kocandan\" bir WhatsApp mesajı geliyor (yeni numara, profil fotoğrafı yok):" },
        { en: "*\"Babe, my phone died, I'm at the garage and they take cards but the machine is down. Can you transfer €420 to this IBAN right now? I'll explain when I'm home, I love you.\"*", fr: "*\"Mon cœur, mon téléphone est mort, je suis chez le garagiste, ils prennent la carte mais la machine est en panne. Tu peux virer 420 € sur cet IBAN tout de suite ? J'expliquerai à la maison, je t'aime.\"*", es: "*\"Cariño, se me murió el móvil, estoy en el taller y aceptan tarjeta pero la máquina no funciona. ¿Puedes transferir 420 € a este IBAN ahora mismo? Te explico cuando llegue a casa, te quiero.\"*", de: "*\"Schatz, mein Handy ist aus, ich bin in der Werkstatt, sie nehmen Karte, aber das Gerät ist kaputt. Kannst du sofort 420 € auf diese IBAN überweisen? Ich erkläre alles, wenn ich zu Hause bin, ich liebe dich.\"*", it: "*\"Amore, il telefono è morto, sono dal meccanico, accettano la carta ma la macchina è guasta. Puoi fare un bonifico di 420 € su questo IBAN subito? Ti spiego a casa, ti amo.\"*", da: "*\"Skat, min telefon er død, jeg er på værkstedet, og de tager kort, men maskinen er nede. Kan du overføre 420 € til denne IBAN lige nu? Jeg forklarer, når jeg er hjemme, jeg elsker dig.\"*", bg: "*\"Любов, телефонът ми умря, в автосервиза съм, приемат карти, но машината им не работи. Можеш ли да преведеш 420 € на този IBAN веднага? Ще ти обясня като се прибера, обичам те.\"*", tr: "*\"Aşkım, telefonum öldü, oto serviste, kart kabul ediyorlar ama POS bozulmuş. Şu anda bu IBAN'a 420 € havale edebilir misin? Eve gelince anlatırım, seni seviyorum.\"*" },
        { en: "What do you do?", fr: "Tu fais quoi ?", es: "¿Qué haces?", de: "Was machst du?", it: "Cosa fai?", da: "Hvad gør du?", bg: "Какво правиш?", tr: "Ne yaparsın?" }
      ],
      choices: [
        { label: { en: "Call his usual number — even if it \"died\"", fr: "Je l'appelle sur son numéro habituel — même s'il est \"mort\"", es: "Llamo a su número habitual — aunque \"esté muerto\"", de: "Ich rufe seine normale Nummer an — auch wenn sie \"aus\" ist", it: "Lo chiamo sul suo numero abituale — anche se è \"morto\"", da: "Jeg ringer til hans normale nummer — selv hvis det er \"dødt\"", bg: "Звъня му на обичайния номер — дори да е \"умрял\"", tr: "Her zamanki numarasını ararım — \"ölmüş\" olsa bile" }, next: "test_right" },
        { label: { en: "Transfer — he sounds stuck", fr: "Je vire — il a l'air coincé", es: "Hago la transferencia — parece atascado", de: "Ich überweise — er klingt festgefahren", it: "Faccio il bonifico — sembra bloccato", da: "Jeg overfører — han lyder fanget", bg: "Превеждам — звучи в затруднение", tr: "Havale ederim — başı dertteymiş gibi" }, next: "test_wrong" }
      ]
    },
    test_right: {
      bot: [
        { en: "✅ Yes! Always call the *real* number first. If it really is dead, the call won't go through — costs you nothing.", fr: "✅ Oui ! Appelle toujours le *vrai* numéro d'abord. S'il est vraiment mort, l'appel ne passera pas — ça ne te coûte rien d'essayer.", es: "✅ ¡Sí! Llama siempre al número *real* primero. Si de verdad está muerto, la llamada no entrará — no te cuesta nada intentarlo.", de: "✅ Ja! Ruf immer zuerst die *echte* Nummer an. Wenn sie wirklich aus ist, kommt der Anruf nicht durch — kostet dich nichts.", it: "✅ Sì! Chiama sempre prima il numero *vero*. Se è davvero morto, la chiamata non passerà — non ti costa nulla.", da: "✅ Ja! Ring altid det *rigtige* nummer først. Hvis det virkelig er dødt, går opkaldet ikke igennem — det koster dig ingenting.", bg: "✅ Да! Винаги звъни първо на *истинския* номер. Ако наистина е \"умрял\", обаждането няма да мине — нищо не ти струва.", tr: "✅ Evet! Önce her zaman *gerçek* numarayı ara. Gerçekten ölmüşse, çağrı gitmez — sana hiçbir maliyeti olmaz." },
        { en: "If he picks up: mystery solved. If a stranger picks up: you just dodged an attack. Either way you win.", fr: "S'il décroche : mystère résolu. Si un inconnu décroche : tu viens d'éviter une attaque. Dans tous les cas, tu gagnes.", es: "Si contesta él: misterio resuelto. Si contesta un desconocido: acabas de esquivar un ataque. En cualquier caso, ganas.", de: "Wenn er drangeht: Rätsel gelöst. Wenn ein Fremder drangeht: Du hast gerade einen Angriff abgewehrt. So oder so gewinnst du.", it: "Se risponde lui: mistero risolto. Se risponde uno sconosciuto: hai appena schivato un attacco. In ogni caso, vinci.", da: "Hvis han svarer: mysteriet er løst. Hvis en fremmed svarer: du har lige undgået et angreb. Uanset hvad vinder du.", bg: "Ако вдигне той: загадката е решена. Ако вдигне непознат: току-що си избегнала атака. И в двата случая печелиш.", tr: "Açarsa: gizem çözüldü. Bir yabancı açarsa: az önce bir saldırıyı atlattın. Her halükârda kazançlısın." }
      ],
      next: "rule"
    },
    test_wrong: {
      bot: [
        { en: "I love your loyalty. Janet is moved. But please — call first.", fr: "J'adore ta loyauté. Janet est émue. Mais s'il te plaît — appelle d'abord.", es: "Me encanta tu lealtad. Janet está conmovida. Pero por favor — llama primero.", de: "Ich liebe deine Loyalität. Janet ist gerührt. Aber bitte — ruf zuerst an.", it: "Adoro la tua lealtà. Janet è commossa. Ma per favore — chiama prima.", da: "Jeg elsker din loyalitet. Janet er rørt. Men venligst — ring først.", bg: "Обожавам лоялността ти. Janet е трогната. Но моля те — първо се обади.", tr: "Sadakatine bayılıyorum. Janet duygulandı. Ama lütfen — önce ara." },
        { en: "A spouse, child, parent, or boss will never be upset that you double-checked before moving money.", fr: "Un·e conjoint·e, enfant, parent ou patron ne sera jamais fâché·e que tu aies vérifié avant d'envoyer de l'argent.", es: "Una pareja, un hijo, un padre o un jefe nunca se enfadarán porque hayas verificado antes de mover dinero.", de: "Ein·e Partner·in, ein Kind, ein Elternteil oder ein Chef wird nie sauer sein, weil du vor einer Geldbewegung nachgefragt hast.", it: "Un partner, un figlio, un genitore o un capo non saranno mai arrabbiati perché hai fatto una doppia verifica prima di muovere dei soldi.", da: "En partner, et barn, en forælder eller en chef vil aldrig blive sur over, at du har dobbelttjekket før du flyttede penge.", bg: "Партньор, дете, родител или шеф никога няма да се ядоса, че си проверила два пъти, преди да преведеш пари.", tr: "Bir eş, çocuk, anne-baba ya da patron, sen para göndermeden önce çift kontrol ettiğin için asla sinirlenmez." },
        { en: "An impostor, on the other hand, will *hate* it. That alone tells you something.", fr: "Un imposteur, en revanche, va *détester* ça. À lui seul, ce détail t'en dit long.", es: "Un impostor, en cambio, lo *odiará*. Eso solo ya te dice algo.", de: "Ein Betrüger hingegen wird das *hassen*. Allein das sagt schon einiges.", it: "Un impostore, invece, lo *odierà*. Già solo questo ti dice qualcosa.", da: "En bedrager vil derimod *hade* det. Det alene siger dig noget.", bg: "Измамникът, от друга страна, ще *мрази* това. Само това ти казва нещо.", tr: "Bir sahtekâr ise bundan *nefret eder*. Bu bile sana bir şey anlatır." }
      ],
      next: "rule"
    },
    rule: {
      bot: [
        { en: "Universal rule: *use a second channel.* Always. Every time. Forever.", fr: "Règle universelle : *utilise un second canal.* Toujours. À chaque fois. Pour toujours.", es: "Regla universal: *usa un segundo canal.* Siempre. Cada vez. Para siempre.", de: "Universelle Regel: *Nutze einen zweiten Kanal.* Immer. Jedes Mal. Für immer.", it: "Regola universale: *usa un secondo canale.* Sempre. Ogni volta. Per sempre.", da: "Universel regel: *brug en anden kanal.* Altid. Hver gang. For evigt.", bg: "Универсално правило: *използвай втори канал.* Винаги. Всеки път. Завинаги.", tr: "Evrensel kural: *ikinci bir kanal kullan.* Her zaman. Her seferinde. Sonsuza dek." },
        { en: "📞 Got a weird text from your son? *Call his old number.*", fr: "📞 SMS bizarre de ton fils ? *Appelle son ancien numéro.*", es: "📞 ¿SMS raro de tu hijo? *Llama a su número de siempre.*", de: "📞 Komische SMS von deinem Sohn? *Ruf seine alte Nummer an.*", it: "📞 SMS strano da tuo figlio? *Chiama il suo vecchio numero.*", da: "📞 Mærkelig sms fra din søn? *Ring til hans gamle nummer.*", bg: "📞 Странен SMS от сина ти? *Звънни на стария му номер.*", tr: "📞 Oğlundan tuhaf bir mesaj mı geldi? *Eski numarasını ara.*" },
        { en: "📞 Got a weird email from your boss? *Call her desk or message her on the usual app.*", fr: "📞 Email bizarre de ta cheffe ? *Appelle son poste, ou écris-lui sur l'appli habituelle.*", es: "📞 ¿Correo raro de tu jefa? *Llama a su despacho o escríbele por la app de siempre.*", de: "📞 Komische E-Mail von deiner Chefin? *Ruf an ihrem Schreibtisch an oder schreib ihr in der üblichen App.*", it: "📞 Email strana dalla tua capa? *Chiamala in ufficio o scrivile sull'app abituale.*", da: "📞 Mærkelig e-mail fra din chef? *Ring til hendes kontor, eller skriv på den sædvanlige app.*", bg: "📞 Странен имейл от шефката ти? *Звънни ѝ на работния телефон или ѝ пиши в обичайното приложение.*", tr: "📞 Patronundan tuhaf bir e-posta mı geldi? *Ofis hattını ara ya da her zamanki uygulamadan yaz.*" },
        { en: "📞 Got a panicked voice call from \"family\"? *Hang up and call them back yourself.*", fr: "📞 Appel paniqué d'un membre de la \"famille\" ? *Raccroche et rappelle-les toi-même.*", es: "📞 ¿Llamada desesperada de un \"familiar\"? *Cuelga y llámale tú directamente.*", de: "📞 Panischer Anruf von der \"Familie\"? *Auflegen und selbst zurückrufen.*", it: "📞 Telefonata in preda al panico da un \"familiare\"? *Riattacca e richiamali tu.*", da: "📞 Panisk opkald fra \"familie\"? *Læg på, og ring selv tilbage til dem.*", bg: "📞 Паническо обаждане от \"роднина\"? *Затвори и ги набери ти самата.*", tr: "📞 \"Aileden\" panik dolu bir telefon mu geldi? *Kapat ve onları sen geri ara.*" },
        { en: "Set up a *family safeword* with the people you love. If a panicked \"daughter\" can't say the word, it isn't her.", fr: "Mets en place un *mot de passe familial* avec tes proches. Si une \"fille\" en panique n'arrive pas à le donner, ce n'est pas elle.", es: "Establece una *contraseña familiar* con tus seres queridos. Si una \"hija\" en pánico no puede decirla, no es ella.", de: "Vereinbart ein *Familien-Codewort* mit den Menschen, die du liebst. Wenn eine panische \"Tochter\" das Wort nicht sagen kann, ist sie es nicht.", it: "Stabilisci una *parola d'ordine di famiglia* con le persone che ami. Se una \"figlia\" in preda al panico non la sa dire, non è lei.", da: "Aftal et *familiekodeord* med dine kære. Hvis en panisk \"datter\" ikke kan sige ordet, er det ikke hende.", bg: "Уговори си *семейна парола* с близките си. Ако паническа \"дъщеря\" не може да я каже, не е тя.", tr: "Sevdiklerinle bir *aile parolası* belirle. Panikleyen bir \"kız\" parolayı söyleyemiyorsa, o kız değildir." },
        { en: "Janet suggests something easy to say and hard to guess. Like \"aubergine,\" or \"pickle,\" or the name of your second-favorite cousin.", fr: "Janet suggère quelque chose de facile à dire et difficile à deviner. Comme \"aubergine\", ou \"cornichon\", ou le prénom de ton·ta deuxième cousin·e préféré·e.", es: "Janet sugiere algo fácil de decir y difícil de adivinar. Como \"berenjena\", \"pepinillo\" o el nombre de tu segundo primo favorito.", de: "Janet schlägt etwas vor, das leicht zu sagen und schwer zu erraten ist. Wie \"Aubergine\", \"Gurke\" oder den Namen deines zweitliebsten Cousins.", it: "Janet suggerisce qualcosa di facile da dire e difficile da indovinare. Tipo \"melanzana\", o \"cetriolino\", o il nome del tuo secondo cugino preferito.", da: "Janet foreslår noget, der er let at sige og svært at gætte. Som \"aubergine\", \"agurk\" eller navnet på din næst-yndlingsfætter.", bg: "Janet предлага нещо лесно за казване и трудно за отгатване. Като \"патладжан\", \"кисела краставичка\" или името на втория ти най-любим братовчед.", tr: "Janet, söylemesi kolay, tahmin etmesi zor bir şey öneriyor. Mesela \"patlıcan\", \"turşu\" ya da ikinci en sevdiğin kuzenin adı." }
      ],
      choices: [{ label: { en: "Setting up a safeword tonight", fr: "Je prépare un mot de passe ce soir", es: "Esta noche preparo una contraseña", de: "Heute Abend lege ich ein Codewort fest", it: "Stasera preparo una parola d'ordine", da: "Jeg laver et kodeord i aften", bg: "Тази вечер ще уговоря парола", tr: "Bu akşam bir parola belirliyorum" }, next: "outro" }]
    },
    outro: {
      bot: [
        { en: "Janet's TL;DR: urgent + secret + money or codes = call the real person, do not reply.", fr: "Le résumé de Janet : urgent + secret + argent ou codes = on appelle la vraie personne, on ne répond pas.", es: "TL;DR de Janet: urgente + secreto + dinero o códigos = llama a la persona real, no respondas.", de: "Janets TL;DR: dringend + geheim + Geld oder Codes = die echte Person anrufen, nicht antworten.", it: "Il TL;DR di Janet: urgente + segreto + soldi o codici = chiama la persona vera, non rispondere.", da: "Janets TL;DR: presserende + hemmeligt + penge eller koder = ring til den rigtige person, svar ikke.", bg: "TL;DR от Janet: спешно + тайно + пари или кодове = звънни на истинския човек, не отговаряй.", tr: "Janet'in TL;DR'ı: acil + gizli + para ya da kod = gerçek kişiyi ara, cevap verme." },
        { en: "Somewhere in the universe, you may have just spared yourself a heartbreak — or rescued a company's quarter. Either way, Janet is, statistically, very pleased. Bye for now! 🎭", fr: "Quelque part dans l'univers, tu viens peut-être de t'épargner un gros chagrin — ou de sauver le trimestre d'une entreprise. Dans tous les cas, statistiquement parlant, Janet est ravie. À très vite ! 🎭", es: "En algún rincón del universo, quizás acabas de ahorrarte un disgusto — o de salvar el trimestre de una empresa. Sea como sea, Janet, estadísticamente, está encantada. ¡Hasta pronto! 🎭", de: "Irgendwo im Universum hast du dir vielleicht gerade Herzschmerz erspart — oder das Quartal einer Firma gerettet. So oder so ist Janet, statistisch gesehen, sehr zufrieden. Bis bald! 🎭", it: "Da qualche parte nell'universo, ti sei forse appena risparmiato un crepacuore — o hai salvato il trimestre di un'azienda. In entrambi i casi, Janet, statisticamente, è molto contenta. A presto! 🎭", da: "Et eller andet sted i universet har du måske lige sparet dig selv for hjertesorg — eller reddet en virksomheds kvartal. Uanset hvad er Janet, statistisk set, meget tilfreds. Hej så længe! 🎭", bg: "Някъде във Вселената току-що може да си си спестила сърдечна болка — или да си спасила тримесечието на цяла компания. И в двата случая Janet, статистически, е много доволна. До скоро! 🎭", tr: "Evrenin bir yerinde, kendini bir gönül yarasından kurtarmış olabilirsin — ya da bir şirketin çeyreğini kurtarmış olabilirsin. Her iki durumda da Janet, istatistiksel olarak, çok memnun. Şimdilik hoşça kal! 🎭" }
      ],
      end: true
    }
  }
};
