window.JANET_COURSES = window.JANET_COURSES || {};
window.JANET_COURSES.digital_footprint = {
  id: "digital_footprint",
  emoji: "👣",
  duration: 4,
  karma: 40,
  title: {
    en: "Digital footprint",
    fr: "Empreinte numérique",
    es: "Huella digital",
    de: "Digitaler Fußabdruck",
    it: "Impronta digitale",
    da: "Digitalt fodaftryk",
    bg: "Дигитален отпечатък",
    tr: "Dijital ayak izi"
  },
  description: {
    en: "The trail you leave online — and how to make it smaller.",
    fr: "Les traces que tu laisses en ligne — et comment les réduire.",
    es: "El rastro que dejas en línea — y cómo reducirlo.",
    de: "Die Spur, die du online hinterlässt — und wie du sie kleiner machst.",
    it: "La traccia che lasci online — e come renderla più piccola.",
    da: "Det spor, du efterlader online — og hvordan du gør det mindre.",
    bg: "Следата, която оставяш онлайн — и как да я направиш по-малка.",
    tr: "İnternette bıraktığın iz — ve onu nasıl küçültürsün."
  },
  startNode: "start",
  nodes: {
    start: {
      bot: [
        { en: "Hi there! Janet here.", fr: "Salut ! C'est Janet.", es: "¡Hola! Soy Janet.", de: "Hallo! Janet hier.", it: "Ciao! Sono Janet.", da: "Hej! Det er Janet.", bg: "Здравей! Аз съм Janet.", tr: "Merhaba! Ben Janet." },
        { en: "Did you know — and this is a real number, I checked — every time you click, post, sign up, or simply exist online, you leave a tiny trail?", fr: "Tu savais — et c'est un vrai chiffre, j'ai vérifié — qu'à chaque clic, chaque post, chaque inscription, ou juste en existant en ligne, tu laisses une petite trace ?", es: "¿Sabías — y es un número real, lo he comprobado — que cada vez que haces clic, publicas, te registras o simplemente existes en línea, dejas un pequeño rastro?", de: "Wusstest du — und das ist eine echte Zahl, ich habe nachgesehen — dass du jedes Mal, wenn du klickst, postest, dich anmeldest oder einfach online existierst, eine kleine Spur hinterlässt?", it: "Lo sapevi — ed è un numero vero, ho controllato — che ogni volta che clicchi, pubblichi, ti iscrivi o semplicemente esisti online, lasci una piccola traccia?", da: "Vidste du — og det er et rigtigt tal, jeg har tjekket — at hver gang du klikker, poster, tilmelder dig eller bare eksisterer online, efterlader du et lille spor?", bg: "Знаеше ли — и това е реално число, проверих — че всеки път, когато кликаш, публикуваш, регистрираш се или просто съществуваш онлайн, оставяш малка следа?", tr: "Biliyor muydun — ki bu gerçek bir rakam, kontrol ettim — her tıkladığında, paylaştığında, kayıt olduğunda ya da sadece internette var olduğunda küçücük bir iz bırakıyorsun?" },
        { en: "That trail is your *digital footprint*. Some of it was your idea. A lot of it was, frankly, not.", fr: "Cette trace, c'est ton *empreinte numérique*. Une partie, c'est toi qui l'as voulue. Une grosse partie, franchement, pas du tout.", es: "Ese rastro es tu *huella digital*. Parte fue idea tuya. Y gran parte, sinceramente, no.", de: "Diese Spur ist dein *digitaler Fußabdruck*. Manches davon war deine Idee. Vieles davon, ehrlich gesagt, nicht.", it: "Quella traccia è la tua *impronta digitale*. Parte è stata una tua scelta. Buona parte, francamente, no.", da: "Det spor er dit *digitale fodaftryk*. Noget af det var din idé. Meget af det var, ærligt talt, ikke.", bg: "Тази следа е твоят *дигитален отпечатък*. Част от него е твоя идея. Голяма част, честно казано, не е.", tr: "Bu iz senin *dijital ayak izin*. Bir kısmı senin fikrindi. Büyük bir kısmı, açıkçası, hiç değildi." }
      ],
      choices: [{ label: { en: "What's in it?", fr: "Qu'est-ce qu'il y a dedans ?", es: "¿Qué contiene?", de: "Was steckt drin?", it: "Cosa c'è dentro?", da: "Hvad er der i den?", bg: "Какво има в него?", tr: "İçinde ne var?" }, next: "active" }]
    },
    active: {
      bot: [
        { en: "Two flavors of footprint.", fr: "Deux types d'empreinte.", es: "Dos sabores de huella.", de: "Zwei Sorten Fußabdruck.", it: "Due tipi di impronta.", da: "To slags fodaftryk.", bg: "Два вида отпечатъци.", tr: "İki çeşit ayak izi var." },
        { en: "✍️ *Active* — things you posted on purpose. Tweets, photos, comments, dating profiles, that one blog you forgot.", fr: "✍️ *Active* — ce que tu as posté volontairement. Tweets, photos, commentaires, profils de rencontre, ce blog que tu as oublié.", es: "✍️ *Activa* — cosas que publicaste a propósito. Tuits, fotos, comentarios, perfiles de citas, ese blog que olvidaste.", de: "✍️ *Aktiv* — was du absichtlich gepostet hast. Tweets, Fotos, Kommentare, Dating-Profile, dieser eine vergessene Blog.", it: "✍️ *Attiva* — cose che hai pubblicato di proposito. Tweet, foto, commenti, profili di dating, quel blog che hai dimenticato.", da: "✍️ *Aktivt* — ting du har postet med vilje. Tweets, billeder, kommentarer, datingprofiler, den blog du glemte.", bg: "✍️ *Активен* — неща, които си публикувал·а нарочно. Туитове, снимки, коментари, профили за запознанства, онзи блог, който си забравил·а.", tr: "✍️ *Aktif* — bilinçli olarak paylaştığın şeyler. Tweet'ler, fotoğraflar, yorumlar, flört profilleri, unuttuğun o blog." },
        { en: "🛰️ *Passive* — things collected about you without you noticing. Cookies, location data, every \"accept all\" you clicked.", fr: "🛰️ *Passive* — ce que d'autres collectent à ton insu. Cookies, position, chaque \"accepter tout\" cliqué sans lire.", es: "🛰️ *Pasiva* — cosas recopiladas sobre ti sin que te enteres. Cookies, datos de ubicación, cada \"aceptar todo\" que pulsaste.", de: "🛰️ *Passiv* — was unbemerkt über dich gesammelt wird. Cookies, Standortdaten, jedes \"Alle akzeptieren\", das du angeklickt hast.", it: "🛰️ *Passiva* — cose raccolte su di te senza che te ne accorga. Cookie, dati di posizione, ogni \"accetta tutto\" che hai cliccato.", da: "🛰️ *Passivt* — ting der bliver indsamlet om dig uden at du opdager det. Cookies, lokationsdata, hvert eneste \"acceptér alle\" du har klikket.", bg: "🛰️ *Пасивен* — неща, които се събират за теб, без да забележиш. Бисквитки, данни за местоположение, всяко \"приеми всички\", което си щракнал·а.", tr: "🛰️ *Pasif* — sen fark etmeden hakkında toplanan şeyler. Çerezler, konum verisi, tıkladığın her \"tümünü kabul et\" tuşu." }
      ],
      next: "stalk"
    },
    stalk: {
      bot: [
        { en: "Try this — search your full name, in quotes, on Google. Then on Bing. Then on DuckDuckGo.", fr: "Essaie : cherche ton nom complet entre guillemets sur Google. Puis sur Bing. Puis sur DuckDuckGo.", es: "Prueba esto: busca tu nombre completo entre comillas en Google. Luego en Bing. Luego en DuckDuckGo.", de: "Versuch das mal: such deinen vollständigen Namen in Anführungszeichen bei Google. Dann bei Bing. Dann bei DuckDuckGo.", it: "Prova questo: cerca il tuo nome completo tra virgolette su Google. Poi su Bing. Poi su DuckDuckGo.", da: "Prøv det her — søg dit fulde navn i anførselstegn på Google. Så på Bing. Så på DuckDuckGo.", bg: "Опитай това — потърси пълното си име в кавички в Google. После в Bing. После в DuckDuckGo.", tr: "Şunu dene — tam adını tırnak içinde Google'da ara. Sonra Bing'de. Sonra DuckDuckGo'da." },
        { en: "Add your city. Your old school. Your job. Be your own stalker for ten minutes.", fr: "Ajoute ta ville. Ton ancienne école. Ton boulot. Sois ton propre détective pendant 10 minutes.", es: "Añade tu ciudad. Tu antiguo colegio. Tu trabajo. Sé tu propio stalker durante diez minutos.", de: "Füg deine Stadt hinzu. Deine alte Schule. Deinen Job. Sei zehn Minuten lang dein eigener Stalker.", it: "Aggiungi la tua città. La tua vecchia scuola. Il tuo lavoro. Sii il tuo stalker per dieci minuti.", da: "Tilføj din by. Din gamle skole. Dit job. Vær din egen stalker i ti minutter.", bg: "Добави града си. Старото си училище. Работата си. Бъди свой собствен сталкер за десет минути.", tr: "Şehrini ekle. Eski okulunu. İşini. On dakika boyunca kendi stalker'ın ol." },
        { en: "What you find — anyone can find.", fr: "Ce que tu trouves — n'importe qui peut le trouver.", es: "Lo que encuentres — cualquiera puede encontrarlo.", de: "Was du findest — kann jeder finden.", it: "Quello che trovi — può trovarlo chiunque.", da: "Det du finder — kan alle finde.", bg: "Това, което намериш — всеки може да го намери.", tr: "Senin bulduğunu — herkes bulabilir." }
      ],
      next: "stalk_check"
    },
    stalk_check: {
      bot: [
        { en: "Quick check — have you ever actually googled yourself?", fr: "Petite question — tu t'es déjà vraiment googlé·e ?", es: "Pregunta rápida — ¿alguna vez te has buscado en Google de verdad?", de: "Kurze Frage — hast du dich schon mal wirklich gegoogelt?", it: "Domanda veloce — ti sei mai davvero cercato·a su Google?", da: "Hurtigt tjek — har du nogensinde rigtigt googlet dig selv?", bg: "Бърза проверка — наистина ли си се търсил·а в Google?", tr: "Kısa bir kontrol — daha önce gerçekten kendini Google'da arattın mı?" }
      ],
      choices: [
        { label: { en: "Yes — and I was a little shocked", fr: "Oui — et j'ai été un peu choqué·e", es: "Sí — y me quedé algo en shock", de: "Ja — und ich war etwas geschockt", it: "Sì — e sono rimasto·a un po' scioccato·a", da: "Ja — og jeg blev lidt chokeret", bg: "Да — и бях леко шокиран·а", tr: "Evet — ve biraz şaşırdım" }, next: "why", reaction: { en: "Welcome to the club. Selon mes registres, that reaction is very common.", fr: "Bienvenue au club. Selon mes registres, cette réaction est très fréquente.", es: "Bienvenido·a al club. Según mis registros, esa reacción es muy común.", de: "Willkommen im Club. Laut meinen Aufzeichnungen ist diese Reaktion sehr verbreitet.", it: "Benvenuto·a nel club. Secondo i miei archivi, quella reazione è molto comune.", da: "Velkommen i klubben. Ifølge mine optegnelser er den reaktion meget almindelig.", bg: "Добре дошъл·дошла в клуба. Според моите регистри, тази реакция е много често срещана.", tr: "Kulübe hoş geldin. Kayıtlarıma göre, bu tepki oldukça yaygın." } },
        { label: { en: "Yes — boring, found nothing", fr: "Oui — bof, j'ai rien trouvé", es: "Sí — aburrido, no encontré nada", de: "Ja — langweilig, nichts gefunden", it: "Sì — noioso, non ho trovato nulla", da: "Ja — kedeligt, fandt intet", bg: "Да — скучно, нищо не намерих", tr: "Evet — sıkıcı, hiçbir şey bulamadım" }, next: "why", reaction: { en: "Lucky, or well-hidden. Both count.", fr: "Chance, ou bonne discrétion. Les deux comptent.", es: "Suerte, o bien escondido·a. Las dos valen.", de: "Glück gehabt oder gut versteckt. Beides zählt.", it: "Fortunato·a o ben nascosto·a. Entrambe contano.", da: "Heldig eller godt gemt. Begge tæller.", bg: "Късмет или добре скрит·а. И двете се броят.", tr: "Şanslı ya da iyi gizlenmişsin. İkisi de sayılır." } },
        { label: { en: "Never — too scared", fr: "Jamais — trop peur", es: "Nunca — me da miedo", de: "Nie — zu viel Angst", it: "Mai — troppa paura", da: "Aldrig — for bange", bg: "Никога — твърде ме е страх", tr: "Hiç — çok korkuyorum" }, next: "why", reaction: { en: "Honest answer. Maybe today's the day.", fr: "Réponse honnête. C'est peut-être le bon jour.", es: "Respuesta sincera. Quizá hoy sea el día.", de: "Ehrliche Antwort. Vielleicht ist heute der Tag.", it: "Risposta onesta. Magari oggi è il giorno giusto.", da: "Ærligt svar. Måske er i dag dagen.", bg: "Честен отговор. Може днес да е денят.", tr: "Dürüst cevap. Belki bugün o gündür." } }
      ]
    },
    why: {
      bot: [
        { en: "Why care? Three reasons:", fr: "Pourquoi s'en soucier ? Trois raisons :", es: "¿Por qué importa? Tres razones:", de: "Warum sich kümmern? Drei Gründe:", it: "Perché importa? Tre motivi:", da: "Hvorfor bekymre sig? Tre grunde:", bg: "Защо да те интересува? Три причини:", tr: "Neden umurunda olsun? Üç neden:" },
        { en: "🎯 Scammers use your footprint to write convincing phishing messages.", fr: "🎯 Les arnaqueurs s'en servent pour rédiger des messages crédibles.", es: "🎯 Los estafadores usan tu huella para redactar mensajes de phishing convincentes.", de: "🎯 Betrüger nutzen deinen Fußabdruck, um überzeugende Phishing-Nachrichten zu schreiben.", it: "🎯 I truffatori usano la tua impronta per scrivere messaggi di phishing credibili.", da: "🎯 Svindlere bruger dit fodaftryk til at skrive overbevisende phishing-beskeder.", bg: "🎯 Измамниците използват отпечатъка ти, за да пишат убедителни phishing съобщения.", tr: "🎯 Dolandırıcılar inandırıcı phishing mesajları yazmak için ayak izini kullanır." },
        { en: "🕵️ Strangers (employers, dates, the curious) build a story of you in five clicks.", fr: "🕵️ Des inconnus (recruteurs, dates, curieux) bâtissent une image de toi en cinq clics.", es: "🕵️ Desconocidos (empleadores, citas, curiosos) construyen una historia sobre ti en cinco clics.", de: "🕵️ Fremde (Arbeitgeber, Dates, Neugierige) bauen sich in fünf Klicks eine Geschichte über dich zusammen.", it: "🕵️ Estranei (datori di lavoro, appuntamenti, curiosi) costruiscono una tua storia in cinque clic.", da: "🕵️ Fremmede (arbejdsgivere, dates, nysgerrige) bygger en historie om dig på fem klik.", bg: "🕵️ Непознати (работодатели, срещи, любопитни) изграждат история за теб с пет клика.", tr: "🕵️ Yabancılar (işverenler, çıktığın kişiler, meraklılar) seninle ilgili bir hikâyeyi beş tıkta kurar." },
        { en: "🏚️ Some of it is wildly out of date or wrong — and represents you anyway.", fr: "🏚️ Une partie est complètement périmée ou carrément fausse — et te représente quand même.", es: "🏚️ Algunas cosas están totalmente desfasadas o son erróneas — y aun así te representan.", de: "🏚️ Manches ist völlig veraltet oder falsch — und repräsentiert dich trotzdem.", it: "🏚️ Alcune cose sono completamente datate o sbagliate — e ti rappresentano comunque.", da: "🏚️ Noget af det er voldsomt forældet eller forkert — og repræsenterer dig alligevel.", bg: "🏚️ Част от него е силно остаряла или грешна — и пак те представя.", tr: "🏚️ Bazıları fena halde eski ya da yanlış — ama yine de seni temsil ediyor." }
      ],
      next: "fact_sun"
    },
    fact_sun: {
      bot: [
        { en: "(Tiny aside, totally unrelated: light from the Sun takes about *8 minutes and 20 seconds* to reach Earth. So the sunlight on your face right now is, technically, slightly out of date.)", fr: "(Petite parenthèse, rien à voir : la lumière du Soleil met environ *8 minutes et 20 secondes* à atteindre la Terre. Du coup, le rayon sur ton visage est techniquement un peu périmé.)", es: "(Pequeño inciso totalmente sin relación: la luz del Sol tarda unos *8 minutos y 20 segundos* en llegar a la Tierra. Así que el rayo de sol en tu cara ahora mismo está, técnicamente, ligeramente desfasado.)", de: "(Kleine Randnotiz, völlig unzusammenhängend: das Licht der Sonne braucht etwa *8 Minuten und 20 Sekunden*, um die Erde zu erreichen. Das Sonnenlicht auf deinem Gesicht ist also technisch gesehen leicht veraltet.)", it: "(Piccola parentesi, totalmente fuori tema: la luce del Sole impiega circa *8 minuti e 20 secondi* per raggiungere la Terra. Quindi il raggio sul tuo viso in questo momento è, tecnicamente, leggermente fuori data.)", da: "(Lille sidebemærkning, helt urelateret: lyset fra Solen er omkring *8 minutter og 20 sekunder* om at nå Jorden. Så sollyset på dit ansigt lige nu er teknisk set en smule forældet.)", bg: "(Малко отклонение, напълно несвързано: светлината от Слънцето отнема около *8 минути и 20 секунди*, за да достигне Земята. Така че слънчевият лъч на лицето ти в момента е, технически, леко остарял.)", tr: "(Küçük bir parantez, konuyla hiç ilgisi yok: Güneş'ten gelen ışık Dünya'ya ulaşmak için yaklaşık *8 dakika 20 saniye* sürer. Yani şu an yüzündeki güneş ışığı, teknik olarak, hafifçe güncelliğini yitirmiş durumda.)" },
        { en: "Anyway! Back to your data.", fr: "Bref ! Retour à tes données.", es: "¡En fin! Volvamos a tus datos.", de: "Wie auch immer! Zurück zu deinen Daten.", it: "Comunque! Torniamo ai tuoi dati.", da: "Nå men! Tilbage til dine data.", bg: "Както и да е! Връщаме се към твоите данни.", tr: "Neyse! Verilerine geri dönelim." }
      ],
      next: "audit_habit"
    },
    audit_habit: {
      bot: [
        { en: "Honestly — when was the last time you cleaned out an old account you don't use anymore?", fr: "Honnêtement — c'était quand la dernière fois que tu as supprimé un vieux compte que tu n'utilises plus ?", es: "Sinceramente — ¿cuándo limpiaste por última vez una cuenta vieja que ya no usas?", de: "Mal ehrlich — wann hast du das letzte Mal einen alten Account aufgeräumt, den du nicht mehr nutzt?", it: "Sinceramente — quand'è stata l'ultima volta che hai ripulito un vecchio account che non usi più?", da: "Helt ærligt — hvornår ryddede du sidst op i en gammel konto, du ikke bruger længere?", bg: "Честно — кога за последно изчисти стар акаунт, който вече не използваш?", tr: "Dürüstçe — kullanmadığın eski bir hesabı en son ne zaman temizledin?" }
      ],
      choices: [
        { label: { en: "This year — I do it regularly", fr: "Cette année — je le fais régulièrement", es: "Este año — lo hago regularmente", de: "Dieses Jahr — ich mache das regelmäßig", it: "Quest'anno — lo faccio regolarmente", da: "I år — jeg gør det regelmæssigt", bg: "Тази година — правя го редовно", tr: "Bu yıl — düzenli yapıyorum" }, next: "actions", reaction: { en: "✅ Janet approves. Top tier behavior.", fr: "✅ Janet approuve. Comportement de très haut niveau.", es: "✅ Janet aprueba. Comportamiento de élite.", de: "✅ Janet stimmt zu. Verhalten der Spitzenklasse.", it: "✅ Janet approva. Comportamento di alto livello.", da: "✅ Janet bifalder. Topadfærd.", bg: "✅ Janet одобрява. Поведение от висока класа.", tr: "✅ Janet onaylar. Üst düzey davranış." } },
        { label: { en: "Years ago, maybe", fr: "Il y a des années, peut-être", es: "Hace años, quizá", de: "Vor Jahren, vielleicht", it: "Anni fa, forse", da: "For år siden, måske", bg: "Преди години, може би", tr: "Yıllar önce, belki" }, next: "actions", reaction: { en: "Honest answer. Most humans live here.", fr: "Réponse honnête. La plupart des humains sont dans ce cas.", es: "Respuesta sincera. La mayoría de los humanos vivimos ahí.", de: "Ehrliche Antwort. Hier wohnen die meisten Menschen.", it: "Risposta onesta. La maggior parte degli umani sta qui.", da: "Ærligt svar. De fleste mennesker bor her.", bg: "Честен отговор. Повечето хора живеят тук.", tr: "Dürüst cevap. İnsanların çoğu burada yaşar." } },
        { label: { en: "Never — I have no idea what's still out there", fr: "Jamais — j'ai aucune idée de ce qui traîne encore", es: "Nunca — no tengo idea de qué sigue por ahí", de: "Nie — keine Ahnung, was da draußen noch rumschwirrt", it: "Mai — non ho idea di cosa ci sia ancora in giro", da: "Aldrig — jeg aner ikke, hvad der stadig er derude", bg: "Никога — нямам представа какво още е там навън", tr: "Hiç — hâlâ ne dolaşıyor bilmiyorum" }, next: "actions", reaction: { en: "OK — Janet keeps a note for the next pass.", fr: "OK — Janet garde une note pour la prochaine fois.", es: "Vale — Janet toma nota para la próxima.", de: "OK — Janet notiert sich das für den nächsten Durchgang.", it: "OK — Janet prende nota per il prossimo giro.", da: "OK — Janet noterer det til næste gennemgang.", bg: "Окей — Janet си записва за следващия път.", tr: "Tamam — Janet bir sonraki tur için not alır." } }
      ]
    },
    actions: {
      bot: [
        { en: "Three concrete moves:", fr: "Trois actions concrètes :", es: "Tres acciones concretas:", de: "Drei konkrete Schritte:", it: "Tre azioni concrete:", da: "Tre konkrete handlinger:", bg: "Три конкретни действия:", tr: "Üç somut hamle:" },
        { en: "1. *Delete what you can.* Old social accounts, ancient forum profiles, abandoned dating apps.", fr: "1. *Supprime ce que tu peux.* Vieux comptes sociaux, profils de forums anciens, applis de rencontre dormantes.", es: "1. *Borra lo que puedas.* Cuentas sociales viejas, perfiles de foros antiguos, apps de citas abandonadas.", de: "1. *Lösche, was du kannst.* Alte Social-Accounts, uralte Forenprofile, vergessene Dating-Apps.", it: "1. *Cancella quello che puoi.* Vecchi account social, profili di forum antichi, app di dating abbandonate.", da: "1. *Slet hvad du kan.* Gamle sociale konti, ældgamle forumprofiler, opgivne datingapps.", bg: "1. *Изтрий каквото можеш.* Стари социални акаунти, древни форум профили, изоставени приложения за запознанства.", tr: "1. *Silebileceğini sil.* Eski sosyal medya hesapları, kadim forum profilleri, terk edilmiş flört uygulamaları." },
        { en: "2. *Lock what you keep.* Switch socials to private. Limit who sees old posts.", fr: "2. *Verrouille ce que tu gardes.* Passe en privé. Limite qui voit tes vieux posts.", es: "2. *Bloquea lo que conserves.* Pon tus redes en privado. Limita quién ve las publicaciones antiguas.", de: "2. *Sperre ab, was du behältst.* Stell die Socials auf privat. Beschränke, wer alte Posts sieht.", it: "2. *Blocca quello che tieni.* Metti i social in privato. Limita chi vede i vecchi post.", da: "2. *Lås det du beholder.* Sæt dine sociale medier til privat. Begræns hvem der kan se gamle opslag.", bg: "2. *Заключи това, което запазваш.* Превключи социалните мрежи на частни. Ограничи кой вижда старите ти публикации.", tr: "2. *Tuttuklarını kilitle.* Sosyal medyayı gizliye al. Eski gönderileri kimin görebildiğini kısıtla." },
        { en: "3. *Search-and-correct.* If you find old wrong info, contact the site to remove or update it. Most will.", fr: "3. *Cherche et corrige.* Une info fausse ou obsolète ? Contacte le site pour la retirer ou la mettre à jour. La plupart le font.", es: "3. *Busca y corrige.* Si encuentras información antigua o errónea, contacta con el sitio para que la elimine o actualice. La mayoría lo hará.", de: "3. *Suchen und korrigieren.* Findest du alte oder falsche Infos, kontaktiere die Seite zum Löschen oder Aktualisieren. Die meisten machen mit.", it: "3. *Cerca e correggi.* Se trovi informazioni vecchie o sbagliate, contatta il sito perché le rimuova o le aggiorni. La maggior parte lo fa.", da: "3. *Søg og ret.* Hvis du finder gammel forkert info, så kontakt siden for at få den fjernet eller opdateret. De fleste gør det.", bg: "3. *Търси и коригирай.* Намериш ли стара или грешна информация, свържи се със сайта, за да я премахне или обнови. Повечето ще го направят.", tr: "3. *Ara ve düzelt.* Eski ya da yanlış bilgi bulursan, siteyle iletişime geç ve kaldırmasını ya da güncellemesini iste. Çoğu yapar." }
      ],
      next: "gdpr"
    },
    gdpr: {
      bot: [
        { en: "If you're in the EU, you have a magic spell: *right to be forgotten*. You can demand sites delete personal info about you.", fr: "Dans l'UE, tu as une formule magique : le *droit à l'oubli*. Tu peux exiger qu'un site supprime tes infos personnelles.", es: "Si estás en la UE, tienes un conjuro mágico: el *derecho al olvido*. Puedes exigir que los sitios borren tu información personal.", de: "In der EU hast du einen Zauberspruch: das *Recht auf Vergessenwerden*. Du kannst von Seiten verlangen, persönliche Infos über dich zu löschen.", it: "Se sei nell'UE, hai una formula magica: il *diritto all'oblio*. Puoi chiedere ai siti di cancellare le tue informazioni personali.", da: "Hvis du er i EU, har du en magisk formel: *retten til at blive glemt*. Du kan kræve, at sider sletter personlige oplysninger om dig.", bg: "Ако си в ЕС, имаш магическо заклинание: *правото да бъдеш забравен*. Можеш да изискваш сайтовете да изтрият личните ти данни.", tr: "AB'deysen, sihirli bir büyün var: *unutulma hakkı*. Sitelerden senin hakkındaki kişisel bilgileri silmelerini talep edebilirsin." },
        { en: "Google even has a form. You're welcome.", fr: "Google a même un formulaire pour ça. De rien.", es: "Google incluso tiene un formulario. De nada.", de: "Google hat sogar ein Formular dafür. Gern geschehen.", it: "Google ha persino un modulo apposito. Prego.", da: "Google har endda en formular til det. Selv tak.", bg: "Google дори има формуляр за това. Няма за какво.", tr: "Google'ın bunun için bir formu bile var. Rica ederim." }
      ],
      choices: [{ label: { en: "I'll do an audit this month", fr: "Je fais le ménage ce mois-ci", es: "Haré una revisión este mes", de: "Ich mache diesen Monat eine Bestandsaufnahme", it: "Faccio un controllo questo mese", da: "Jeg laver et tjek denne måned", bg: "Ще направя ревизия този месец", tr: "Bu ay bir denetim yapacağım" }, next: "outro" }]
    },
    outro: {
      bot: [
        { en: "Footprints cannot be erased completely. But they can be made *quiet*. Quiet, per Janet's data, is the goal.", fr: "Les empreintes ne s'effacent pas complètement. Mais on peut les rendre *discrètes*. Et d'après les données de Janet, c'est tout l'objectif : la discrétion.", es: "Las huellas no se borran del todo. Pero pueden volverse *silenciosas*. Silencioso, según los datos de Janet, es el objetivo.", de: "Fußabdrücke lassen sich nicht vollständig auslöschen. Aber sie können *leise* werden. Leise ist, laut Janets Daten, das Ziel.", it: "Le impronte non possono essere cancellate del tutto. Ma possono diventare *silenziose*. Silenzioso, secondo i dati di Janet, è l'obiettivo.", da: "Fodaftryk kan ikke slettes helt. Men de kan gøres *stille*. Stille er, ifølge Janets data, målet.", bg: "Отпечатъците не могат да се изтрият напълно. Но могат да станат *тихи*. Тихото, според данните на Janet, е целта.", tr: "Ayak izleri tamamen silinemez. Ama *sessiz* hâle getirilebilir. Janet'in verilerine göre, sessizlik hedeftir." },
        { en: "Bye for now! 👣", fr: "À très vite ! 👣", es: "¡Hasta pronto! 👣", de: "Bis bald! 👣", it: "A presto! 👣", da: "Vi ses! 👣", bg: "До скоро! 👣", tr: "Şimdilik hoşça kal! 👣" }
      ],
      end: true
    }
  }
};
