window.JANET_COURSES = window.JANET_COURSES || {};
window.JANET_COURSES.linkedin_footprint = {
  id: "linkedin_footprint",
  emoji: "💼",
  duration: 4,
  karma: 40,
  title: {
    en: "Your LinkedIn trail",
    fr: "Ton empreinte LinkedIn",
    es: "Tu rastro en LinkedIn",
    de: "Deine LinkedIn-Spur",
    it: "La tua traccia su LinkedIn",
    da: "Dit LinkedIn-spor",
    bg: "Твоята LinkedIn следа",
    tr: "LinkedIn izin"
  },
  description: {
    en: "Why your CV is a scammer's favorite reading material.",
    fr: "Pourquoi ton CV est la lecture préférée des arnaqueurs.",
    es: "Por qué tu CV es la lectura favorita de los estafadores.",
    de: "Warum dein Lebenslauf die Lieblingslektüre von Betrügern ist.",
    it: "Perché il tuo CV è la lettura preferita dei truffatori.",
    da: "Hvorfor dit CV er svindleres yndlingslæsning.",
    bg: "Защо твоето CV е любимото четиво на измамниците.",
    tr: "CV'n neden dolandırıcıların en sevdiği okuma materyali."
  },
  startNode: "start",
  nodes: {
    start: {
      bot: [
        { en: "Hi there! Janet here, with what is — per my classifications — the most paradoxical social network ever invented.", fr: "Salut ! C'est Janet, avec — d'après mes classifications — le réseau social le plus paradoxal jamais conçu.", es: "¡Hola! Soy Janet, con — según mis clasificaciones — la red social más paradójica jamás inventada.", de: "Hallo! Hier ist Janet, mit — laut meinen Klassifikationen — dem paradoxesten sozialen Netzwerk, das je erfunden wurde.", it: "Ciao! Sono Janet, con — secondo i miei archivi — il social network più paradossale mai inventato.", da: "Hej! Det er Janet, med — ifølge mine optegnelser — det mest paradoksale sociale netværk, der nogensinde er opfundet.", bg: "Здравей! Аз съм Janet, с — според моите класификации — най-парадоксалната социална мрежа, измисляна някога.", tr: "Merhaba! Ben Janet, kayıtlarıma göre şimdiye kadar icat edilmiş en paradoksal sosyal ağla birlikte." },
        { en: "LinkedIn. Simultaneously the most useful and the most dangerous one.", fr: "LinkedIn. À la fois le plus utile et le plus dangereux.", es: "LinkedIn. A la vez la más útil y la más peligrosa.", de: "LinkedIn. Gleichzeitig das nützlichste und das gefährlichste.", it: "LinkedIn. Allo stesso tempo il più utile e il più pericoloso.", da: "LinkedIn. Samtidig det mest nyttige og det farligste.", bg: "LinkedIn. Едновременно най-полезната и най-опасната.", tr: "LinkedIn. Aynı anda hem en faydalısı hem de en tehlikelisi." },
        { en: "Useful, because it finds you jobs. Dangerous, because it's a public CV with your manager's name printed on it.", fr: "Utile, parce qu'il te trouve des jobs. Dangereux, parce que c'est un CV public avec le nom de ta cheffe imprimé dessus.", es: "Útil, porque te encuentra empleo. Peligrosa, porque es un CV público con el nombre de tu jefa impreso encima.", de: "Nützlich, weil es dir Jobs findet. Gefährlich, weil es ein öffentlicher Lebenslauf mit dem Namen deiner Chefin drauf ist.", it: "Utile, perché ti trova lavoro. Pericoloso, perché è un CV pubblico con il nome del tuo capo stampato sopra.", da: "Nyttigt, fordi det finder dig jobs. Farligt, fordi det er et offentligt CV med din chefs navn trykt på.", bg: "Полезна, защото ти намира работа. Опасна, защото е публично CV с името на шефа ти отгоре.", tr: "Faydalı, çünkü sana iş buluyor. Tehlikeli, çünkü üzerinde yöneticinin adı basılı, herkese açık bir CV." }
      ],
      choices: [{ label: { en: "I never thought of it that way", fr: "Je n'avais jamais vu ça comme ça", es: "Nunca lo había visto así", de: "So habe ich das noch nie gesehen", it: "Non l'avevo mai vista così", da: "Det havde jeg aldrig set sådan", bg: "Никога не съм го гледал така", tr: "Bunu hiç böyle düşünmemiştim" }, next: "info" }]
    },
    info: {
      bot: [
        { en: "From your LinkedIn profile, a scammer can learn in 60 seconds:", fr: "Avec ton profil LinkedIn, un arnaqueur apprend en 60 secondes :", es: "Desde tu perfil de LinkedIn, un estafador puede averiguar en 60 segundos:", de: "Aus deinem LinkedIn-Profil kann ein Betrüger in 60 Sekunden lernen:", it: "Dal tuo profilo LinkedIn, un truffatore impara in 60 secondi:", da: "Fra din LinkedIn-profil kan en svindler lære på 60 sekunder:", bg: "От твоя LinkedIn профил измамник може за 60 секунди да научи:", tr: "LinkedIn profilinden bir dolandırıcı 60 saniye içinde şunları öğrenebilir:" },
        { en: "👤 Your full name and current employer.", fr: "👤 Ton nom complet et ton employeur.", es: "👤 Tu nombre completo y tu empleador actual.", de: "👤 Deinen vollständigen Namen und deinen aktuellen Arbeitgeber.", it: "👤 Il tuo nome completo e il tuo datore di lavoro attuale.", da: "👤 Dit fulde navn og din nuværende arbejdsgiver.", bg: "👤 Пълното ти име и настоящия ти работодател.", tr: "👤 Tam adın ve şu anki işverenin." },
        { en: "👔 Your boss's name (\"[name] reports to [name]\").", fr: "👔 Le nom de ta cheffe (\"[nom] est rattaché à [nom]\").", es: "👔 El nombre de tu jefa (\"[nombre] reporta a [nombre]\").", de: "👔 Den Namen deiner Chefin (\"[Name] berichtet an [Name]\").", it: "👔 Il nome del tuo capo (\"[nome] riporta a [nome]\").", da: "👔 Din chefs navn (\"[navn] refererer til [navn]\").", bg: "👔 Името на шефа ти („[име] докладва на [име]“).", tr: "👔 Patronunun adı (\"[isim], [isim]'e bağlı çalışıyor\")." },
        { en: "🏢 Names of your colleagues and your team's structure.", fr: "🏢 Le nom de tes collègues et la structure de ton équipe.", es: "🏢 Los nombres de tus compañeros y la estructura de tu equipo.", de: "🏢 Die Namen deiner Kollegen und die Struktur deines Teams.", it: "🏢 I nomi dei tuoi colleghi e la struttura del tuo team.", da: "🏢 Dine kollegers navne og dit teams struktur.", bg: "🏢 Имената на колегите ти и структурата на екипа ти.", tr: "🏢 Meslektaşlarının isimleri ve ekibinin yapısı." },
        { en: "📍 Where you work, your specialty, your tools.", fr: "📍 Où tu bosses, ta spécialité, tes outils.", es: "📍 Dónde trabajas, tu especialidad, tus herramientas.", de: "📍 Wo du arbeitest, deine Spezialität, deine Tools.", it: "📍 Dove lavori, la tua specialità, i tuoi strumenti.", da: "📍 Hvor du arbejder, dit speciale, dine værktøjer.", bg: "📍 Къде работиш, специалността ти, инструментите ти.", tr: "📍 Nerede çalıştığın, uzmanlığın, kullandığın araçlar." }
      ],
      next: "use"
    },
    use: {
      bot: [
        { en: "Now imagine that scammer sending you a perfectly written email signed by your boss, on the project you actually work on. Convincing, no?", fr: "Imagine maintenant que l'arnaqueur t'envoie un email parfaitement rédigé, signé de ta cheffe, sur le projet sur lequel tu bosses réellement. Convaincant, non ?", es: "Ahora imagina a ese estafador enviándote un correo perfectamente redactado, firmado por tu jefa, sobre el proyecto en el que de verdad trabajas. Convincente, ¿no?", de: "Stell dir jetzt vor, dieser Betrüger schickt dir eine perfekt geschriebene E-Mail, unterschrieben von deiner Chefin, über das Projekt, an dem du tatsächlich arbeitest. Überzeugend, oder?", it: "Ora immagina che quel truffatore ti mandi un'email scritta alla perfezione, firmata dal tuo capo, sul progetto su cui lavori davvero. Convincente, no?", da: "Forestil dig nu, at den svindler sender dig en perfekt skrevet e-mail, underskrevet af din chef, om det projekt, du faktisk arbejder på. Overbevisende, ikke?", bg: "Сега си представи как този измамник ти изпраща перфектно написан имейл, подписан от шефа ти, за проекта, по който реално работиш. Убедително, нали?", tr: "Şimdi o dolandırıcının sana, gerçekten üzerinde çalıştığın proje hakkında, patronun tarafından imzalanmış kusursuz bir e-posta gönderdiğini düşün. İkna edici, değil mi?" }
      ],
      next: "balance"
    },
    balance: {
      bot: [
        { en: "I'm not saying delete LinkedIn. I'm saying — be a little choosier.", fr: "Je ne te dis pas de supprimer LinkedIn. Je dis — sois un peu plus sélectif·ve.", es: "No te digo que borres LinkedIn. Digo — sé un poco más selectivo.", de: "Ich sage nicht, lösch LinkedIn. Ich sage — sei ein bisschen wählerischer.", it: "Non ti sto dicendo di cancellare LinkedIn. Dico — sii un po' più selettivo.", da: "Jeg siger ikke, du skal slette LinkedIn. Jeg siger — vær lidt mere kræsen.", bg: "Не казвам да изтриеш LinkedIn. Казвам — бъди малко по-придирчив.", tr: "LinkedIn'i sil demiyorum. Diyorum ki — biraz daha seçici ol." }
      ],
      next: "linkedin_state"
    },
    linkedin_state: {
      bot: [
        { en: "How locked-down is your LinkedIn profile right now?", fr: "À quel point ton profil LinkedIn est verrouillé en ce moment ?", es: "¿Cómo de blindado tienes tu perfil de LinkedIn ahora mismo?", de: "Wie zugesperrt ist dein LinkedIn-Profil im Moment?", it: "Quanto è blindato il tuo profilo LinkedIn in questo momento?", da: "Hvor låst ned er din LinkedIn-profil lige nu?", bg: "Колко заключен е LinkedIn профилът ти в момента?", tr: "LinkedIn profilin şu an ne kadar kilitli?" }
      ],
      choices: [
        { label: { en: "Wide open — full public CV", fr: "Grand ouvert — CV public", es: "Totalmente abierto — CV público", de: "Sperrangelweit offen — öffentlicher Lebenslauf", it: "Spalancato — CV pubblico", da: "Helt åbent — offentligt CV", bg: "Широко отворен — публично CV", tr: "Tamamen açık — herkese açık CV" }, next: "tips", reaction: { en: "Okay — then the next tips are going to be especially useful for you.", fr: "Ok — alors les conseils qui suivent vont être particulièrement utiles pour toi.", es: "Vale — entonces los próximos consejos te van a venir muy bien.", de: "Okay — dann sind die nächsten Tipps für dich besonders nützlich.", it: "Ok — allora i prossimi consigli ti saranno particolarmente utili.", da: "Okay — så bliver de næste tips især nyttige for dig.", bg: "Окей — следващите съвети ще ти бъдат особено полезни.", tr: "Tamam — sıradaki ipuçları senin için özellikle yararlı olacak." } },
        { label: { en: "Somewhere in the middle", fr: "Quelque part au milieu", es: "Más o menos en medio", de: "Irgendwo in der Mitte", it: "Una via di mezzo", da: "Et sted midt imellem", bg: "Някъде по средата", tr: "Ortalarda bir yerde" }, next: "tips", reaction: { en: "The most common spot. A couple of small tweaks will go a long way.", fr: "Le cas le plus fréquent. Deux ou trois réglages vont déjà bien aider.", es: "Lo más habitual. Un par de ajustes pequeños y ya cambia mucho.", de: "Der häufigste Fall. Ein paar kleine Stellschrauben bringen schon viel.", it: "Il caso più comune. Un paio di piccole modifiche faranno tanto.", da: "Det mest almindelige sted. Et par små justeringer rykker meget.", bg: "Най-честият случай. Няколко малки настройки ще свършат много работа.", tr: "En sık görülen durum. Birkaç küçük ayar büyük fark yaratır." } },
        { label: { en: "Pretty locked down already", fr: "Déjà bien verrouillé", es: "Bastante blindado ya", de: "Schon ziemlich dicht", it: "Già piuttosto blindato", da: "Ret låst ned allerede", bg: "Доста заключен вече", tr: "Zaten epey kilitli" }, next: "tips", reaction: { en: "Lovely. Let's see if there's still a setting or two worth checking.", fr: "Adorable. Voyons s'il reste un ou deux réglages à vérifier.", es: "Estupendo. A ver si queda algún ajuste que merezca un repaso.", de: "Wunderbar. Schauen wir, ob noch eine Einstellung oder zwei einen Blick wert sind.", it: "Bello. Vediamo se c'è ancora qualche impostazione da controllare.", da: "Skønt. Lad os se, om der stadig er en indstilling eller to værd at tjekke.", bg: "Прекрасно. Да видим има ли още една-две настройки, които си струва да се проверят.", tr: "Harika. Bakalım hâlâ kontrol etmeye değer bir iki ayar var mı." } }
      ]
    },
    tips: {
      bot: [
        { en: "Tips that don't hurt your career:", fr: "Quelques conseils qui ne plomberont pas ta carrière :", es: "Consejos que no perjudican tu carrera:", de: "Tipps, die deiner Karriere nicht schaden:", it: "Consigli che non danneggiano la tua carriera:", da: "Tips, der ikke skader din karriere:", bg: "Съвети, които не вредят на кариерата ти:", tr: "Kariyerine zarar vermeyen ipuçları:" },
        { en: "🔒 *Hide your connections list* (Settings → Visibility). Scammers love this list for impersonation.", fr: "🔒 *Cache ta liste de relations* (Paramètres → Visibilité). Les arnaqueurs en raffolent pour usurper des identités.", es: "🔒 *Oculta tu lista de contactos* (Configuración → Visibilidad). A los estafadores les encanta esta lista para suplantarte.", de: "🔒 *Verstecke deine Kontaktliste* (Einstellungen → Sichtbarkeit). Betrüger lieben diese Liste, um Identitäten zu fälschen.", it: "🔒 *Nascondi la lista dei tuoi contatti* (Impostazioni → Visibilità). I truffatori adorano questa lista per impersonare qualcuno.", da: "🔒 *Skjul din kontaktliste* (Indstillinger → Synlighed). Svindlere elsker den liste til at udgive sig for andre.", bg: "🔒 *Скрий списъка си с контакти* (Настройки → Видимост). Измамниците обожават този списък за фалшифициране на самоличност.", tr: "🔒 *Bağlantı listeni gizle* (Ayarlar → Görünürlük). Dolandırıcılar bu listeyi kimliğe bürünmek için çok sever." },
        { en: "📧 *Don't list your work email* on the profile.", fr: "📧 *N'affiche pas ton email pro* sur ton profil.", es: "📧 *No pongas tu correo del trabajo* en el perfil.", de: "📧 *Verrate nicht deine Arbeits-E-Mail* im Profil.", it: "📧 *Non mostrare la tua email di lavoro* sul profilo.", da: "📧 *Vis ikke din arbejds-e-mail* på profilen.", bg: "📧 *Не показвай служебния си имейл* в профила.", tr: "📧 *İş e-postanı profilde gösterme*." },
        { en: "✋ *Be picky with connection requests.* No mutuals + brand-new account = decline.", fr: "✋ *Trie tes demandes de contact.* Aucun lien commun + compte tout neuf = refuse.", es: "✋ *Sé selectivo con las invitaciones.* Sin contactos en común + cuenta recién creada = rechaza.", de: "✋ *Sei wählerisch bei Kontaktanfragen.* Keine gemeinsamen Kontakte + nagelneues Konto = ablehnen.", it: "✋ *Sii selettivo con le richieste di collegamento.* Nessun contatto in comune + account nuovo di zecca = rifiuta.", da: "✋ *Vær kræsen med kontaktanmodninger.* Ingen fælles kontakter + helt ny konto = afslå.", bg: "✋ *Бъди придирчив с поканите за връзка.* Без общи контакти + чисто нов акаунт = откажи.", tr: "✋ *Bağlantı isteklerinde seçici ol.* Ortak bağlantı yok + yepyeni hesap = reddet." },
        { en: "📷 *Reverse-image-search a stranger's photo* before connecting. Stock photo = scam.", fr: "📷 *Fais une recherche d'image inversée* avant d'accepter un inconnu. Photo issue d'une banque d'images = arnaque.", es: "📷 *Haz una búsqueda inversa de imágenes* de la foto de un desconocido antes de aceptarlo. Foto de banco de imágenes = estafa.", de: "📷 *Mach eine umgekehrte Bildersuche* mit dem Foto eines Fremden, bevor du dich verbindest. Stockfoto = Betrug.", it: "📷 *Fai una ricerca inversa per immagini* della foto di uno sconosciuto prima di accettarlo. Foto di stock = truffa.", da: "📷 *Lav en omvendt billedsøgning* på en fremmeds foto, før du forbinder dig. Stockfoto = svindel.", bg: "📷 *Направи обратно търсене на изображението* на снимката на непознат, преди да го добавиш. Стокова снимка = измама.", tr: "📷 Bağlantı kurmadan önce *yabancı birinin fotoğrafını ters görsel aramayla araştır*. Stok fotoğraf = dolandırıcılık." }
      ],
      next: "test"
    },
    test: {
      bot: [
        { en: "Scenario: a \"recruiter\" with a generic profile pings you about a dream job. They want to take it to WhatsApp and \"send you the contract.\"", fr: "Cas : un \"recruteur\" au profil générique t'envoie un message pour le job de tes rêves. Il veut basculer sur WhatsApp et te \"transmettre le contrat\".", es: "Escenario: un \"reclutador\" con un perfil genérico te escribe por el trabajo de tus sueños. Quiere pasarse a WhatsApp y \"enviarte el contrato\".", de: "Szenario: ein \"Recruiter\" mit einem generischen Profil schreibt dich wegen deines Traumjobs an. Er will auf WhatsApp wechseln und dir \"den Vertrag schicken\".", it: "Scenario: un \"recruiter\" con un profilo generico ti contatta per il lavoro dei tuoi sogni. Vuole spostarsi su WhatsApp e \"mandarti il contratto\".", da: "Scenarie: en \"rekrutterer\" med en generisk profil skriver til dig om drømmejobbet. Vedkommende vil flytte til WhatsApp og \"sende dig kontrakten\".", bg: "Сценарий: „рекрутер“ с общ профил ти пише за работата на мечтите ти. Иска да преминете в WhatsApp и да ти „изпрати договора“.", tr: "Senaryo: genel bir profile sahip bir \"işe alım uzmanı\" sana hayalindeki iş hakkında yazıyor. Konuşmayı WhatsApp'a taşıyıp sana \"sözleşmeyi göndermek\" istiyor." }
      ],
      choices: [
        { label: { en: "Check their company first", fr: "Je vérifie l'entreprise d'abord", es: "Compruebo su empresa primero", de: "Ich prüfe erstmal die Firma", it: "Prima controllo l'azienda", da: "Jeg tjekker virksomheden først", bg: "Първо проверявам компанията", tr: "Önce şirketini kontrol ederim" }, next: "test_good" },
        { label: { en: "Switch to WhatsApp", fr: "Je passe sur WhatsApp", es: "Me paso a WhatsApp", de: "Auf WhatsApp wechseln", it: "Passo su WhatsApp", da: "Jeg skifter til WhatsApp", bg: "Преминавам в WhatsApp", tr: "WhatsApp'a geçerim" }, next: "test_bad" }
      ]
    },
    test_good: {
      bot: [
        { en: "✅ Smart. Search the company's actual careers page. If the job isn't listed — that's your answer.", fr: "✅ Bien vu. Cherche la vraie page carrière de l'entreprise. Si l'offre n'y est pas, voilà ta réponse.", es: "✅ Listo. Busca la página de empleo real de la empresa. Si la oferta no aparece — ahí tienes tu respuesta.", de: "✅ Klug. Such die echte Karriere-Seite der Firma. Wenn der Job nicht gelistet ist — das ist deine Antwort.", it: "✅ Furbo. Cerca la vera pagina carriere dell'azienda. Se l'offerta non c'è — ecco la tua risposta.", da: "✅ Klogt. Søg virksomhedens rigtige karriereside. Hvis jobbet ikke står der — det er dit svar.", bg: "✅ Умно. Потърси истинската страница за кариери на компанията. Ако обявата я няма — това е твоят отговор.", tr: "✅ Akıllıca. Şirketin gerçek kariyer sayfasını ara. İlan orada yoksa — cevabın bu." },
        { en: "Real recruiters can also be confirmed via the company's LinkedIn page → employees list.", fr: "Tu peux aussi vérifier un vrai recruteur via la page LinkedIn de l'entreprise → employés.", es: "También puedes confirmar a un reclutador real desde la página de LinkedIn de la empresa → lista de empleados.", de: "Echte Recruiter kannst du auch über die LinkedIn-Seite der Firma → Mitarbeiterliste bestätigen.", it: "I veri recruiter possono anche essere confermati tramite la pagina LinkedIn dell'azienda → elenco dipendenti.", da: "Rigtige rekrutterere kan også bekræftes via virksomhedens LinkedIn-side → medarbejderliste.", bg: "Истинските рекрутери могат да бъдат потвърдени и през LinkedIn страницата на компанията → списък със служители.", tr: "Gerçek işe alım uzmanları ayrıca şirketin LinkedIn sayfası → çalışanlar listesi üzerinden de doğrulanabilir." }
      ],
      next: "outro"
    },
    test_bad: {
      bot: [
        { en: "Stop! Recruiter scams are huge. They'll later \"need a small fee\" or \"verify your identity\" by collecting documents.", fr: "Stop ! Les arnaques au recruteur, c'est massif. Ensuite arrivent les \"petits frais à régler\" ou la \"vérification d'identité\" via des documents.", es: "¡Para! Las estafas de reclutadores están a la orden del día. Después vendrán \"unos gastos pequeños\" o \"verificar tu identidad\" recopilando documentos.", de: "Stopp! Recruiter-Betrug ist riesig. Später kommt dann \"eine kleine Gebühr\" oder \"Identitätsprüfung\" durch das Einsammeln von Dokumenten.", it: "Stop! Le truffe dei recruiter sono enormi. Poi arriveranno \"una piccola spesa\" o \"verifica della tua identità\" raccogliendo documenti.", da: "Stop! Rekrutteringssvindel er kæmpestort. Bagefter kommer \"et lille gebyr\" eller \"bekræft din identitet\" ved at indsamle dokumenter.", bg: "Стоп! Измамите с рекрутери са огромни. После идва „малка такса“ или „потвърждение на самоличността“ чрез събиране на документи.", tr: "Dur! İşe alım dolandırıcılıkları çok yaygın. Sonradan \"küçük bir ücret\" gerekecek ya da belge toplayarak \"kimliğini doğrulamak\" isteyecekler." },
        { en: "Always confirm via the company's official careers page first.", fr: "Vérifie toujours via la page carrière officielle de l'entreprise.", es: "Confirma siempre primero a través de la página oficial de empleo de la empresa.", de: "Bestätige es immer zuerst über die offizielle Karriere-Seite der Firma.", it: "Conferma sempre prima tramite la pagina carriere ufficiale dell'azienda.", da: "Bekræft altid først via virksomhedens officielle karriereside.", bg: "Винаги първо потвърждавай през официалната страница за кариери на компанията.", tr: "Her zaman önce şirketin resmi kariyer sayfasından doğrula." }
      ],
      next: "outro"
    },
    outro: {
      bot: [
        { en: "LinkedIn is genuinely useful. Just remember: every detail you share builds a more convincing impersonation of you. Or your boss.", fr: "LinkedIn est franchement utile. Souviens-toi juste : chaque détail que tu partages rend l'imitation de toi plus crédible. Ou de ta cheffe.", es: "LinkedIn es realmente útil. Solo recuerda: cada detalle que compartes construye una suplantación más convincente de ti. O de tu jefa.", de: "LinkedIn ist wirklich nützlich. Denk nur dran: jedes Detail, das du teilst, baut eine überzeugendere Imitation von dir auf. Oder von deiner Chefin.", it: "LinkedIn è davvero utile. Ricorda solo: ogni dettaglio che condividi costruisce un'imitazione più credibile di te. O del tuo capo.", da: "LinkedIn er virkelig nyttigt. Husk bare: hver detalje, du deler, bygger en mere overbevisende efterligning af dig. Eller din chef.", bg: "LinkedIn е наистина полезен. Само помни: всяка подробност, която споделяш, изгражда по-убедителна имитация на теб. Или на шефа ти.", tr: "LinkedIn gerçekten faydalı. Sadece şunu unutma: paylaştığın her ayrıntı, senin — ya da patronunun — daha inandırıcı bir taklidini oluşturur." },
        { en: "Janet recommends: be helpful, be findable, but maybe a little mysterious. Bye for now! 💼", fr: "Janet recommande : sois utile, reste trouvable, mais garde une part de mystère. À très vite ! 💼", es: "Janet recomienda: sé útil, sé localizable, pero quizá un poquito misterioso. ¡Hasta pronto! 💼", de: "Janet empfiehlt: sei hilfreich, sei auffindbar, aber vielleicht ein bisschen geheimnisvoll. Bis bald! 💼", it: "Janet consiglia: sii utile, sii rintracciabile, ma magari un po' misterioso. A presto! 💼", da: "Janet anbefaler: vær hjælpsom, vær findbar, men måske lidt mystisk. Vi ses! 💼", bg: "Janet препоръчва: бъди полезен, бъди намираем, но може би малко загадъчен. До скоро! 💼", tr: "Janet'in tavsiyesi: yardımsever ol, bulunabilir ol, ama belki birazcık da gizemli. Şimdilik hoşça kal! 💼" }
      ],
      end: true
    }
  }
};
