window.JANET_COURSES = window.JANET_COURSES || {};
window.JANET_COURSES.personal_data = {
  id: "personal_data",
  emoji: "🧬",
  duration: 5,
  karma: 50,
  title: {
    en: "Personal data",
    fr: "Données personnelles",
    es: "Datos personales",
    de: "Persönliche Daten",
    it: "Dati personali",
    da: "Personlige data",
    bg: "Лични данни",
    tr: "Kişisel veriler"
  },
  description: {
    en: "Knowing what you share — and what's quietly leaking out of you.",
    fr: "Savoir ce que tu partages — et ce qui fuit en douce.",
    es: "Saber qué compartes — y qué se está filtrando de ti sin darte cuenta.",
    de: "Wissen, was du teilst — und was unbemerkt aus dir herausläuft.",
    it: "Sapere cosa condividi — e cosa sta uscendo da te in silenzio.",
    da: "At vide, hvad du deler — og hvad der stille siver ud af dig.",
    bg: "Да знаеш какво споделяш — и какво тихо изтича от теб.",
    tr: "Neyi paylaştığını — ve senden sessizce neyin sızdığını bilmek."
  },
  startNode: "start",
  nodes: {
    start: {
      bot: [
        { en: "Hi there! Janet here.", fr: "Salut ! C'est Janet.", es: "¡Hola! Soy Janet.", de: "Hallo! Hier ist Janet.", it: "Ciao! Sono Janet.", da: "Hej! Det er Janet.", bg: "Здравей! Аз съм Janet.", tr: "Merhaba! Ben Janet." },
        { en: "Today's topic: *you*. Or — to be more precise — the version of you that lives on company servers.", fr: "Sujet du jour : *toi*. Plus précisément : la version de toi qui vit sur les serveurs d'entreprises.", es: "Tema de hoy: *tú*. O — para ser más precisa — la versión de ti que vive en los servidores de las empresas.", de: "Heutiges Thema: *du*. Oder — um genauer zu sein — die Version von dir, die auf Firmenservern lebt.", it: "Argomento di oggi: *tu*. O — per essere più precisa — la versione di te che vive sui server delle aziende.", da: "Dagens emne: *dig*. Eller — for at være mere præcis — den udgave af dig, der lever på virksomheders servere.", bg: "Темата за днес: *ти*. Или — за да съм по-точна — версията на теб, която живее по сървърите на компаниите.", tr: "Bugünün konusu: *sen*. Ya da — daha doğrusu — şirket sunucularında yaşayan senin versiyonun." },
        { en: "What it is, who has it, and how to take a tiny bit of it back. According to Janet, this is the most empowering topic on the menu.", fr: "Ce qu'elle est, qui la possède, et comment en reprendre un petit bout. Selon Janet, c'est le sujet le plus libérateur du menu.", es: "Qué es, quién la tiene y cómo recuperar un trocito. Según Janet, es el tema más liberador del menú.", de: "Was sie ist, wer sie hat und wie du ein winziges Stück zurückholst. Laut Janet ist das das ermächtigendste Thema auf der Speisekarte.", it: "Cos'è, chi ce l'ha e come riprendersene un pezzetto. Secondo Janet, è l'argomento più liberatorio del menu.", da: "Hvad det er, hvem der har det, og hvordan man tager en lille bid tilbage. Ifølge Janet er det det mest frigørende emne på menuen.", bg: "Какво е, кой я има и как да си върнеш малко от нея. Според Janet, това е най-овластяващата тема в менюто.", tr: "Ne olduğunu, kimde olduğunu ve ufak bir parçasını nasıl geri alacağını. Janet'e göre, bu menüdeki en güçlendirici konu." }
      ],
      choices: [{ label: { en: "Let's go", fr: "C'est parti", es: "Vamos", de: "Los geht's", it: "Andiamo", da: "Lad os komme i gang", bg: "Да започваме", tr: "Hadi başlayalım" }, next: "what" }]
    },
    what: {
      bot: [
        { en: "\"Personal data\" is anything that points back to you. The obvious stuff:", fr: "Une \"donnée personnelle\", c'est tout ce qui mène à toi. Les évidentes :", es: "Un \"dato personal\" es cualquier cosa que apunta a ti. Lo obvio:", de: "\"Persönliche Daten\" sind alles, was zu dir zurückführt. Das Offensichtliche:", it: "Un \"dato personale\" è tutto ciò che riconduce a te. Le cose ovvie:", da: "\"Personlige data\" er alt, der peger tilbage på dig. Det åbenlyse:", bg: "\"Лични данни\" е всичко, което води обратно до теб. Очевидните:", tr: "\"Kişisel veri\", sana geri işaret eden her şeydir. Bariz olanlar:" },
        { en: "📛 Name, age, email, phone, address.", fr: "📛 Nom, âge, email, téléphone, adresse.", es: "📛 Nombre, edad, correo, teléfono, dirección.", de: "📛 Name, Alter, E-Mail, Telefon, Adresse.", it: "📛 Nome, età, email, telefono, indirizzo.", da: "📛 Navn, alder, e-mail, telefon, adresse.", bg: "📛 Име, възраст, имейл, телефон, адрес.", tr: "📛 İsim, yaş, e-posta, telefon, adres." },
        { en: "But also a *lot* of less obvious things:", fr: "Mais aussi *plein* de choses moins évidentes :", es: "Pero también *muchas* cosas menos obvias:", de: "Aber auch *viele* weniger offensichtliche Dinge:", it: "Ma anche *tante* cose meno ovvie:", da: "Men også *en masse* mindre åbenlyse ting:", bg: "Но също и *много* по-малко очевидни неща:", tr: "Ama bir de *bir sürü* daha az bariz şey:" },
        { en: "📍 Your location history.", fr: "📍 L'historique de tes positions.", es: "📍 Tu historial de ubicaciones.", de: "📍 Dein Standortverlauf.", it: "📍 La cronologia delle tue posizioni.", da: "📍 Din placeringshistorik.", bg: "📍 Историята на местоположенията ти.", tr: "📍 Konum geçmişin." },
        { en: "🛒 Every product you ever bought online.", fr: "🛒 Chaque produit que tu as commandé en ligne.", es: "🛒 Cada producto que has comprado en línea.", de: "🛒 Jedes Produkt, das du je online gekauft hast.", it: "🛒 Ogni prodotto che hai mai comprato online.", da: "🛒 Hvert produkt du nogensinde har købt online.", bg: "🛒 Всеки продукт, който някога си купувала онлайн.", tr: "🛒 Çevrimiçi aldığın her ürün." },
        { en: "🎵 What you searched at 2am last Wednesday.", fr: "🎵 Ce que tu as cherché à 2h du matin mercredi dernier.", es: "🎵 Lo que buscaste a las 2 de la madrugada el miércoles pasado.", de: "🎵 Was du letzten Mittwoch um 2 Uhr morgens gesucht hast.", it: "🎵 Cosa hai cercato alle 2 di notte mercoledì scorso.", da: "🎵 Hvad du søgte efter klokken 2 om natten sidste onsdag.", bg: "🎵 Какво си търсила в 2 през нощта миналата сряда.", tr: "🎵 Geçen çarşamba gece 2'de ne aradığın." },
        { en: "👀 How long you stared at a photo before scrolling.", fr: "👀 Le temps passé à regarder une photo avant de scroller.", es: "👀 Cuánto tiempo te quedaste mirando una foto antes de seguir scrolleando.", de: "👀 Wie lange du auf ein Foto gestarrt hast, bevor du weitergescrollt bist.", it: "👀 Quanto a lungo hai fissato una foto prima di scorrere.", da: "👀 Hvor længe du stirrede på et foto, før du scrollede videre.", bg: "👀 Колко дълго си гледала снимка, преди да продължиш да скролваш.", tr: "👀 Kaydırmadan önce bir fotoğrafa ne kadar baktığın." }
      ],
      next: "value"
    },
    value: {
      bot: [
        { en: "All this gets bundled into a *profile* of you. Profiles are bought and sold by data brokers, ad networks, and yes, occasionally scammers.", fr: "Tout ça est assemblé en un *profil* de toi. Les profils s'achètent et se vendent entre courtiers de données, régies pub, et parfois aussi des arnaqueurs.", es: "Todo esto se agrupa en un *perfil* tuyo. Los perfiles se compran y se venden entre brokers de datos, redes publicitarias y, sí, a veces estafadores.", de: "All das wird zu einem *Profil* von dir gebündelt. Profile werden von Datenhändlern, Werbenetzwerken und ja, gelegentlich Betrügern gekauft und verkauft.", it: "Tutto questo viene impacchettato in un *profilo* di te. I profili vengono comprati e venduti tra broker di dati, reti pubblicitarie e, sì, a volte truffatori.", da: "Alt dette samles til en *profil* af dig. Profiler købes og sælges af datamæglere, annoncenetværk og ja, af og til svindlere.", bg: "Всичко това се събира в *профил* на теб. Профилите се купуват и продават между брокери на данни, рекламни мрежи и да, понякога измамници.", tr: "Tüm bunlar, senin bir *profilin* halinde paketleniyor. Profiller veri simsarları, reklam ağları ve evet, ara sıra dolandırıcılar tarafından alınıp satılıyor." },
        { en: "Each profile is worth pennies on its own. Bundled, they're billions.", fr: "Chaque profil ne vaut que quelques centimes. Empilés, ça pèse des milliards.", es: "Cada perfil por sí solo vale céntimos. En conjunto, valen miles de millones.", de: "Jedes Profil ist für sich genommen Pfennige wert. Gebündelt sind sie Milliarden wert.", it: "Ogni profilo da solo vale pochi centesimi. Insieme, valgono miliardi.", da: "Hver profil er ører værd alene. Samlet er de milliarder værd.", bg: "Всеки профил сам по себе си струва стотинки. Събрани, струват милиарди.", tr: "Her profil tek başına kuruşluktur. Bir araya geldiklerinde ise milyarlar değerinde." }
      ],
      next: "ask"
    },
    ask: {
      bot: [
        { en: "Want the practical bits — what to do?", fr: "On passe au pratique — qu'est-ce qu'on fait ?", es: "¿Pasamos a lo práctico — qué hacer?", de: "Wollen wir zum Praktischen — was zu tun ist?", it: "Passiamo al pratico — cosa fare?", da: "Skal vi til det praktiske — hvad man kan gøre?", bg: "Минаваме на практичното — какво да правим?", tr: "Pratik kısma geçelim mi — ne yapmalı?" }
      ],
      choices: [{ label: { en: "Yes please", fr: "Oui s'il te plaît", es: "Sí, por favor", de: "Ja bitte", it: "Sì, per favore", da: "Ja tak", bg: "Да, моля", tr: "Evet lütfen" }, next: "reduce" }]
    },
    reduce: {
      bot: [
        { en: "🪥 *Brush your data teeth* — once a year, do an account audit.", fr: "🪥 *Brossage de données* — une fois par an, fais le ménage.", es: "🪥 *Cepíllate los datos* — una vez al año, haz una auditoría de cuentas.", de: "🪥 *Putz dir die Datenzähne* — einmal im Jahr eine Kontenprüfung machen.", it: "🪥 *Lavati i denti dei dati* — una volta all'anno, fai un controllo degli account.", da: "🪥 *Børst dine datatænder* — én gang om året, lav et kontoeftersyn.", bg: "🪥 *Изчеткай си зъбите от данни* — веднъж годишно направи одит на профилите.", tr: "🪥 *Veri dişlerini fırçala* — yılda bir kez hesap denetimi yap." },
        { en: "Delete accounts you no longer use. Many sites have a *Delete account* button buried in settings.", fr: "Supprime les comptes que tu n'utilises plus. Beaucoup de sites ont un bouton *Supprimer mon compte* enterré dans les paramètres.", es: "Borra las cuentas que ya no usas. Muchos sitios tienen un botón *Eliminar cuenta* enterrado en los ajustes.", de: "Lösche Konten, die du nicht mehr nutzt. Viele Seiten haben einen *Konto löschen*-Button tief in den Einstellungen versteckt.", it: "Elimina gli account che non usi più. Molti siti hanno un pulsante *Elimina account* sepolto nelle impostazioni.", da: "Slet konti, du ikke længere bruger. Mange sider har en *Slet konto*-knap gemt i indstillingerne.", bg: "Изтрий профили, които вече не използваш. Много сайтове имат бутон *Изтрий профила*, заровен в настройките.", tr: "Artık kullanmadığın hesapları sil. Birçok sitede ayarların derinliklerine gömülmüş bir *Hesabı sil* butonu vardır." },
        { en: "If they don't, email them — under GDPR (Europe) or CCPA (California) they often have to comply.", fr: "Sinon, écris-leur — RGPD (Europe) ou CCPA (Californie) les obligent souvent à obtempérer.", es: "Si no, escríbeles — bajo el GDPR (Europa) o la CCPA (California) suelen estar obligados a cumplir.", de: "Wenn nicht, schreib ihnen — laut GDPR (Europa) oder CCPA (Kalifornien) müssen sie oft nachkommen.", it: "Se non ce l'hanno, scrivigli — con il GDPR (Europa) o la CCPA (California) spesso sono obbligati a obbedire.", da: "Hvis ikke, skriv til dem — under GDPR (Europa) eller CCPA (Californien) skal de ofte efterkomme det.", bg: "Ако нямат, пиши им — според GDPR (Европа) или CCPA (Калифорния) често са длъжни да се съобразят.", tr: "Yoksa onlara e-posta at — GDPR (Avrupa) ya da CCPA (Kaliforniya) kapsamında genellikle uymak zorundalar." }
      ],
      next: "fake_data"
    },
    fake_data: {
      bot: [
        { en: "🎭 *Lie a little, lovingly.* For low-stakes signups (newsletters, free Wi-Fi, store loyalty cards) — fake names, fake birthdays, dedicated alias emails.", fr: "🎭 *Mens un peu, gentiment.* Pour les inscriptions sans enjeu (newsletters, Wi-Fi gratuit, cartes de fidélité) — pseudo, fausse date de naissance, email-alias.", es: "🎭 *Miente un poquito, con cariño.* Para registros sin importancia (newsletters, Wi-Fi gratis, tarjetas de fidelidad) — nombres falsos, cumpleaños falsos, correos alias dedicados.", de: "🎭 *Lüg ein bisschen, liebevoll.* Bei unwichtigen Anmeldungen (Newsletter, kostenloses WLAN, Kundenkarten) — falsche Namen, falsche Geburtstage, eigene Alias-E-Mails.", it: "🎭 *Menti un po', con affetto.* Per le iscrizioni senza importanza (newsletter, Wi-Fi gratuito, carte fedeltà) — nomi falsi, date di nascita false, email alias dedicate.", da: "🎭 *Lyv lidt, kærligt.* Til ligegyldige tilmeldinger (nyhedsbreve, gratis Wi-Fi, loyalitetskort) — falske navne, falske fødselsdage, dedikerede alias-e-mails.", bg: "🎭 *Излъжи малко, с любов.* За регистрации без значение (бюлетини, безплатен Wi-Fi, карти за лоялност) — фалшиви имена, фалшиви рождени дати, специални имейл-псевдоними.", tr: "🎭 *Sevgiyle azıcık yalan söyle.* Önemsiz kayıtlar için (bültenler, ücretsiz Wi-Fi, mağaza sadakat kartları) — sahte isimler, sahte doğum günleri, ayrı takma ad e-postaları." },
        { en: "Apple, Gmail, Firefox Relay, and SimpleLogin can generate burner email aliases.", fr: "Apple, Gmail, Firefox Relay, ou SimpleLogin génèrent des alias jetables.", es: "Apple, Gmail, Firefox Relay y SimpleLogin pueden generar alias de correo desechables.", de: "Apple, Gmail, Firefox Relay und SimpleLogin können Wegwerf-E-Mail-Aliase erzeugen.", it: "Apple, Gmail, Firefox Relay e SimpleLogin possono generare alias email usa e getta.", da: "Apple, Gmail, Firefox Relay og SimpleLogin kan generere engangs-e-mail-aliasser.", bg: "Apple, Gmail, Firefox Relay и SimpleLogin могат да генерират еднократни имейл псевдоними.", tr: "Apple, Gmail, Firefox Relay ve SimpleLogin tek kullanımlık e-posta takma adları üretebilir." }
      ],
      next: "settings"
    },
    settings: {
      bot: [
        { en: "📵 *Trim app permissions.* Open your phone settings → Permissions. Why does that flashlight app need your contacts?", fr: "📵 *Coupe les permissions d'apps.* Va dans les réglages → Permissions. Pourquoi l'appli lampe-torche a-t-elle besoin de tes contacts ?", es: "📵 *Recorta los permisos de las apps.* Abre los ajustes del móvil → Permisos. ¿Por qué la app de linterna necesita tus contactos?", de: "📵 *Stutze die App-Berechtigungen.* Öffne die Telefoneinstellungen → Berechtigungen. Warum braucht die Taschenlampen-App deine Kontakte?", it: "📵 *Taglia i permessi delle app.* Apri le impostazioni del telefono → Autorizzazioni. Perché quell'app torcia ha bisogno dei tuoi contatti?", da: "📵 *Skær ned på app-tilladelser.* Åbn dine telefonindstillinger → Tilladelser. Hvorfor har den lommelygte-app brug for dine kontakter?", bg: "📵 *Подкастри разрешенията на приложенията.* Отвори настройките на телефона → Разрешения. Защо приложението за фенерче има нужда от контактите ти?", tr: "📵 *Uygulama izinlerini kırp.* Telefon ayarlarını aç → İzinler. O el feneri uygulamasının kişilerine neden ihtiyacı var?" },
        { en: "Revoke camera, mic, contacts, location from anything that doesn't *strictly* need them.", fr: "Coupe caméra, micro, contacts, position pour tout ce qui n'en a pas *strictement* besoin.", es: "Quita cámara, micro, contactos y ubicación a cualquier cosa que no las necesite *estrictamente*.", de: "Entziehe Kamera, Mikrofon, Kontakte und Standort allem, was sie nicht *unbedingt* braucht.", it: "Revoca fotocamera, microfono, contatti, posizione a tutto ciò che non ne ha *strettamente* bisogno.", da: "Fjern kamera, mikrofon, kontakter og placering fra alt, der ikke *strengt* har brug for det.", bg: "Откажи камера, микрофон, контакти, местоположение на всичко, което не им е *строго* необходимо.", tr: "*Kesinlikle* ihtiyacı olmayan her şeyden kamera, mikrofon, kişiler ve konum izinlerini geri al." }
      ],
      next: "social"
    },
    social: {
      bot: [
        { en: "📱 *Audit your socials.* Pretend to be a stranger and search yourself. What can a random person learn about you in 5 minutes?", fr: "📱 *Audite tes réseaux.* Fais semblant d'être un inconnu et cherche-toi. Que peut apprendre quelqu'un sur toi en 5 minutes ?", es: "📱 *Audita tus redes.* Finge ser un desconocido y búscate. ¿Qué puede aprender una persona cualquiera sobre ti en 5 minutos?", de: "📱 *Prüfe deine sozialen Netzwerke.* Tu so, als wärst du fremd, und such nach dir selbst. Was kann ein Zufallsmensch in 5 Minuten über dich erfahren?", it: "📱 *Controlla i tuoi social.* Fingi di essere uno sconosciuto e cercati. Cosa può imparare una persona qualunque su di te in 5 minuti?", da: "📱 *Tjek dine sociale medier.* Lad som om du er en fremmed og søg på dig selv. Hvad kan en tilfældig person lære om dig på 5 minutter?", bg: "📱 *Провери социалните си мрежи.* Престори се на непознат и се потърси. Какво може случаен човек да научи за теб за 5 минути?", tr: "📱 *Sosyal medyanı denetle.* Bir yabancıymış gibi davranıp kendini ara. Rastgele bir insan 5 dakikada senin hakkında neler öğrenebilir?" },
        { en: "If the answer includes your home street, workplace, kid's school, holiday dates — consider tightening privacy settings.", fr: "Si la réponse contient ta rue, ton lieu de travail, l'école des enfants, tes dates de vacances — pense à durcir tes paramètres.", es: "Si la respuesta incluye tu calle, tu trabajo, el colegio de los peques, las fechas de vacaciones — plantéate apretar la configuración de privacidad.", de: "Wenn die Antwort deine Wohnstraße, deinen Arbeitsplatz, die Schule deines Kindes oder Urlaubsdaten enthält — überlege, die Datenschutzeinstellungen zu verschärfen.", it: "Se la risposta include la tua via, il posto di lavoro, la scuola dei bambini, le date delle vacanze — valuta di stringere le impostazioni della privacy.", da: "Hvis svaret indeholder din gade, arbejdsplads, børnenes skole eller feriedatoer — overvej at stramme privatlivsindstillingerne.", bg: "Ако отговорът включва улицата ти, работното място, училището на детето, датите на отпуска — обмисли да затегнеш настройките за поверителност.", tr: "Cevap evinin sokağını, iş yerini, çocuğunun okulunu, tatil tarihlerini içeriyorsa — gizlilik ayarlarını sıkılaştırmayı düşün." }
      ],
      choices: [{ label: { en: "Doing that this weekend", fr: "Je fais ça ce week-end", es: "Lo haré este fin de semana", de: "Mache ich dieses Wochenende", it: "Lo faccio questo fine settimana", da: "Det gør jeg i weekenden", bg: "Ще го направя този уикенд", tr: "Bunu bu hafta sonu yapacağım" }, next: "outro" }]
    },
    outro: {
      bot: [
        { en: "Perfection is not the goal. The goal is to give scammers *less to work with*.", fr: "Le but n'est pas la perfection. Le but est de donner aux arnaqueurs *moins de matière*.", es: "El objetivo no es la perfección. El objetivo es dar a los estafadores *menos con lo que trabajar*.", de: "Perfektion ist nicht das Ziel. Das Ziel ist, Betrügern *weniger Material* zu geben.", it: "L'obiettivo non è la perfezione. L'obiettivo è dare ai truffatori *meno materiale*.", da: "Målet er ikke perfektion. Målet er at give svindlere *mindre at arbejde med*.", bg: "Целта не е перфекцията. Целта е да дадеш на измамниците *по-малко материал*.", tr: "Hedef mükemmellik değil. Hedef, dolandırıcılara *daha az malzeme* vermek." },
        { en: "Each account deleted, each permission revoked = a quieter version of you on the internet. Bye for now, smaller-footprint friend! 🌱", fr: "Chaque compte supprimé, chaque permission coupée = une version plus discrète de toi sur internet. À très vite, empreinte allégée ! 🌱", es: "Cada cuenta borrada, cada permiso revocado = una versión más silenciosa de ti en internet. ¡Hasta pronto, amiga de huella reducida! 🌱", de: "Jedes gelöschte Konto, jede entzogene Berechtigung = eine leisere Version von dir im Internet. Bis bald, kleinerer-Fußabdruck-Freundin! 🌱", it: "Ogni account eliminato, ogni autorizzazione revocata = una versione più silenziosa di te su internet. A presto, amica dall'impronta ridotta! 🌱", da: "Hver slettet konto, hver tilbagekaldt tilladelse = en mere stille udgave af dig på internettet. Vi ses, mindre-aftryk-ven! 🌱", bg: "Всеки изтрит профил, всяко отменено разрешение = по-тиха версия на теб в интернет. До скоро, приятелко с по-малък отпечатък! 🌱", tr: "Silinen her hesap, geri alınan her izin = internette daha sessiz bir versiyonun. Şimdilik hoşça kal, daha küçük ayak izli dostum! 🌱" }
      ],
      end: true
    }
  }
};
