window.JANET_COURSES = window.JANET_COURSES || {};
window.JANET_COURSES.two_factor = {
  id: "two_factor",
  emoji: "✌️",
  duration: 4,
  karma: 50,
  title: {
    en: "Two-factor auth",
    fr: "Double authentification",
    es: "Autenticación de dos factores",
    de: "Zwei-Faktor-Authentifizierung",
    it: "Autenticazione a due fattori",
    da: "Tofaktorgodkendelse",
    bg: "Двуфакторно удостоверяване",
    tr: "İki faktörlü kimlik doğrulama"
  },
  description: {
    en: "The single most powerful upgrade to your online safety.",
    fr: "Le geste qui change le plus la donne pour ta sécurité en ligne.",
    es: "La mejora más potente para tu seguridad en línea.",
    de: "Das wirkungsvollste Upgrade für deine Online-Sicherheit.",
    it: "Il singolo miglioramento più potente per la tua sicurezza online.",
    da: "Den enkelt mest effektive opgradering af din onlinesikkerhed.",
    bg: "Най-мощното подобрение за твоята онлайн сигурност.",
    tr: "Çevrimiçi güvenliğin için yapabileceğin en güçlü iyileştirme."
  },
  startNode: "start",
  nodes: {
    start: {
      bot: [
        { en: "Hi there! Janet here, with what is, I have decided, my favorite security topic.", fr: "Salut ! Janet à l'appareil, et avec mon sujet de sécurité préféré — c'est moi qui décide.", es: "¡Hola! Soy Janet, con el que, lo he decidido, es mi tema de seguridad favorito.", de: "Hallo! Hier ist Janet, mit — ich habe es entschieden — meinem Lieblings-Sicherheitsthema.", it: "Ciao! Sono Janet, con quello che, ho deciso, è il mio argomento di sicurezza preferito.", da: "Hej! Det er Janet, med det, jeg har besluttet, er mit yndlingssikkerhedsemne.", bg: "Здравей! Аз съм Janet, с — реших го — любимата ми тема по сигурност.", tr: "Merhaba! Ben Janet, ve karar verdim — en sevdiğim güvenlik konusuyla buradayım." },
        { en: "Quick thought experiment: imagine someone steals your house key. Inconvenient.", fr: "Petite expérience de pensée : imagine qu'on te pique ta clé de maison. Embêtant, hein.", es: "Pequeño experimento mental: imagina que alguien te roba la llave de casa. Incómodo.", de: "Kleines Gedankenexperiment: Stell dir vor, jemand stiehlt deinen Haustürschlüssel. Lästig.", it: "Piccolo esperimento mentale: immagina che qualcuno ti rubi la chiave di casa. Scocciante.", da: "Lille tankeeksperiment: forestil dig, at nogen stjæler din husnøgle. Træls.", bg: "Малък мисловен експеримент: представи си, че някой ти открадне ключа от вкъщи. Неприятно.", tr: "Küçük bir düşünce deneyi: birinin ev anahtarını çaldığını hayal et. Can sıkıcı." },
        { en: "Now imagine your door also asks *what's your grandmother's name* before unlocking. The thief, suddenly, has a problem.", fr: "Maintenant imagine que ta porte demande aussi *le prénom de ta grand-mère* avant de s'ouvrir. Le voleur, lui, vient d'avoir un sérieux problème.", es: "Ahora imagina que tu puerta también pregunta *cómo se llama tu abuela* antes de abrirse. El ladrón, de repente, tiene un problema.", de: "Stell dir jetzt vor, deine Tür fragt vor dem Aufschließen auch noch *wie heißt deine Großmutter*. Der Dieb hat plötzlich ein Problem.", it: "Ora immagina che la tua porta chieda anche *come si chiama tua nonna* prima di aprirsi. Il ladro, all'improvviso, ha un problema.", da: "Forestil dig nu, at din dør også spørger *hvad hedder din bedstemor*, før den låser op. Tyven har pludselig et problem.", bg: "Сега си представи, че вратата ти също пита *как се казва баба ти*, преди да се отключи. Крадецът изведнъж има проблем.", tr: "Şimdi kapının açılmadan önce *babaannenin adı ne* diye de sorduğunu hayal et. Hırsızın aniden bir sorunu olur." }
      ],
      choices: [{ label: { en: "Cute analogy", fr: "Joli !", es: "Bonita analogía", de: "Hübscher Vergleich", it: "Carina come analogia", da: "Sød analogi", bg: "Сладка аналогия", tr: "Tatlı bir benzetme" }, next: "intro" }]
    },
    intro: {
      bot: [
        { en: "That second question is what we call *two-factor authentication*. Or 2FA, if you like saving syllables.", fr: "Cette deuxième question, c'est ce qu'on appelle la *double authentification*. Ou 2FA, pour les amateurs d'acronymes.", es: "Esa segunda pregunta es lo que llamamos *autenticación de dos factores*. O 2FA, si te gusta ahorrar sílabas.", de: "Diese zweite Frage nennen wir *Zwei-Faktor-Authentifizierung*. Oder 2FA, falls du gern Silben sparst.", it: "Quella seconda domanda è ciò che chiamiamo *autenticazione a due fattori*. O 2FA, se ti piace risparmiare sillabe.", da: "Det andet spørgsmål kalder vi *tofaktorgodkendelse*. Eller 2FA, hvis du kan lide at spare stavelser.", bg: "Този втори въпрос е това, което наричаме *двуфакторно удостоверяване*. Или 2FA, ако обичаш да спестяваш срички.", tr: "İşte o ikinci soru, *iki faktörlü kimlik doğrulama* dediğimiz şey. Ya da heceleri sevmiyorsan, 2FA." },
        { en: "Translated: even if someone steals your password, they *still* can't get in.", fr: "En clair : même si quelqu'un te pique ton mot de passe, il ne peut *quand même pas* entrer.", es: "Traducción: aunque alguien robe tu contraseña, *aun así* no puede entrar.", de: "Übersetzt: Selbst wenn jemand dein Passwort klaut, kommt er *trotzdem* nicht rein.", it: "Tradotto: anche se qualcuno ti ruba la password, *comunque* non può entrare.", da: "Oversat: selv hvis nogen stjæler din adgangskode, kan de *stadig* ikke komme ind.", bg: "Преведено: дори ако някой ти открадне паролата, той *пак* не може да влезе.", tr: "Tercüme edersek: biri parolanı çalsa bile, *yine de* içeri giremez." }
      ],
      choices: [{ label: { en: "How does it work?", fr: "Ça fonctionne comment ?", es: "¿Cómo funciona?", de: "Wie funktioniert das?", it: "Come funziona?", da: "Hvordan virker det?", bg: "Как работи?", tr: "Nasıl çalışıyor?" }, next: "how" }]
    },
    how: {
      bot: [
        { en: "Three flavors. Listed from least secure to most:", fr: "Trois formules, de la moins sûre à la plus sûre :", es: "Tres variantes. De la menos segura a la más segura:", de: "Drei Varianten. Von am wenigsten sicher bis am sichersten:", it: "Tre varianti. Dalla meno sicura alla più sicura:", da: "Tre varianter. Fra mindst sikker til mest sikker:", bg: "Три разновидности. От най-малко до най-сигурната:", tr: "Üç çeşit. En az güvenliden en güvenliye doğru sıralı:" },
        { en: "📱 *SMS code* — they text you a number. Easy to use. Sadly, also the easiest for hackers to hijack.", fr: "📱 *Code SMS* — on t'envoie un code par texto. Simple à utiliser. Et malheureusement, simple à détourner pour les pirates.", es: "📱 *Código SMS* — te envían un número por mensaje. Fácil de usar. Lamentablemente, también el más fácil de secuestrar para los hackers.", de: "📱 *SMS-Code* — du bekommst eine Nummer per SMS. Einfach zu nutzen. Leider auch am einfachsten für Hacker zu kapern.", it: "📱 *Codice SMS* — ti mandano un numero via SMS. Facile da usare. Purtroppo anche il più facile da dirottare per gli hacker.", da: "📱 *SMS-kode* — du får et tal pr. SMS. Nemt at bruge. Desværre også nemmest for hackere at kapre.", bg: "📱 *SMS код* — изпращат ти число по SMS. Лесно за използване. За съжаление и най-лесно за прихващане от хакери.", tr: "📱 *SMS kodu* — sana SMS ile bir numara gönderirler. Kullanması kolay. Ne yazık ki hackerların ele geçirmesi de en kolayı." },
        { en: "🪄 *Authenticator app* — an app like Authy, 1Password or Google Authenticator generates a 6-digit code every 30 seconds. Much better.", fr: "🪄 *Application d'authentification* — une appli comme Authy, 1Password ou Google Authenticator génère un code à 6 chiffres toutes les 30 secondes. Bien mieux.", es: "🪄 *App de autenticación* — una app como Authy, 1Password o Google Authenticator genera un código de 6 dígitos cada 30 segundos. Mucho mejor.", de: "🪄 *Authenticator-App* — eine App wie Authy, 1Password oder Google Authenticator erzeugt alle 30 Sekunden einen 6-stelligen Code. Viel besser.", it: "🪄 *App di autenticazione* — un'app come Authy, 1Password o Google Authenticator genera un codice a 6 cifre ogni 30 secondi. Molto meglio.", da: "🪄 *Authenticator-app* — en app som Authy, 1Password eller Google Authenticator genererer en 6-cifret kode hvert 30. sekund. Meget bedre.", bg: "🪄 *Приложение за удостоверяване* — приложение като Authy, 1Password или Google Authenticator генерира 6-цифрен код на всеки 30 секунди. Много по-добре.", tr: "🪄 *Kimlik doğrulayıcı uygulama* — Authy, 1Password ya da Google Authenticator gibi bir uygulama her 30 saniyede bir 6 haneli bir kod üretir. Çok daha iyi." },
        { en: "🔑 *Hardware key* — a tiny USB stick (like a YubiKey). You touch it, you're in. Strongest by far.", fr: "🔑 *Clé physique* — un petit dongle USB (style YubiKey). Tu poses le doigt dessus, et c'est validé. De très loin le plus solide.", es: "🔑 *Llave física* — una pequeña memoria USB (como una YubiKey). La tocas y estás dentro. Lo más fuerte con diferencia.", de: "🔑 *Hardware-Schlüssel* — ein winziger USB-Stick (z. B. ein YubiKey). Du berührst ihn, du bist drin. Mit Abstand am stärksten.", it: "🔑 *Chiave fisica* — una piccola chiavetta USB (come una YubiKey). La tocchi, sei dentro. Di gran lunga la più sicura.", da: "🔑 *Hardware-nøgle* — en lille USB-stik (som en YubiKey). Du rører den, og du er inde. Klart den stærkeste.", bg: "🔑 *Хардуерен ключ* — малко USB устройство (като YubiKey). Докосваш го и си вътре. Категорично най-силният.", tr: "🔑 *Donanım anahtarı* — küçük bir USB çubuğu (YubiKey gibi). Dokunursun, içeridesin. Açık ara en güçlüsü." }
      ],
      choices: [{ label: { en: "Which should I use?", fr: "Laquelle choisir ?", es: "¿Cuál debo usar?", de: "Welche soll ich nehmen?", it: "Quale dovrei usare?", da: "Hvilken skal jeg bruge?", bg: "Кой да използвам?", tr: "Hangisini kullanmalıyım?" }, next: "fact_blink" }]
    },
    fact_blink: {
      bot: [
        { en: "(Tiny aside: the average human blinks about *14,400 times a day*. Janet finds that an impressive amount of involuntary maintenance.)", fr: "(Petite parenthèse : un humain cligne des yeux environ *14 400 fois par jour*. Janet trouve que ça fait beaucoup d'entretien involontaire.)", es: "(Pequeño paréntesis: el ser humano medio parpadea unas *14.400 veces al día*. A Janet le parece una cantidad impresionante de mantenimiento involuntario.)", de: "(Kleine Randbemerkung: Der durchschnittliche Mensch blinzelt etwa *14.400 Mal pro Tag*. Janet findet das eine beeindruckende Menge unfreiwilliger Wartung.)", it: "(Piccola parentesi: l'essere umano medio sbatte le palpebre circa *14.400 volte al giorno*. Janet trova che sia una quantità impressionante di manutenzione involontaria.)", da: "(Lille sidebemærkning: det gennemsnitlige menneske blinker omkring *14.400 gange om dagen*. Janet synes, det er en imponerende mængde ufrivillig vedligeholdelse.)", bg: "(Малка отвлечена забележка: средностатистическият човек мига около *14 400 пъти на ден*. Janet намира това за впечатляващо количество неволна поддръжка.)", tr: "(Küçük bir parantez: ortalama bir insan günde yaklaşık *14.400 kez* göz kırpar. Janet bunu istemsiz bir bakım için etkileyici bir miktar buluyor.)" },
        { en: "Anyway! Two-factor auth.", fr: "Bref ! Revenons à la double authentification.", es: "¡En fin! Autenticación de dos factores.", de: "Wie auch immer! Zwei-Faktor-Authentifizierung.", it: "Comunque! Autenticazione a due fattori.", da: "Nå men! Tofaktorgodkendelse.", bg: "Както и да е! Двуфакторно удостоверяване.", tr: "Her neyse! İki faktörlü kimlik doğrulama." }
      ],
      next: "advice"
    },
    advice: {
      bot: [
        { en: "Honest answer: anything is better than nothing.", fr: "Honnêtement : n'importe laquelle vaut toujours mieux que rien.", es: "Respuesta honesta: cualquier cosa es mejor que nada.", de: "Ehrliche Antwort: Irgendwas ist besser als nichts.", it: "Risposta sincera: qualsiasi cosa è meglio di niente.", da: "Ærligt svar: alt er bedre end ingenting.", bg: "Честен отговор: каквото и да е, е по-добре от нищо.", tr: "Dürüst cevap: hiçbir şey olmamasından her şey daha iyidir." },
        { en: "If SMS is the only option a site gives you — turn it on. Now.", fr: "Si un site ne te propose que le SMS — active-le quand même. Tout de suite.", es: "Si un sitio solo te ofrece SMS — actívalo. Ya.", de: "Wenn eine Seite dir nur SMS anbietet — schalte es ein. Sofort.", it: "Se un sito ti offre solo SMS — attivalo. Subito.", da: "Hvis et site kun tilbyder SMS — slå det til. Nu.", bg: "Ако сайт ти предлага само SMS — включи го. Веднага.", tr: "Bir site sana yalnızca SMS sunuyorsa — aç onu. Hemen şimdi." },
        { en: "If you can pick an authenticator app, even better.", fr: "Si tu peux choisir une appli d'authentification, c'est encore mieux.", es: "Si puedes elegir una app de autenticación, mejor aún.", de: "Wenn du eine Authenticator-App wählen kannst, umso besser.", it: "Se puoi scegliere un'app di autenticazione, ancora meglio.", da: "Hvis du kan vælge en authenticator-app, endnu bedre.", bg: "Ако можеш да избереш приложение за удостоверяване, още по-добре.", tr: "Bir kimlik doğrulayıcı uygulama seçebiliyorsan, daha da iyi." },
        { en: "And for your *most important* accounts — your email and your bank — try a hardware key.", fr: "Et pour tes comptes les *plus précieux* — mail, banque — pense à la clé physique.", es: "Y para tus cuentas *más importantes* — el correo y el banco — prueba una llave física.", de: "Und für deine *wichtigsten* Konten — E-Mail und Bank — probier einen Hardware-Schlüssel.", it: "E per i tuoi account *più importanti* — email e banca — prova una chiave fisica.", da: "Og til dine *vigtigste* konti — e-mail og bank — prøv en hardware-nøgle.", bg: "А за *най-важните* си акаунти — имейл и банка — пробвай хардуерен ключ.", tr: "Ve *en önemli* hesapların için — e-postan ve bankan — bir donanım anahtarı dene." }
      ],
      next: "twofa_state"
    },
    twofa_state: {
      bot: [
        { en: "Quick check-in: which 2FA do you currently use most?", fr: "Petit point rapide : quel type de 2FA tu utilises le plus en ce moment ?", es: "Pequeño chequeo: ¿qué 2FA usas más ahora mismo?", de: "Kurzer Check: welche 2FA nutzt du gerade am meisten?", it: "Piccola verifica: quale 2FA usi di più al momento?", da: "Hurtigt tjek: hvilken 2FA bruger du mest lige nu?", bg: "Бърза проверка: коя 2FA използваш най-много в момента?", tr: "Hızlı bir kontrol: şu anda en çok hangi 2FA'yı kullanıyorsun?" }
      ],
      choices: [
        { label: { en: "SMS codes", fr: "Codes SMS", es: "Códigos SMS", de: "SMS-Codes", it: "Codici SMS", da: "SMS-koder", bg: "SMS кодове", tr: "SMS kodları" }, next: "sms_warning", reaction: { en: "Noted. Then the next bit is *especially* for you.", fr: "Noté. Alors la suite est *spécialement* pour toi.", es: "Apuntado. Entonces lo que viene es *especialmente* para ti.", de: "Notiert. Dann ist das Nächste *besonders* für dich.", it: "Annotato. Allora la prossima parte è *appositamente* per te.", da: "Noteret. Så er det næste *især* til dig.", bg: "Отбелязано. Тогава следващото е *специално* за теб.", tr: "Not aldım. O zaman sıradaki kısım *özellikle* sana." } },
        { label: { en: "An authenticator app", fr: "Une appli d'authentification", es: "Una app de autenticación", de: "Eine Authenticator-App", it: "Un'app di autenticazione", da: "En authenticator-app", bg: "Приложение за удостоверяване", tr: "Bir kimlik doğrulayıcı uygulama" }, next: "sms_warning", reaction: { en: "Lovely. You're already in the comfy middle tier.", fr: "Très bien. Tu es déjà dans la catégorie confort.", es: "Genial. Ya estás en la categoría cómoda intermedia.", de: "Schön. Du bist schon in der gemütlichen Mittelstufe.", it: "Bene. Sei già nella comoda fascia intermedia.", da: "Skønt. Du er allerede i den behagelige mellemkategori.", bg: "Чудесно. Вече си в удобната средна категория.", tr: "Hoş. Zaten rahat orta kademedesin." } },
        { label: { en: "A hardware key (YubiKey etc.)", fr: "Une clé physique (YubiKey etc.)", es: "Una llave física (YubiKey, etc.)", de: "Ein Hardware-Schlüssel (YubiKey usw.)", it: "Una chiave fisica (YubiKey ecc.)", da: "En hardware-nøgle (YubiKey osv.)", bg: "Хардуерен ключ (YubiKey и др.)", tr: "Bir donanım anahtarı (YubiKey vb.)" }, next: "sms_warning", reaction: { en: "Top shelf. Janet is, factually, impressed.", fr: "Le top du top. Janet est, soit dit en passant, impressionnée.", es: "El nivel más alto. Janet está, factualmente, impresionada.", de: "Oberliga. Janet ist, faktisch, beeindruckt.", it: "Massimo livello. Janet è, fattualmente, colpita.", da: "Topklasse. Janet er, faktuelt, imponeret.", bg: "Най-високо ниво. Janet е, технически, впечатлена.", tr: "En üst seviye. Janet, fiilen, etkilendi." } },
        { label: { en: "None yet", fr: "Rien pour l'instant", es: "Nada todavía", de: "Noch nichts", it: "Ancora niente", da: "Ingen endnu", bg: "Все още нищо", tr: "Henüz yok" }, next: "sms_warning", reaction: { en: "All good — we're about to fix that together.", fr: "Pas de souci — on va régler ça ensemble.", es: "Tranqui — vamos a arreglarlo juntos.", de: "Alles gut — wir kümmern uns gleich darum.", it: "Tutto ok — stiamo per sistemarlo insieme.", da: "Helt fint — det ordner vi sammen.", bg: "Спокойно — ще го оправим заедно.", tr: "Sorun değil — bunu birlikte halledeceğiz." } }
      ]
    },
    sms_warning: {
      bot: [
        { en: "Quick warning about SMS: there's a trick called *SIM swapping* where attackers convince your phone provider to transfer your number to *their* SIM.", fr: "Petite mise en garde sur les SMS : il existe une combine, le *SIM swapping*, où des attaquants embobinent ton opérateur pour qu'il transfère ton numéro vers *leur* carte SIM.", es: "Aviso rápido sobre SMS: existe una técnica llamada *SIM swapping* en la que los atacantes convencen a tu operador para transferir tu número a *su* SIM.", de: "Kurze Warnung zu SMS: Es gibt einen Trick namens *SIM swapping*, bei dem Angreifer deinen Mobilfunkanbieter überreden, deine Nummer auf *ihre* SIM zu übertragen.", it: "Avvertimento rapido sugli SMS: esiste una tecnica chiamata *SIM swapping* in cui gli aggressori convincono il tuo operatore a trasferire il tuo numero sulla *loro* SIM.", da: "Hurtig advarsel om SMS: der findes et trick kaldet *SIM swapping*, hvor angribere overtaler dit teleselskab til at overføre dit nummer til *deres* SIM.", bg: "Кратко предупреждение за SMS: има техника, наречена *SIM swapping*, при която нападателите убеждават мобилния ти оператор да прехвърли номера ти на *тяхната* SIM карта.", tr: "SMS hakkında kısa bir uyarı: *SIM swapping* denilen bir hile var; saldırganlar telefon operatörünü ikna ederek numaranı *kendi* SIM kartlarına aktarttırıyor." },
        { en: "Then your codes arrive on their phone, not yours. Spooky.", fr: "Et là, tes codes atterrissent sur leur téléphone, plus sur le tien. Flippant.", es: "Y entonces tus códigos llegan a su teléfono, no al tuyo. Espeluznante.", de: "Dann landen deine Codes auf ihrem Handy, nicht auf deinem. Gruselig.", it: "E così i tuoi codici arrivano sul loro telefono, non sul tuo. Inquietante.", da: "Så lander dine koder på deres telefon, ikke din. Uhyggeligt.", bg: "И тогава кодовете ти пристигат на техния телефон, не на твоя. Зловещо.", tr: "Sonra kodların seninkine değil, onların telefonuna geliyor. Ürkütücü." },
        { en: "An authenticator app or hardware key avoids that entirely.", fr: "Une appli d'authentification ou une clé physique court-circuite complètement le problème.", es: "Una app de autenticación o una llave física evita el problema por completo.", de: "Eine Authenticator-App oder ein Hardware-Schlüssel umgeht das Problem komplett.", it: "Un'app di autenticazione o una chiave fisica evita del tutto il problema.", da: "En authenticator-app eller hardware-nøgle undgår problemet helt.", bg: "Приложение за удостоверяване или хардуерен ключ напълно избягва този проблем.", tr: "Bir kimlik doğrulayıcı uygulama ya da donanım anahtarı bu sorunu tamamen ortadan kaldırır." }
      ],
      choices: [{ label: { en: "Switching to an app then", fr: "Je passe à une appli alors", es: "Me paso a una app entonces", de: "Dann wechsle ich zu einer App", it: "Allora passo a un'app", da: "Så skifter jeg til en app", bg: "Тогава преминавам към приложение", tr: "O zaman uygulamaya geçiyorum" }, next: "campfire" }]
    },
    campfire: {
      bot: [
        { en: "Smart human.", fr: "Sage décision, ô humain·e.", es: "Humano sabio.", de: "Kluger Mensch.", it: "Umano saggio.", da: "Klogt menneske.", bg: "Умен човек.", tr: "Akıllı insan." },
        { en: "Last tip: the *campfire rule*. Scouts say — leave the campsite cleaner than you found it.", fr: "Dernier conseil : la *règle du feu de camp*. Chez les scouts, on dit : laisse le campement plus propre que tu ne l'as trouvé.", es: "Último consejo: la *regla del campamento*. Los scouts dicen — deja el campamento más limpio de lo que lo encontraste.", de: "Letzter Tipp: die *Lagerfeuer-Regel*. Bei den Pfadfindern heißt es — verlasse den Lagerplatz sauberer, als du ihn vorgefunden hast.", it: "Ultimo consiglio: la *regola del campo*. Gli scout dicono — lascia il campo più pulito di come l'hai trovato.", da: "Sidste tip: *bålpladsreglen*. Spejderne siger — efterlad lejrpladsen renere, end du fandt den.", bg: "Последен съвет: *правилото на лагерния огън*. Скаутите казват — остави лагера по-чист, отколкото си го намерил.", tr: "Son tüyo: *kamp ateşi kuralı*. İzcilerin dediği gibi — kamp alanını bulduğundan daha temiz bırak." },
        { en: "Each time you log in to an account, take 30 seconds to turn on 2FA if it isn't already on.", fr: "Chaque fois que tu te connectes à un compte, prends 30 secondes pour activer la 2FA si ce n'est pas déjà fait.", es: "Cada vez que inicies sesión en una cuenta, dedica 30 segundos a activar el 2FA si no lo está ya.", de: "Jedes Mal, wenn du dich bei einem Konto anmeldest, nimm dir 30 Sekunden, um 2FA einzuschalten, falls noch nicht geschehen.", it: "Ogni volta che accedi a un account, prenditi 30 secondi per attivare la 2FA se non è già attiva.", da: "Hver gang du logger ind på en konto, så tag 30 sekunder til at slå 2FA til, hvis det ikke allerede er.", bg: "Всеки път, когато влизаш в акаунт, отдели 30 секунди, за да включиш 2FA, ако още не е включена.", tr: "Bir hesaba her giriş yaptığında, henüz açık değilse 2FA'yı açmak için 30 saniye ayır." },
        { en: "In a few months, your whole digital life will be protected — without ever scheduling a \"security afternoon.\"", fr: "En quelques mois, toute ta vie numérique sera protégée — sans avoir bloqué un seul \"après-midi sécurité\" dans ton agenda.", es: "En unos meses, toda tu vida digital estará protegida — sin haber programado ni una sola \"tarde de seguridad\".", de: "In ein paar Monaten ist dein ganzes digitales Leben geschützt — ohne dass du je einen \"Sicherheitsnachmittag\" einplanen musstest.", it: "In pochi mesi, tutta la tua vita digitale sarà protetta — senza aver mai pianificato un \"pomeriggio sicurezza\".", da: "På få måneder vil hele dit digitale liv være beskyttet — uden at du nogensinde har planlagt en \"sikkerhedseftermiddag\".", bg: "След няколко месеца целият ти дигитален живот ще е защитен — без никога да си планирал „следобед на сигурността“.", tr: "Birkaç ay içinde, tüm dijital hayatın korunmuş olacak — hiç \"güvenlik öğleden sonrası\" planlamadan." }
      ],
      choices: [{ label: { en: "I love it", fr: "J'adore", es: "Me encanta", de: "Liebe ich", it: "Mi piace un sacco", da: "Jeg elsker det", bg: "Обожавам го", tr: "Bayıldım" }, next: "outro" }]
    },
    outro: {
      bot: [
        { en: "If you're picking an order: email first, then bank, then socials, then everything else. That's what Janet recommends.", fr: "S'il te faut un ordre : la boîte mail d'abord, puis la banque, puis les réseaux sociaux, puis tout le reste. Voilà ce que Janet conseille.", es: "Si buscas un orden: primero el correo, luego el banco, luego las redes sociales, después el resto. Eso recomienda Janet.", de: "Falls du eine Reihenfolge brauchst: zuerst E-Mail, dann Bank, dann soziale Netzwerke, dann der Rest. Das empfiehlt Janet.", it: "Se cerchi un ordine: prima l'email, poi la banca, poi i social, poi tutto il resto. Ecco cosa consiglia Janet.", da: "Hvis du leder efter en rækkefølge: e-mail først, så bank, så sociale medier, så resten. Det anbefaler Janet.", bg: "Ако търсиш ред: първо имейлът, после банката, после социалните мрежи, после останалото. Това препоръчва Janet.", tr: "Bir sıra arıyorsan: önce e-posta, sonra banka, sonra sosyal medya, sonra geri kalan her şey. Janet'in önerisi bu." },
        { en: "You're about to be very hard to break into. I am, factually, delighted. Bye for now! 🔐", fr: "Tu vas devenir un coffre-fort sur pattes. Et Janet, elle, en est ravie. À très vite ! 🔐", es: "Estás a punto de ser muy difícil de vulnerar. Estoy, factualmente, encantada. ¡Hasta pronto! 🔐", de: "Du wirst gleich sehr schwer zu knacken sein. Ich bin, faktisch, entzückt. Bis bald! 🔐", it: "Stai per diventare molto difficile da violare. Sono, fattualmente, deliziata. A presto! 🔐", da: "Du er ved at blive meget svær at bryde ind hos. Jeg er, faktuelt, henrykt. Vi ses! 🔐", bg: "На път си да станеш много труден за разбиване. Аз съм, технически, във възторг. До скоро! 🔐", tr: "İçine girmek çok zor biri olmak üzeresin. Fiilen, çok mutluyum. Şimdilik hoşça kal! 🔐" }
      ],
      end: true
    }
  }
};
